"""
Substitueix completament el catàleg global de POMs (S12-A).

Operació al schema `public`. Esborra i recrea POMGlobal i POMCategory
amb el catàleg ampliat de 106 POMs i 15 categories (afegeix
'Technical / Workwear' i 'Accessories').

Idempotent: es pot reexecutar sense efectes laterals.
"""
from django.core.management.base import BaseCommand
from django.db import transaction
from django_tenants.utils import schema_context

from fhort.pom.models import POMGlobal, POMCategory


# (codi, nom_en, nom_ca, display_order, descripcio_en)
CATEGORIES = [
    ('Upper body',           'Upper body',           'Part superior del cos',  1,
     'Chest, waist, hip, shoulder, back, armhole, body length'),
    ('Sleeve',               'Sleeve',               'Màniga',                 2,
     'All sleeve and arm measurements: length, width, cuff'),
    ('Collar / Neckline',    'Collar / Neckline',    'Coll / Escot',           3,
     'Neck width, drop, collar dimensions'),
    ('Lower body',           'Lower body',           'Part inferior del cos',  4,
     'Hip, thigh, knee, leg opening, inseam, outseam'),
    ('Waistband',            'Waistband',            'Cinturó',                5,
     'Waistband width (relaxed/stretched) and height'),
    ('Rise',                 'Rise',                 'Tiro',                   6,
     'Front rise, back rise, total rise'),
    ('Skirt / Dress',        'Skirt / Dress',        'Faldilla / Vestit',      7,
     'Skirt length, dress length, sweep'),
    ('Hem / Finish',         'Hem / Finish',         'Baix de peça / Acabat',  8,
     'Bottom hem width, allowance, rib hem'),
    ('Knitwear-specific',    'Knitwear-specific',    'Específic de punt',      9,
     'Relaxed and stretched measurements for knitwear'),
    ('Swimwear-specific',    'Swimwear-specific',    'Específic de bany',     10,
     'Cup, strap, crotch and leg opening for swimwear'),
    ('Closure / Detail',     'Closure / Detail',     'Tancament / Detall',    11,
     'Zipper, buttons, placket, pockets, hood, snaps, straps'),
    ('Jacket / Coat',        'Jacket / Coat',        'Jaqueta / Abric',       12,
     'Jacket/coat specific: lapel, gorge, chest pocket'),
    ('Placement',            'Placement',            'Col·locació',           13,
     'Label, logo, print and pocket placement distances'),
    ('Accessories',          'Accessories',          'Accessoris',            14,
     'Accessory items: belts, ties, scarves'),
    ('Technical / Workwear', 'Technical / Workwear', 'Tècnic / Laboral',      15,
     'Sportswear, outdoor, technical and workwear POMs'),
]


# (codi, nom_en, nom_ca, categoria, abbreviation,
#  descripcio_en, descripcio_ca,
#  start_point, end_point, reference_point,
#  scope, orientation, state, line, body_section,
#  is_key, tol_prod_cm, tol_samp_cm,
#  applies_woven, applies_knit, applies_swim,
#  actiu, notes, iso_ref)
POMS = [
    # ─── UPPER BODY ───────────────────────────────────────────────────────────
    ('POM-001','Chest width','Ample de pit','Upper body','CH',
     'Measure straight across the chest from side seam to side seam, 1 inch (2.5 cm) below the armhole, garment laid flat.',
     'Mesura horitzontal de costura lateral a costura lateral, 1 cm per sota de la sisa. Peça plana.',
     'Side seam','Side seam','1 inch below armhole',
     'HALF','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     True,1.0,0.5,True,True,False,True,'',''),
    ('POM-002','Chest circumference','Circumferència de pit','Upper body','CH CIRC',
     'Full circumference of the chest, 1 inch below the armhole. Used for knit specs or when client requests full measurement.',
     'Circumferència completa de pit, 1 cm sota sisa. Per a especificació de punt o quan el client demana mesura completa.',
     'Side seam','Side seam','1 inch below armhole',
     'FULL','HORIZONTAL','RELAXED','STRAIGHT','BOTH',
     True,2.0,1.0,False,True,False,True,'',''),
    ('POM-003','Waist width','Ample de cintura','Upper body','WA',
     'Measure straight across the narrowest part of the torso between chest and hip, at a specified distance from HPS, garment laid flat.',
     'Mesura horitzontal al punt més estret del tors entre pit i maluc, a distància especificada des de HPS. Peça plana.',
     'Side seam','Side seam','Specified distance from HPS (state cm)',
     'HALF','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     True,1.0,0.5,True,True,False,True,'',''),
    ('POM-004','Hip width (top)','Ample de maluc (part superior)','Upper body','HI',
     'Measure straight across at the fullest part of the hip, at a specified distance from HPS or waistband, garment laid flat.',
     'Mesura horitzontal al punt més ample del maluc, a distància especificada des de HPS o cinturó. Peça plana.',
     'Side seam','Side seam','Specified distance from HPS or waistband top (state cm)',
     'HALF','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     True,1.0,0.5,True,True,False,True,'',''),
    ('POM-005','Shoulder width',"Ample d'espatlla",'Upper body','SH',
     'Measure straight across from shoulder seam to shoulder seam, across the top of the back, garment laid flat.',
     "Mesura horitzontal de costura d'espatlla a costura d'espatlla, per la part superior de l'esquena. Peça plana.",
     'Shoulder seam (left)','Shoulder seam (right)','Across top of back',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BACK',
     False,0.75,0.5,True,True,False,True,'',''),
    ('POM-006','Across shoulder (back)','Inter-espatlles posterior','Upper body','AC SH',
     'Measure straight across the upper back from armhole edge to armhole edge, 4 inches below HPS.',
     "Mesura horitzontal de l'esquena de vora de sisa a vora de sisa, 4 polzades sota HPS.",
     'Armhole edge (left)','Armhole edge (right)','4 inches below HPS',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BACK',
     False,0.75,0.5,True,True,False,True,'',''),
    ('POM-007','Across front','Ample davanter mig','Upper body','AC FR',
     'Measure straight across the front from armhole edge to armhole edge, at a specified distance below HPS.',
     'Mesura horitzontal del davanter de vora de sisa a vora de sisa, a distància especificada sota HPS.',
     'Armhole edge (left)','Armhole edge (right)','Specified distance below HPS (state cm)',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','FRONT',
     False,0.75,0.5,True,True,False,True,'',''),
    ('POM-008','Across back','Ample posterior mig','Upper body','AC BK',
     'Measure straight across the back from armhole edge to armhole edge, at a specified distance below HPS.',
     "Mesura horitzontal de l'esquena de vora de sisa a vora de sisa, a distància especificada sota HPS.",
     'Armhole edge (left)','Armhole edge (right)','Specified distance below HPS (state cm)',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BACK',
     False,0.75,0.5,True,True,False,True,'',''),
    ('POM-009','Body length (HPS front)','Longitud cos des de HPS davanter','Upper body','BL HPS',
     'Measure from HPS (High Point Shoulder) straight down the center front to the bottom hem, garment laid flat.',
     'Mesura vertical des de HPS fins al baix de la peça, centre davanter. Peça plana.',
     'HPS (front)','Bottom hem','Center front',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     True,1.5,1.0,True,True,False,True,'',''),
    ('POM-010','Body length (CB)','Longitud cos des de CB','Upper body','BL CB',
     'Measure from the center back neck seam straight down to the bottom hem, garment laid flat.',
     'Mesura vertical des de la costura del coll al centre posterior fins al baix de la peça. Peça plana.',
     'CB neck seam','Bottom hem','Center back',
     'FULL','VERTICAL','FLAT','STRAIGHT','BACK',
     False,1.5,1.0,True,True,False,True,'',''),
    ('POM-011','Side seam length','Longitud costura lateral','Upper body','SS',
     'Measure straight down the side seam from the bottom of the armhole to the bottom hem.',
     'Mesura vertical per la costura lateral des del punt baix de la sisa fins al baix de la peça.',
     'Bottom of armhole','Bottom hem','Side seam',
     'FULL','VERTICAL','FLAT','STRAIGHT','SIDE',
     False,1.5,1.0,True,True,False,True,'',''),
    ('POM-012','Armhole depth','Profunditat de sisa','Upper body','AH DEP',
     'Measure straight from the shoulder seam to the bottom of the armhole, following the side seam, garment laid flat.',
     "Mesura recta des de la costura d'espatlla fins al punt baix de la sisa, seguint la costura lateral.",
     'Shoulder seam','Bottom of armhole','Side seam',
     'FULL','VERTICAL','FLAT','STRAIGHT','SIDE',
     False,0.75,0.5,True,True,False,True,'',''),
    ('POM-013','Armhole circumference','Circumferència de sisa','Upper body','AH CIRC',
     'Measure along the curve of the entire armhole seam from top to bottom and back to top.',
     "Mesura seguint el contorn de tota la costura de la sisa, de dalt a baix i de tornada al punt d'inici.",
     'Shoulder seam top','Shoulder seam top','Full armhole seam',
     'FULL','CURVED','FLAT','ALONG CURVE','SIDE',
     False,1.0,0.5,True,True,False,True,'',''),
    ('POM-014','Shoulder drop',"Caiguda d'espatlla",'Upper body','SH DR',
     'Measure vertically from HPS to the shoulder seam at the armhole edge.',
     "Mesura vertical des de HPS fins a la costura d'espatlla en el punt de la sisa.",
     'HPS','Shoulder seam at armhole','Vertical drop',
     'FULL','VERTICAL','FLAT','STRAIGHT','BACK',
     False,0.5,0.25,True,True,False,True,'',''),
    ('POM-019','Shoulder slope / pitch',"Inclinació de l'espatlla",'Upper body','SS SLOPE',
     'Vertical drop from side neck point to shoulder seam point. Determines shoulder angle.',
     "Caiguda vertical des del punt lateral del coll al punt de l'espatlla.",
     'Side neck point (SNP)','Shoulder point (SP)','Vertical drop',
     'FULL','VERTICAL','FLAT','ANGLED','BACK',
     False,0.5,0.25,True,True,False,True,'Add: ISO §5.6.2. Critical for fit.','ISO 8559-1 §5.6.2'),
    ('POM-083','Underbust girth','Perímetre sota pit','Upper body','UB',
     'Measure girth around torso immediately below the bust.',
     'Perímetre immediatament per sota del pit.',
     'Below bust','Below bust','Immediately below bust',
     'FULL','CIRCUMFERENCE','RELAXED','CURVED','BOTH',
     True,1.0,0.5,True,True,True,True,'Add: ISO §5.3.8. Essential for bra/swimwear.','ISO 8559-1 §5.3.8'),
    ('POM-084','Bust cup depth (calculated)','Copa del pit (calculada)','Upper body','CUP',
     'Calculated: bust girth minus underbust girth. Indicates cup size.',
     'Calculat: perímetre pit menys perímetre sota pit. Indica la copa.',
     'Calculated','Calculated','Bust minus underbust',
     'CALCULATED','CIRCUMFERENCE','ON_BODY','CURVED','FRONT',
     True,1.0,0.5,True,False,True,True,'Add: ISO §5.7.7. Bra/swimwear development.','ISO 8559-1 §5.7.7'),

    # ─── COLLAR / NECKLINE ────────────────────────────────────────────────────
    ('POM-015','Neck base girth','Perímetre base del coll','Collar / Neckline','NC',
     'Measure the girth around the base of the neck. Garment equivalent: neckband circumference relaxed.',
     'Perímetre base del coll. Equivalent de peça: neckband relaxat.',
     'Side neck point','Side neck point','Around neck base',
     'FULL','CIRCUMFERENCE','RELAXED','CURVED','BOTH',
     False,1.0,0.5,True,True,False,True,'Add: ISO 8559-1 §5.3.3.','ISO 8559-1 §5.3.3'),
    ('POM-030','Neck width',"Ample d'escot",'Collar / Neckline','NK W',
     'Measure straight across the neckline from seam to seam at the HPS level, garment laid flat.',
     "Mesura horitzontal de l'escot de costura a costura a l'alçada del HPS. Peça plana.",
     'Neck seam (left HPS)','Neck seam (right HPS)','At HPS level',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,0.5,0.25,True,True,False,True,'',''),
    ('POM-031','Neck drop front',"Caiguda d'escot davantera",'Collar / Neckline','NK DR FR',
     'Measure vertically from the HPS level down to the lowest point of the front neckline.',
     "Mesura vertical des del nivell HPS fins al punt més baix de l'escot davanter.",
     'HPS level','Lowest point of front neckline','Center front',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     False,0.5,0.25,True,True,False,True,'',''),
    ('POM-032','Neck drop back',"Caiguda d'escot posterior",'Collar / Neckline','NK DR BK',
     'Measure vertically from the HPS level down to the lowest point of the back neckline.',
     "Mesura vertical des del nivell HPS fins al punt més baix de l'escot posterior.",
     'HPS level','Lowest point of back neckline','Center back',
     'FULL','VERTICAL','FLAT','STRAIGHT','BACK',
     False,0.5,0.25,True,True,False,True,'',''),
    ('POM-033','Collar length','Longitud de coll','Collar / Neckline','COL L',
     'Measure the full length of the collar, stretched flat, from one end to the other along the outer edge.',
     "Mesura la longitud total del coll estès pla, d'un extrem a l'altre per la vora exterior.",
     'Collar end (left)','Collar end (right)','Along outer collar edge, fully extended',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,0.5,0.25,True,False,False,True,'',''),
    ('POM-034','Collar height (CB stand)','Alçada de coll al CB','Collar / Neckline','COL H CB',
     'Measure the height of the collar stand at center back, from the seam joining the collar to the garment to the top fold or edge.',
     "Mesura l'alçada del peu de coll al centre posterior, des de la costura d'unió fins al plec o vora superior.",
     'CB collar/garment seam','CB collar top fold/edge','Center back',
     'FULL','VERTICAL','FLAT','STRAIGHT','BACK',
     False,0.5,0.25,True,False,False,True,'',''),
    ('POM-035','Collar height (CF)','Alçada de coll al CF','Collar / Neckline','COL H CF',
     'Measure the height of the collar at center front, from the seam joining the collar to the garment to the top edge.',
     "Mesura l'alçada del coll al centre davanter, des de la costura d'unió fins a la vora superior.",
     'CF collar/garment seam','CF collar top edge','Center front',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     False,0.5,0.25,True,False,False,True,'',''),
    ('POM-036','Neckband circumference (relaxed)','Circumferència de coll (relaxat)','Collar / Neckline','NK CIRC RLX',
     'Measure the full circumference of the neckband or neckline seam, garment relaxed and laid flat.',
     "Mesura la circumferència completa del coll o costura de l'escot, peça relaxada i plana.",
     'Neckline seam start','Neckline seam start','Full neckline seam, along curve',
     'FULL','CURVED','RELAXED','ALONG CURVE','BOTH',
     False,1.0,0.5,True,True,False,True,'',''),

    # ─── SLEEVE ───────────────────────────────────────────────────────────────
    ('POM-016','Upper arm girth','Perímetre part superior del braç','Sleeve','UA',
     'Measure girth around fullest part of upper arm, perpendicular to arm axis.',
     'Perímetre al punt més ample de la part superior del braç.',
     'Fullest upper arm','Fullest upper arm','Perpendicular to arm',
     'FULL','CIRCUMFERENCE','RELAXED','CURVED','SLEEVE',
     False,1.0,0.5,True,True,False,True,'Add: ISO §5.3.16. Critical for fitted sleeves.','ISO 8559-1 §5.3.16'),
    ('POM-017','Wrist girth','Perímetre del canell','Sleeve','WG',
     'Measure girth around the wrist at the wrist joint.',
     'Perímetre al canell.',
     'Wrist joint','Wrist joint','At wrist bone',
     'FULL','CIRCUMFERENCE','RELAXED','CURVED','SLEEVE',
     False,0.5,0.25,True,True,False,True,'Add: ISO §5.3.19. For cuff fit.','ISO 8559-1 §5.3.19'),
    ('POM-018','Elbow girth','Perímetre del colze','Sleeve','EG',
     'Measure girth around the elbow when arm is straight.',
     'Perímetre al colze, braç estès.',
     'Elbow point','Elbow point','Arm straight',
     'FULL','CIRCUMFERENCE','RELAXED','CURVED','SLEEVE',
     False,1.0,0.5,True,True,False,True,'Add: ISO §5.3.17. Fitted jackets/sleeves.','ISO 8559-1 §5.3.17'),
    ('POM-020','Sleeve length','Longitud de màniga','Sleeve','SL',
     'Measure from the shoulder seam (top of sleeve head) to the bottom of the sleeve opening, along the top of the sleeve, garment laid flat.',
     "Mesura des de la costura d'espatlla fins al baix de la boca de màniga, per la part superior de la màniga. Peça plana.",
     'Shoulder seam','Sleeve opening','Along top of sleeve',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','SIDE',
     True,1.0,0.5,True,True,False,True,'',''),
    ('POM-021','Sleeve length (underarm)','Longitud de màniga des de soba','Sleeve','SL UA',
     'Measure from the underarm seam intersection to the sleeve opening along the underside of the sleeve.',
     "Mesura des del punt d'unió de la soba fins a la boca de màniga, per la part inferior de la màniga.",
     'Underarm seam','Sleeve opening','Along underside of sleeve',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','SIDE',
     False,1.0,0.5,True,True,False,True,'',''),
    ('POM-022','Sleeve length (CB)','Longitud de màniga des de CB','Sleeve','SL CB',
     'Measure from center back neck across the shoulder seam to the sleeve opening. Used for outerwear and tailored jackets.',
     "Mesura des del centre de coll posterior, per la costura d'espatlla, fins a la boca de màniga. Per a roba exterior.",
     'CB neck','Sleeve opening','Across shoulder and along sleeve',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BACK',
     False,1.5,1.0,True,False,False,True,'',''),
    ('POM-023','Sleeve width at bicep','Ample de màniga al bíceps','Sleeve','BIC',
     'Measure straight across the sleeve from seam to seam, 1 inch below the armhole, perpendicular to the sleeve length.',
     'Mesura horitzontal de costura a costura, 1 polzada sota la sisa, perpendicular a la longitud de la màniga.',
     'Sleeve seam (front)','Sleeve seam (back)','1 inch below armhole',
     'HALF','HORIZONTAL','FLAT','STRAIGHT','SIDE',
     False,0.75,0.5,True,True,False,True,'',''),
    ('POM-024','Sleeve width at elbow','Ample de màniga al colze','Sleeve','ELB',
     'Measure straight across the sleeve at the midpoint of the sleeve length (elbow level), perpendicular to sleeve length.',
     'Mesura horitzontal al punt mig de la longitud de màniga (alçada de colze), perpendicular a la longitud.',
     'Sleeve seam (front)','Sleeve seam (back)','Midpoint of sleeve length',
     'HALF','HORIZONTAL','FLAT','STRAIGHT','SIDE',
     False,0.75,0.5,True,True,False,True,'',''),
    ('POM-025','Sleeve opening / Cuff width','Ample de boca de màniga / Puny','Sleeve','SL OP',
     'Measure straight across the sleeve opening or cuff from seam to seam, garment laid flat and relaxed.',
     'Mesura horitzontal de la boca de màniga o puny, de costura a costura. Peça plana i relaxada.',
     'Sleeve seam (front)','Sleeve seam (back)','At sleeve opening',
     'HALF','HORIZONTAL','FLAT','STRAIGHT','SIDE',
     False,0.5,0.25,True,True,False,True,'',''),
    ('POM-026','Sleeve opening stretched','Boca de màniga estirada','Sleeve','SL OP STR',
     'Measure straight across the sleeve opening stretched to its fullest extent, from seam to seam.',
     'Mesura horitzontal de la boca de màniga estirada al màxim, de costura a costura.',
     'Sleeve seam (front)','Sleeve seam (back)','At sleeve opening, fully stretched',
     'HALF','HORIZONTAL','STRETCHED','STRAIGHT','SIDE',
     False,0.75,0.5,False,True,False,True,'',''),
    ('POM-027','Cuff height','Alçada de puny','Sleeve','CUF H',
     'Measure the height of the cuff from the fold or seam at the top to the sleeve opening at the bottom.',
     "Mesura l'alçada del puny des del plec o costura superior fins a la boca de màniga inferior.",
     'Cuff top fold/seam','Sleeve opening','Along cuff',
     'FULL','VERTICAL','FLAT','STRAIGHT','SIDE',
     False,0.5,0.25,True,False,False,True,'',''),
    ('POM-028','Rib cuff height','Alçada de puny de punt','Sleeve','RIB CUF',
     'Measure the height of the rib cuff, relaxed, from the seam joining the sleeve to the rib edge.',
     "Mesura l'alçada del puny de punt relaxat, des de la costura d'unió amb la màniga fins al vora del puny.",
     'Rib/sleeve join seam','Rib edge','Along rib',
     'FULL','VERTICAL','RELAXED','STRAIGHT','SIDE',
     False,0.5,0.25,False,True,False,True,'',''),

    # ─── LOWER BODY ───────────────────────────────────────────────────────────
    ('POM-040','Hip width (pants)','Ample de maluc (pantaló)','Lower body','HI PA',
     'Measure straight across the garment at a specified distance below the waistband top, from side seam to side seam, garment laid flat.',
     'Mesura horitzontal a distància especificada sota la part superior del cinturó, de costura lateral a costura lateral. Peça plana.',
     'Side seam','Side seam','Specified distance below waistband top (state cm, typically 18–23 cm)',
     'HALF','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     True,1.0,0.5,True,True,False,True,'',''),
    ('POM-041','Thigh width','Ample de cuixa','Lower body','THI',
     'Measure straight across the thigh, 1 inch below the crotch seam, from seam to seam, garment laid flat.',
     "Mesura horitzontal de la cuixa, 1 polzada sota la costura de l'entrecuix, de costura a costura. Peça plana.",
     'Leg seam (front/inseam)','Leg seam (back/outseam)','1 inch below crotch seam',
     'HALF','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,0.75,0.5,True,True,False,True,'',''),
    ('POM-042','Knee width','Ample de genoll','Lower body','KNE',
     'Measure straight across the leg at the knee level (midpoint between crotch seam and leg opening), from seam to seam.',
     "Mesura horitzontal a l'alçada del genoll (punt mig entre entrecuix i baix de cama), de costura a costura.",
     'Leg seam (front/inseam)','Leg seam (back/outseam)','At knee level (midpoint between crotch and leg opening)',
     'HALF','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,0.75,0.5,True,True,False,True,'',''),
    ('POM-043','Leg opening','Obertura de cama','Lower body','LEG OP',
     'Measure straight across the leg opening from seam to seam at the very bottom of the leg, garment laid flat.',
     'Mesura horitzontal de la boca de cama de costura a costura al punt baix de la cama. Peça plana.',
     'Inseam edge','Outseam edge','At leg opening (bottom hem)',
     'HALF','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     True,0.75,0.5,True,True,False,True,'',''),
    ('POM-044','Inseam length',"Longitud d'entrecuix",'Lower body','INS',
     'Measure from the crotch seam intersection straight down to the leg opening along the inside seam.',
     "Mesura des de la intersecció de la costura de l'entrecuix fins a la boca de cama per la costura interior.",
     'Crotch seam intersection','Leg opening','Along inseam',
     'FULL','VERTICAL','FLAT','STRAIGHT','SIDE',
     True,1.5,1.0,True,True,False,True,'',''),
    ('POM-045','Outseam length','Longitud exterior de cama','Lower body','OUTS',
     'Measure from the top of the waistband to the leg opening along the outside seam.',
     'Mesura des de la part superior del cinturó fins a la boca de cama per la costura exterior.',
     'Waistband top','Leg opening','Along outseam',
     'FULL','VERTICAL','FLAT','STRAIGHT','SIDE',
     False,1.5,1.0,True,True,False,True,'',''),
    ('POM-046','Thigh girth','Perímetre de la cuixa','Lower body','TH',
     'Measure girth around fullest part of thigh, 1 inch below crotch seam.',
     'Perímetre al punt més ample de la cuixa, 1" sota costura entrecama.',
     'Fullest thigh','Fullest thigh','1 inch below crotch seam',
     'FULL','CIRCUMFERENCE','RELAXED','CURVED','BOTH',
     True,1.0,0.5,True,True,False,True,'Add: ISO §5.3.20. Key for fitted trousers/leggings.','ISO 8559-1 §5.3.20'),
    ('POM-047','Knee girth','Perímetre del genoll','Lower body','KG',
     'Measure girth around the knee at the kneecap level.',
     'Perímetre al nivell del genoll.',
     'Knee cap level','Knee cap level','At knee',
     'FULL','CIRCUMFERENCE','RELAXED','CURVED','BOTH',
     False,1.0,0.5,True,True,False,True,'Add: ISO §5.3.22. Skinny trousers/leggings.','ISO 8559-1 §5.3.22'),
    ('POM-048','Calf girth','Perímetre del panxell','Lower body','CG',
     'Measure girth around fullest part of calf.',
     'Perímetre al punt més ample del panxell.',
     'Fullest calf','Fullest calf','Fullest point',
     'FULL','CIRCUMFERENCE','RELAXED','CURVED','BOTH',
     False,1.0,0.5,True,True,False,True,'Add: ISO §5.3.24. Boot-cut trousers.','ISO 8559-1 §5.3.24'),
    ('POM-049','Ankle girth','Perímetre del turmell','Lower body','AG',
     'Measure girth around ankle at narrowest point above ankle bone.',
     'Perímetre al turmell, punt més estret.',
     'Ankle bone','Ankle bone','Narrowest point',
     'FULL','CIRCUMFERENCE','RELAXED','CURVED','BOTH',
     False,0.5,0.25,True,True,False,True,'Add: ISO §5.3.26. Ankle trousers/boots.','ISO 8559-1 §5.3.26'),
    ('POM-121','Leg opening (bodysuit, relaxed)','Obertura cama body relaxada','Lower body','LOB',
     'Leg opening of bodysuit measured flat, relaxed.',
     'Obertura de cama de body plana i relaxada.',
     'Seam edge','Seam edge','Leg hem flat relaxed',
     'HALF','HORIZONTAL','RELAXED','CURVED','BOTH',
     True,0.5,0.25,False,True,True,True,'Add: Baby/swimwear. Bodysuits, leotards.',''),

    # ─── WAISTBAND ────────────────────────────────────────────────────────────
    ('POM-050','Waistband width (relaxed)','Ample de cinturó (relaxat)','Waistband','WB RLX',
     'Measure straight across the top edge of the waistband from side edge to side edge, waistband lying flat and relaxed.',
     'Mesura horitzontal de la part superior del cinturó, de vora a vora, cinturó pla i relaxat.',
     'Waistband side edge (left)','Waistband side edge (right)','Top edge of waistband, relaxed',
     'HALF','HORIZONTAL','RELAXED','STRAIGHT','BOTH',
     True,1.0,0.5,True,True,True,True,'',''),
    ('POM-051','Waistband width (stretched)','Ample de cinturó (estès)','Waistband','WB STR',
     'Measure straight across the waistband stretched to its fullest extent, from side edge to side edge.',
     'Mesura horitzontal del cinturó estès al màxim, de vora a vora.',
     'Waistband side edge (left)','Waistband side edge (right)','Fully stretched',
     'HALF','HORIZONTAL','STRETCHED','STRAIGHT','BOTH',
     False,1.5,1.0,False,True,True,True,'',''),
    ('POM-052','Waistband height','Alçada de cinturó','Waistband','WB H',
     'Measure the height of the waistband from the top edge to the seam joining the waistband to the garment body.',
     "Mesura l'alçada del cinturó des de la vora superior fins a la costura d'unió amb el cos de la peça.",
     'Waistband top edge','Waistband/body seam','Along center front or center back',
     'FULL','VERTICAL','FLAT','STRAIGHT','BOTH',
     False,0.5,0.25,True,True,True,True,'',''),

    # ─── RISE ─────────────────────────────────────────────────────────────────
    ('POM-055','Rise (front)','Cavall davanter','Rise','RI FR',
     'Measure vertically from the crotch seam intersection up along the center front seam to the top edge of the front waistband.',
     "Mesura vertical des de la intersecció de la costura de l'entrecuix fins a la part superior del cinturó, centre davanter.",
     'Crotch seam intersection','Waistband top edge','Along center front seam',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     True,0.75,0.5,True,True,False,True,'',''),
    ('POM-056','Rise (back)','Cavall posterior','Rise','RI BK',
     'Measure vertically from the crotch seam intersection up along the center back seam to the top edge of the back waistband.',
     "Mesura vertical des de la intersecció de la costura de l'entrecuix fins a la part superior del cinturó, centre posterior.",
     'Crotch seam intersection','Waistband top edge','Along center back seam',
     'FULL','VERTICAL','FLAT','STRAIGHT','BACK',
     False,0.75,0.5,True,True,False,True,'',''),
    ('POM-057','Rise (total)','Cavall total','Rise','RI TOT',
     'Front rise plus back rise combined. Measure from front waistband top edge, through crotch seam, to back waistband top edge.',
     "Cavall davanter més cavall posterior. Des de la vora superior del cinturó davanter, passant per l'entrecuix, fins a la vora superior del cinturó posterior.",
     'Front waistband top','Back waistband top','Through crotch seam',
     'FULL','VERTICAL','FLAT','STRAIGHT','BOTH',
     False,1.5,1.0,True,True,False,True,'',''),

    # ─── SKIRT / DRESS ────────────────────────────────────────────────────────
    ('POM-060','Skirt length','Longitud de faldilla','Skirt / Dress','SK L',
     'Measure from the top edge of the waistband straight down to the bottom hem along the center front.',
     'Mesura des de la vora superior del cinturó fins al baix de la peça, centre davanter.',
     'Waistband top edge','Bottom hem','Center front',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     True,1.5,1.0,True,True,False,True,'',''),
    ('POM-061','Dress length (HPS)','Longitud de vestit (HPS)','Skirt / Dress','DR L HPS',
     'Measure from HPS straight down to the bottom hem along the center front, garment laid flat.',
     'Mesura des de HPS fins al baix de la peça, centre davanter. Peça plana.',
     'HPS (front)','Bottom hem','Center front',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     True,1.5,1.0,True,True,False,True,'',''),
    ('POM-062','Skirt sweep (bottom width)','Amplada de baix de faldilla','Skirt / Dress','SK SW',
     'Measure straight across the bottom hem of the skirt or dress from edge to edge, garment laid flat.',
     'Mesura horitzontal del baix de la faldilla o vestit de vora a vora. Peça plana.',
     'Side seam (left)','Side seam (right)','At bottom hem',
     'HALF','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,1.5,1.0,True,True,False,True,'',''),

    # ─── HEM / FINISH ─────────────────────────────────────────────────────────
    ('POM-070','Bottom hem width','Ample de baix (peça plana)','Hem / Finish','HEM W',
     'Measure straight across the bottom of the garment from side seam to side seam, garment laid flat.',
     'Mesura horitzontal del baix de la peça de costura lateral a costura lateral. Peça plana.',
     'Side seam (left)','Side seam (right)','At bottom hem',
     'HALF','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,1.5,1.0,True,True,False,True,'',''),
    ('POM-071','Hem allowance','Tombada de baix','Hem / Finish','HEM ALL',
     'Measure the width of the hem fold or hem allowance at the bottom of the garment.',
     "Mesura l'amplada de la tombada o sobrant de costura del baix de la peça.",
     'Fold line or hem stitch','Raw edge or fold edge','Along hem',
     'FULL','VERTICAL','FLAT','STRAIGHT','BOTH',
     False,0.25,0.25,True,True,True,True,'',''),
    ('POM-072','Rib hem height','Alçada de baix de punt','Hem / Finish','RIB HEM H',
     'Measure the height of the rib hem band at the bottom of the garment, relaxed.',
     "Mesura l'alçada de la banda de punt del baix de la peça, relaxada.",
     'Rib/body join seam','Rib bottom edge','Center front or center back',
     'FULL','VERTICAL','RELAXED','STRAIGHT','BOTH',
     False,0.5,0.25,False,True,False,True,'',''),
    ('POM-073','Rib hem width (stretched)','Ample baix peça elàstic estirat','Hem / Finish','RHS',
     'Measure elasticated or rib hem fully stretched flat, edge to edge.',
     'Mesura del baix elàstic o de punt totalment estirat.',
     'Seam edge','Seam edge','Fully stretched',
     'HALF','HORIZONTAL','STRETCHED','STRAIGHT','BOTH',
     False,1.0,0.5,False,True,False,True,'Add: Knitwear/elasticated hem. Verifies stretch recovery.',''),

    # ─── KNITWEAR-SPECIFIC ────────────────────────────────────────────────────
    ('POM-080','Chest width (relaxed)','Ample de pit (relaxat)','Knitwear-specific','CH RLX',
     'Measure straight across the chest, 1 inch below the armhole, garment fully relaxed and laid flat without stretching.',
     'Mesura horitzontal del pit, 1 cm sota sisa, peça completament relaxada i plana, sense estirar.',
     'Side seam','Side seam','1 inch below armhole, fully relaxed',
     'HALF','HORIZONTAL','RELAXED','STRAIGHT','BOTH',
     True,1.0,0.5,False,True,False,True,'',''),
    ('POM-081','Chest width (stretched)','Ample de pit (estès)','Knitwear-specific','CH STR',
     'Measure straight across the chest stretched to its fullest comfortable extent, 1 inch below the armhole.',
     'Mesura horitzontal del pit estirat al màxim còmode, 1 cm sota sisa.',
     'Side seam','Side seam','1 inch below armhole, fully stretched',
     'HALF','HORIZONTAL','STRETCHED','STRAIGHT','BOTH',
     False,1.5,1.0,False,True,False,True,'',''),
    ('POM-082','Body length (knitwear, relaxed)','Longitud cos (punt, relaxat)','Knitwear-specific','BL KN RLX',
     'Measure from HPS to the bottom of the rib hem, garment fully relaxed and laid flat, not stretched vertically.',
     'Mesura des de HPS fins al baix del doblet de punt, peça completament relaxada i plana, sense estirar verticalment.',
     'HPS (front)','Bottom rib edge','Center front, fully relaxed',
     'FULL','VERTICAL','RELAXED','STRAIGHT','FRONT',
     True,1.5,1.0,False,True,False,True,'',''),

    # ─── SWIMWEAR-SPECIFIC ────────────────────────────────────────────────────
    ('POM-085','Bikini top / Bra cup width','Ample de copa','Swimwear-specific','CUP W',
     'Measure the maximum horizontal width of one cup, garment laid flat and relaxed.',
     "Mesura l'amplada màxima horitzontal d'una copa, peça plana i relaxada.",
     'Cup edge (left)','Cup edge (right)','Across widest part of cup',
     'FULL','HORIZONTAL','RELAXED','STRAIGHT','FRONT',
     True,0.5,0.25,False,False,True,True,'',''),
    ('POM-086','Bikini top / Bra cup height','Alçada de copa','Swimwear-specific','CUP H',
     'Measure the maximum vertical height of one cup, from the bottom seam to the top edge, garment laid flat.',
     "Mesura l'alçada màxima vertical d'una copa, des de la costura inferior fins a la vora superior. Peça plana.",
     'Cup bottom seam','Cup top edge','Center of cup',
     'FULL','VERTICAL','RELAXED','STRAIGHT','FRONT',
     False,0.5,0.25,False,False,True,True,'',''),
    ('POM-087','Strap width (swimwear)','Ample de tirant (bany)','Swimwear-specific','STRAP W SW',
     'Measure the width of the swimwear strap at its midpoint, garment laid flat.',
     "Mesura l'amplada del tirant de bany al seu punt central. Peça plana.",
     'Strap edge (left)','Strap edge (right)','At midpoint of strap',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,0.25,0.25,False,False,True,True,'',''),
    ('POM-088','Swimwear crotch width',"Ample d'entrecuix de bany",'Swimwear-specific','SW CROT W',
     'Measure the width of the crotch gusset at its narrowest point, garment laid flat.',
     "Mesura l'amplada de l'entrepanys de l'entrecuix al punt més estret. Peça plana.",
     'Gusset seam (left)','Gusset seam (right)','At narrowest point of gusset',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     True,0.5,0.25,False,False,True,True,'',''),
    ('POM-089','Swimwear leg opening','Obertura de cama de bany','Swimwear-specific','SW LEG OP',
     'Measure the circumference of the leg opening of a swimsuit, garment laid flat (measure half, edge to edge).',
     "Mesura la circumferència de l'obertura de cama d'un bany, peça plana (mesurar la meitat, de vora a vora).",
     'Leg opening seam edge (front)','Leg opening seam edge (back)','At leg opening, relaxed',
     'HALF','CURVED','RELAXED','ALONG CURVE','BOTH',
     False,0.75,0.5,False,False,True,True,'',''),

    # ─── CLOSURE / DETAIL ─────────────────────────────────────────────────────
    ('POM-090','Zipper length','Longitud de cremallera','Closure / Detail','ZIP L',
     'Measure from the top stop to the bottom stop of the zipper, zipper lying flat and closed.',
     'Mesura des del top stop fins al bottom stop de la cremallera, cremallera plana i tancada.',
     'Zipper top stop','Zipper bottom stop','Along zipper tape, closed',
     'FULL','VERTICAL','FLAT','STRAIGHT','BOTH',
     False,0.5,0.5,True,True,True,True,'',''),
    ('POM-091','Button spacing','Separació de botons','Closure / Detail','BTN SP',
     'Measure the distance between the centers of two consecutive buttons.',
     'Mesura la distància entre els centres de dos botons consecutius.',
     'Button center (upper)','Button center (lower)','Between two consecutive buttons',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     False,0.25,0.25,True,False,False,True,'',''),
    ('POM-092','Placket width','Ample de botillera','Closure / Detail','PLCK W',
     'Measure the width of the placket from the fold or seam to the edge, garment laid flat.',
     "Mesura l'amplada de la botillera des del plec o costura fins a la vora. Peça plana.",
     'Placket fold/seam','Placket outer edge','Along placket',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','FRONT',
     False,0.25,0.25,True,False,False,True,'',''),
    ('POM-093','Vent length','Longitud de partió','Closure / Detail','VNT L',
     'Measure from the top of the vent opening to the bottom hem along the vent seam or fold.',
     "Mesura des de la part superior de l'obertura de la partió fins al baix de la peça, per la costura o plec.",
     'Vent top opening','Bottom hem','Along vent',
     'FULL','VERTICAL','FLAT','STRAIGHT','BACK',
     False,0.75,0.5,True,False,False,True,'',''),
    ('POM-094','Pleat depth','Profunditat de plec','Closure / Detail','PLT DEP',
     'Measure the depth of one pleat from the fold line to the stitch line or edge, garment laid flat.',
     "Mesura la profunditat d'un plec des de la línia de plec fins a la línia de costura o vora. Peça plana.",
     'Pleat fold line','Pleat stitch line','At widest point of pleat',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,0.25,0.25,True,False,False,True,'',''),
    ('POM-095','Hood height','Alçada de caputxa','Closure / Detail','HD H',
     'Measure from the crown of the hood to the bottom seam joining the hood to the garment, at center back.',
     "Mesura des del punt més alt de la caputxa fins a la costura inferior d'unió amb la peça, al centre posterior.",
     'Hood crown (highest point)','Hood/garment seam','Center back',
     'FULL','VERTICAL','FLAT','STRAIGHT','BACK',
     False,1.0,0.5,True,True,False,True,'',''),
    ('POM-096','Hood width','Ample de caputxa','Closure / Detail','HD W',
     'Measure the maximum width of the hood at its widest point, garment laid flat and hood open.',
     "Mesura l'amplada màxima de la caputxa al punt més ample. Peça plana i caputxa oberta.",
     'Hood edge (left)','Hood edge (right)','At widest point',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,1.0,0.5,True,True,False,True,'',''),
    ('POM-097','Side pocket opening','Obertura de butxaca lateral','Closure / Detail','PKT OP',
     'Measure the length of the side pocket opening from top to bottom.',
     "Mesura la longitud de l'obertura de la butxaca lateral de dalt a baix.",
     'Pocket opening top','Pocket opening bottom','Along pocket opening',
     'FULL','VERTICAL','FLAT','STRAIGHT','SIDE',
     False,0.5,0.5,True,True,False,True,'',''),
    ('POM-098','Pocket width','Ample de butxaca','Closure / Detail','PKT W',
     'Measure the horizontal width of the pocket opening or welt, edge to edge.',
     "Mesura l'amplada horitzontal de l'obertura o viu de la butxaca, de vora a vora.",
     'Pocket edge (left)','Pocket edge (right)','Across pocket opening',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,0.5,0.5,True,True,False,True,'',''),
    ('POM-099','Elastic waist width (relaxed)',"Ample d'elàstic de cintura (relaxat)",'Closure / Detail','EL WA RLX',
     'Measure the width of the elastic waistband channel from side seam to side seam, garment fully relaxed.',
     "Mesura l'ample del canal elàstic de cintura de costura lateral a costura lateral, peça completament relaxada.",
     'Side seam','Side seam','At elastic waistband level, fully relaxed',
     'HALF','HORIZONTAL','RELAXED','STRAIGHT','BOTH',
     False,1.0,0.5,True,True,True,True,'',''),
    ('POM-120','Snap / popper placement','Posició de botons de pressió','Closure / Detail','SNP',
     'Distance from hem to snap center. Critical for babywear bodysuits.',
     'Distància del baix de la peça al centre del botó de pressió.',
     'Hem / seam','Snap center','State reference seam',
     'FULL','VERTICAL','FLAT','STRAIGHT','BOTH',
     False,0.5,0.25,True,True,False,True,'Add: Baby/childrenswear. Bodysuits, rompers.',''),
    ('POM-122','Shoulder opening width','Amplada obertura espatlla','Closure / Detail','SOW',
     'Width of shoulder opening on envelope neck bodysuits, measured flat edge to edge.',
     "Amplada de l'obertura d'espatlla en bodys de sobre, plana.",
     'Seam edge','Seam edge','At shoulder opening',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BACK',
     False,0.5,0.25,True,True,False,True,'Add: Baby/childrenswear envelope neck styles.',''),
    ('POM-126','Strap length (front)','Longitud de tirant davanter','Closure / Detail','STRAP LF',
     'Measure the length of the garment strap from the front attachment point to the front seam, laid flat.',
     "Mesura la longitud del tirant des del punt d'ancoratge davanter fins a la costura davantera, pla.",
     'Front attachment point','Front seam/edge','Along strap, laid flat',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     False,0.5,0.5,True,True,False,True,'Tirants per a vestits, bodysuits, salopetes.',''),
    ('POM-127','Strap length (back)','Longitud de tirant posterior','Closure / Detail','STRAP LB',
     'Measure the length of the garment strap from the back attachment point to the back seam, laid flat.',
     "Mesura la longitud del tirant des del punt d'ancoratge posterior fins a la costura posterior, pla.",
     'Back attachment point','Back seam/edge','Along strap, laid flat',
     'FULL','VERTICAL','FLAT','STRAIGHT','BACK',
     False,0.5,0.5,True,True,False,True,'Tirants per a vestits, bodysuits, salopetes.',''),
    ('POM-128','Strap width (garment)','Amplada de tirant (peça)','Closure / Detail','STRAP W',
     'Measure the width of the garment shoulder or body strap at its midpoint, laid flat.',
     "Mesura l'amplada del tirant d'espatlla o cos de la peça al seu punt central, pla.",
     'Strap edge (left)','Strap edge (right)','At midpoint of strap',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,0.25,0.25,True,True,False,True,'Tirants generals (no swimwear).',''),
    ('POM-129','Strap spacing at neckline',"Separació de tirants a l'escot",'Closure / Detail','STRAP SP NK',
     'Measure center-to-center distance between straps at the front neckline.',
     "Mesura centre a centre dels tirants a l'escot davanter.",
     'Strap center (left)','Strap center (right)','At front neckline',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','FRONT',
     False,0.5,0.25,True,True,False,True,'',''),
    ('POM-130','Strap spacing at back',"Separació de tirants a l'esquena",'Closure / Detail','STRAP SP BK',
     'Measure center-to-center distance between straps at the back.',
     "Mesura centre a centre dels tirants a l'esquena.",
     'Strap center (left)','Strap center (right)','At back',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BACK',
     False,0.5,0.25,True,True,False,True,'',''),

    # ─── JACKET / COAT ────────────────────────────────────────────────────────
    ('POM-100','Jacket length (HPS front)','Longitud de xaqueta (HPS)','Jacket / Coat','JK L HPS',
     'Measure from HPS straight down the center front to the bottom hem of the jacket, garment laid flat and buttoned.',
     'Mesura des de HPS fins al baix de la xaqueta, centre davanter, peça plana i abotonat.',
     'HPS (front)','Bottom hem','Center front, garment buttoned',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     True,1.5,1.0,True,False,False,True,'',''),
    ('POM-101','Lapel width','Ample de solapa','Jacket / Coat','LAP W',
     'Measure the width of the lapel at its widest point, perpendicular to the lapel roll line, garment laid flat.',
     "Mesura l'amplada de la solapa al seu punt més ample, perpendicular a la línia de doblec. Peça plana.",
     'Lapel roll line','Lapel outer edge','At widest point',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','FRONT',
     False,0.5,0.25,True,False,False,True,'',''),
    ('POM-102','Gorge line position','Posició de la talla de coll','Jacket / Coat','GORGE',
     'Measure from HPS to the gorge point (where collar meets lapel), along the shoulder seam and lapel edge.',
     "Mesura des de HPS fins al punt d'unió de coll i solapa, per la costura d'espatlla i la vora de la solapa.",
     'HPS','Gorge point (collar/lapel join)','Along shoulder and lapel',
     'FULL','DIAGONAL','FLAT','STRAIGHT','FRONT',
     False,0.5,0.25,True,False,False,True,'',''),
    ('POM-103','Chest pocket position','Posició de butxaca de pit','Jacket / Coat','CH PKT POS',
     'Measure from HPS to the top edge of the chest pocket, along the center front, garment laid flat.',
     'Mesura des de HPS fins a la vora superior de la butxaca de pit, per el centre davanter. Peça plana.',
     'HPS (front)','Chest pocket top edge','Center front',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     False,0.5,0.5,True,False,False,True,'',''),

    # ─── PLACEMENT ────────────────────────────────────────────────────────────
    ('POM-110','Label placement (CF distance)',"Posició d'etiqueta (distància CF)",'Placement','LBL CF',
     'Measure from center front neck seam to the nearest edge of the main label.',
     "Mesura des de la costura del coll al centre davanter fins a la vora més propera de l'etiqueta principal.",
     'CF neck seam','Nearest label edge','Along center front',
     'FULL','VERTICAL','FLAT','STRAIGHT','BACK',
     False,0.5,0.5,True,True,True,True,'',''),
    ('POM-111','Logo / print placement (from HPS)','Posició de logo (des de HPS)','Placement','LOGO HPS',
     'Measure from HPS straight down to the top edge of the logo or print, along the center front.',
     'Mesura des de HPS fins a la vora superior del logo o estampat, per el centre davanter.',
     'HPS (front)','Top edge of logo/print','Center front',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     False,0.5,0.5,True,True,True,True,'',''),
    ('POM-112','Pocket placement from waistband','Posició de butxaca des del cinturó','Placement','PKT WB',
     'Measure from the top edge of the waistband to the top edge of the side pocket opening.',
     "Mesura des de la vora superior del cinturó fins a la vora superior de l'obertura de la butxaca lateral.",
     'Waistband top edge','Pocket opening top','Along side seam',
     'FULL','VERTICAL','FLAT','STRAIGHT','SIDE',
     False,0.5,0.5,True,True,False,True,'',''),
    ('POM-113','Head circumference','Circumferència del cap','Placement','HC',
     'Measure girth around head at largest point, above ears and eyebrows.',
     'Perímetre del cap al punt més gran, per sobre de les orelles.',
     'Above ears','Above ears','Largest point',
     'FULL','CIRCUMFERENCE','ON_BODY','CURVED','HEAD',
     False,0.5,0.25,True,True,False,True,'Add: ISO §5.3.1. Hats, hoods, childrenswear head openings.','ISO 8559-1 §5.3.1'),

    # ─── ACCESSORIES ──────────────────────────────────────────────────────────
    ('POM-123','Belt length','Longitud de cinturó','Accessories','BELT L',
     'Measure the full length of the belt from tip to tip, including the tail, laid flat.',
     'Mesura la longitud total del cinturó de punta a punta, incloent la cua, pla.',
     'Belt tip (buckle end)','Belt tip (tail)','Along center of belt, fully extended',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,1.0,0.5,True,False,False,True,'Accessory belt. BELT group.',''),
    ('POM-124','Belt width','Amplada de cinturó','Accessories','BELT W',
     'Measure the width of the belt at its widest point, perpendicular to length, laid flat.',
     "Mesura l'amplada del cinturó al seu punt més ample, perpendicular a la longitud, pla.",
     'Belt edge (top)','Belt edge (bottom)','At widest point',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,0.25,0.25,True,False,False,True,'Accessory belt. BELT group.',''),
    ('POM-125','Belt hole spacing','Separació de forats de cinturó','Accessories','BELT HS',
     'Measure center-to-center distance between consecutive belt holes.',
     'Mesura la distància centre a centre entre forats consecutius del cinturó.',
     'Hole center (1st)','Hole center (2nd)','Between consecutive holes',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,0.25,0.25,True,False,False,True,'Accessory belt. Standard spacing typically 2.5 cm.',''),

    # ─── TECHNICAL / WORKWEAR ─────────────────────────────────────────────────
    ('POM-131','Thumbhole size',"Mida d'obertura de polze",'Technical / Workwear','THUMB',
     'Measure the diameter or width of the thumbhole opening at the sleeve hem.',
     "Mesura el diàmetre o amplada de l'obertura de polze al baix de la màniga.",
     'Thumbhole edge (left)','Thumbhole edge (right)','At widest point of opening',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','SLEEVE',
     False,0.25,0.25,True,True,False,True,'Sportswear/outerwear. Prevents sleeve ride-up.',''),
    ('POM-132','Ventilation opening length',"Longitud d'obertura de ventilació",'Technical / Workwear','VENT L',
     'Measure the full length of the ventilation opening or mesh panel from top to bottom.',
     'Mesura la longitud completa de l\'obertura de ventilació o panell de malla de dalt a baix.',
     'Ventilation top edge','Ventilation bottom edge','Along opening',
     'FULL','VERTICAL','FLAT','STRAIGHT','SIDE',
     False,0.5,0.5,True,True,False,True,'Sportswear/outerwear underarm or side vents.',''),
    ('POM-133','Kangaroo pocket width','Amplada de butxaca cangur','Technical / Workwear','KANG W',
     'Measure the total opening width of the kangaroo pocket, edge to edge, garment laid flat.',
     "Mesura l'amplada total de l'obertura de la butxaca cangur, de vora a vora, peça plana.",
     'Pocket opening edge (left)','Pocket opening edge (right)','Across full pocket opening',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','FRONT',
     False,0.5,0.5,False,True,False,True,'Hoodies, sweatshirts, sports tops.',''),
    ('POM-134','Hood visor length','Longitud de visera de caputxa','Technical / Workwear','VISOR L',
     'Measure the projection of the visor or peak from the hood face opening, at center.',
     "Mesura la projecció de la visera des de l'obertura de la caputxa, al centre.",
     'Hood face seam','Visor tip','At center',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','FRONT',
     False,0.5,0.25,True,True,False,True,'Outdoor/technical hoods with peak.',''),
    ('POM-135','Neck gaiter height','Alçada de coll tub','Technical / Workwear','GAITER H',
     'Measure the height of the integrated neck gaiter from the body seam to the top edge, relaxed.',
     "Mesura l'alçada del coll tub integrat des de la costura del cos fins a la vora superior, relaxat.",
     'Body/gaiter seam','Gaiter top edge','Center front',
     'FULL','VERTICAL','RELAXED','STRAIGHT','BOTH',
     False,0.5,0.5,True,True,False,True,'Technical outerwear with integrated neck tube.',''),
    ('POM-136','Reflective band width','Amplada de banda reflectant','Technical / Workwear','REFL W',
     'Measure the width of the reflective tape or band applied to the garment.',
     "Mesura l'amplada de la cinta o banda reflectant aplicada a la peça.",
     'Reflective band edge (top)','Reflective band edge (bottom)','Perpendicular to band length',
     'FULL','HORIZONTAL','FLAT','STRAIGHT','BOTH',
     False,0.25,0.25,True,True,False,True,'Workwear, sportswear, EN ISO 20471 hi-vis.',''),
    ('POM-137','Tool loop position',"Posició de passador d'eines",'Technical / Workwear','TOOL POS',
     'Measure from the waistband top to the center of the tool loop attachment point.',
     "Mesura des de la part superior del cinturó fins al centre del punt d'ancoratge del passador d'eines.",
     'Waistband top edge','Tool loop center','Along side seam',
     'FULL','VERTICAL','FLAT','STRAIGHT','SIDE',
     False,0.5,0.5,True,False,False,True,'Workwear trousers and shorts.',''),
    ('POM-138','Bib height','Alçada de peto','Technical / Workwear','BIB H',
     'Measure from the waistband top seam to the top edge of the bib panel, center front.',
     'Mesura des de la costura superior del cinturó fins a la vora superior del peto, centre davanter.',
     'Waistband top seam','Bib top edge','Center front',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     False,1.0,0.5,True,False,False,True,'Dungarees, workwear salopettes, bib overalls.',''),
    ('POM-139','Chest patch pocket position (CF)','Posició de butxaca pectoral (CF)','Technical / Workwear','CH PKT CF',
     'Measure from HPS to the top edge of the chest patch pocket, along center front.',
     'Mesura des de HPS fins a la vora superior de la butxaca pectoral, per el centre davanter.',
     'HPS (front)','Chest patch pocket top edge','Center front',
     'FULL','VERTICAL','FLAT','STRAIGHT','FRONT',
     False,0.5,0.5,True,True,False,True,'Workwear shirts, polo workwear, technical tops.',''),
]


class Command(BaseCommand):
    help = 'Substitueix completament el catàleg global de POMs (106 POMs v2, S12-A)'

    def add_arguments(self, parser):
        parser.add_argument(
            '--schema', default='public',
            help='Schema on aplicar el reseed (default: public). '
                 'Cal repetir per cada tenant si fhort.pom està a TENANT_APPS.'
        )

    def handle(self, *args, **opts):
        target_schema = opts['schema']
        assert len(POMS) == 106, f"Expected 106 POMs, got {len(POMS)}"
        assert len(CATEGORIES) == 15, f"Expected 15 categories, got {len(CATEGORIES)}"

        cat_codis = {c[0] for c in CATEGORIES}
        for row in POMS:
            if row[3] not in cat_codis:
                raise ValueError(f"POM {row[0]} referencia categoria inexistent: {row[3]!r}")

        with schema_context(target_schema):
            with transaction.atomic():
                self.stdout.write(self.style.WARNING(
                    f'Esborrant POMs existents al schema {target_schema}...'
                ))
                deleted, _ = POMGlobal.objects.all().delete()
                self.stdout.write(f'  {deleted} POMGlobal esborrats.')

                self.stdout.write('Creant/actualitzant 15 categories...')
                for codi, nom_en, nom_ca, order, desc in CATEGORIES:
                    POMCategory.objects.update_or_create(
                        codi=codi,
                        defaults={
                            'nom_en': nom_en,
                            'nom_ca': nom_ca,
                            'display_order': order,
                            'descripcio': desc,
                            'actiu': True,
                        }
                    )

                self.stdout.write('Creant 106 POMs...')
                objs = []
                for row in POMS:
                    (codi, nom_en, nom_ca, categoria, abbreviation,
                     desc_en, desc_ca, start_pt, end_pt, ref_pt,
                     scope, orientation, state, line, body_section,
                     is_key, tol_prod, tol_samp,
                     woven, knit, swim, actiu, notes, iso_ref) = row
                    objs.append(POMGlobal(
                        codi=codi,
                        nom_en=nom_en,
                        nom_ca=nom_ca,
                        nom_es='',
                        categoria=categoria,
                        descripcio_en=desc_en,
                        descripcio_ca=desc_ca,
                        unitat='cm',
                        actiu=actiu,
                        abbreviation=abbreviation,
                        start_point=start_pt,
                        end_point=end_pt,
                        reference_point=ref_pt,
                        scope=scope,
                        orientation=orientation,
                        state=state,
                        line=line,
                        body_section=body_section,
                        is_key=is_key,
                        tol_prod_cm=tol_prod,
                        tol_samp_cm=tol_samp,
                        applies_woven=woven,
                        applies_knit=knit,
                        applies_swim=swim,
                        notes=notes,
                        iso_ref=iso_ref,
                    ))
                POMGlobal.objects.bulk_create(objs)

            total = POMGlobal.objects.count()
            self.stdout.write(self.style.SUCCESS(
                f'\n✓ {total} POMs creats al schema {target_schema}\n'
            ))
            for codi, nom_en, *_ in CATEGORIES:
                n = POMGlobal.objects.filter(categoria=codi).count()
                self.stdout.write(f'  {nom_en:25} {n:3d} POMs')
