# Generated by Django 6.0.5 on 2026-07-09 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field', models.CharField(help_text="Nom del camp traduït (p.ex. 'name').", max_length=100)),
                ('language', models.CharField(help_text='Codi ISO 639-1 (ca, es, fr, de…).', max_length=5)),
                ('text', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='i18n_conten_content_1f6907_idx')],
                'unique_together': {('content_type', 'object_id', 'field', 'language')},
            },
        ),
    ]
