# Generated by Django 6.0.5 on 2026-06-01 14:56

import django.db.models.deletion
import fhort.planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_userprofile_jornada_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaris', models.JSONField(default=fhort.planning.models.default_horaris)),
                ('festius_extra', models.JSONField(blank=True, default=list)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company calendar',
                'verbose_name_plural': 'Company calendars',
            },
        ),
        migrations.CreateModel(
            name='Absencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField()),
                ('motiu', models.CharField(blank=True, default='', max_length=200)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absencies', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Absència',
                'verbose_name_plural': 'Absències',
                'ordering': ['-data_inici'],
            },
        ),
    ]
