# Generated by Django 6.0.5 on 2026-06-02 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_jornada_override'),
        ('models_app', '0024_model_predicted_end_model_predicted_start'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianQueueOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_orders', to='models_app.model')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_orders', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Ordre de cua per tècnic',
                'verbose_name_plural': 'Ordres de cua per tècnic',
                'ordering': ['profile_id', 'position'],
                'unique_together': {('profile', 'model')},
            },
        ),
    ]
