# Generated by Django 6.0.5 on 2026-05-25 12:11

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nom', models.CharField(max_length=200)),
                ('tipologia', models.CharField(choices=[('estudi', 'Estudi'), ('marca', 'Marca')], max_length=20)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('actiu', models.BooleanField(default=True)),
                ('data_alta', models.DateField(auto_now_add=True)),
                ('onboarding_complet', models.BooleanField(default=False)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('unitats', models.CharField(choices=[('cm', 'cm'), ('inch', 'inch')], default='cm', max_length=4)),
                ('idioma', models.CharField(default='ca', max_length=5)),
                ('codi_tenant', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Solo', 'Solo'), ('Studio', 'Studio'), ('Brand', 'Brand'), ('Enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('tipologia', models.CharField(choices=[('estudi', 'Estudi'), ('marca', 'Marca'), ('enterprise', 'Enterprise')], max_length=20)),
                ('preu_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_models_actius', models.IntegerField()),
                ('max_usuaris', models.IntegerField()),
                ('storage_gb', models.IntegerField()),
                ('ia_credits_mes', models.IntegerField()),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pla',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='tenants.plan'),
        ),
    ]
