# Generated by Django 6.0.5 on 2026-06-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adreca_fiscal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='data_baixa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='data_suspensio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email_facturacio',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='estat',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('actiu', 'Actiu'), ('suspes', 'Suspès'), ('baixa', 'Baixa')], default='onboarding', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='metode_pagament',
            field=models.CharField(blank=True, choices=[('stripe_card', 'Targeta (Stripe)'), ('sepa', 'SEPA')], max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='motiu_baixa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nif',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='pais',
            field=models.CharField(default='ES', max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='rao_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='models_inclosos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='moneda_pla',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='preu_model_extra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
