# Generated by Django 6.0.5 on 2026-06-05 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_client_estat_fiscal_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adreca_linia1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='adreca_linia2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='ciutat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='codi_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='estat_provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='gratis_fins',
            field=models.DateField(blank=True, help_text='Null=gratuïtat perpètua. Data=prova/promoció fins aquella data.', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nota_comercial',
            field=models.TextField(blank=True, help_text='Context comercial intern: motiu prova, acord especial, etc.'),
        ),
        migrations.AddField(
            model_name='client',
            name='regim_vat',
            field=models.CharField(blank=True, choices=[('espanyol', 'IVA Espanyol'), ('reverse_charge_ue', 'Reverse Charge UE'), ('oss_ue', 'OSS UE'), ('fora_ue', 'Fora UE')], max_length=30),
        ),
        migrations.AddField(
            model_name='client',
            name='tipus_client',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'B2C')], default='b2b', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_number',
            field=models.CharField(blank=True, help_text='NIF fiscal internacional (VAT/EIN/etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_validat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_validat_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TenantContacte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognom', models.CharField(blank=True, max_length=100)),
                ('carrec', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('principal', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactes', to='tenants.client')),
            ],
            options={
                'ordering': ['-principal', 'nom'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('client',), name='unic_contacte_principal_per_client')],
            },
        ),
    ]
