# Generated by Django 6.0.5 on 2026-07-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_client_adreca_vat_contactes_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_lookup_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_lookup_platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
