# Generated by Django 6.0.5 on 2026-07-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_plan_stripe_lookup_model_plan_stripe_lookup_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='nom',
            field=models.CharField(choices=[('Free', 'Free'), ('Solo', 'Solo'), ('Studio', 'Studio'), ('Brand', 'Brand'), ('Enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
    ]
