# Generated by Django 6.0.5 on 2026-07-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_plan_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodiAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_hash', models.CharField(max_length=64, unique=True)),
                ('mena', models.CharField(choices=[('seleccio', 'Selecció de workspace'), ('bescanvi', 'Bescanvi per sessió')], max_length=10)),
                ('tenant_schema', models.CharField(blank=True, max_length=63)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('candidats', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Codi d'autenticació",
                'verbose_name_plural': "Codis d'autenticació",
            },
        ),
    ]
