# Generated by Django 6.0.5 on 2026-07-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_codiauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_codi_tenant', models.CharField(max_length=3)),
                ('studio_codi_tenant', models.CharField(max_length=3)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('estat', models.CharField(choices=[('ACTIU', 'Actiu'), ('ATURAT', 'Aturat'), ('REVOCAT', 'Revocat')], default='ACTIU', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aturat_at', models.DateTimeField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Vincle de federació',
                'verbose_name_plural': 'Vincles de federació',
                'unique_together': {('brand_codi_tenant', 'studio_codi_tenant')},
            },
        ),
    ]
