# Generated by Django 6.0.5 on 2026-05-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentTypeGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=80, unique=True)),
                ('nom_en', models.CharField(max_length=200)),
                ('nom_ca', models.CharField(max_length=200)),
                ('nom_es', models.CharField(max_length=200)),
                ('grup', models.CharField(max_length=40)),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipus garment global',
                'verbose_name_plural': 'Tipus garment globals',
            },
        ),
        migrations.CreateModel(
            name='POMGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=80, unique=True)),
                ('nom_en', models.CharField(max_length=200)),
                ('nom_ca', models.CharField(max_length=200)),
                ('nom_es', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=40)),
                ('descripcio_en', models.TextField(blank=True)),
                ('unitat', models.CharField(choices=[('cm', 'cm'), ('inch', 'inch')], default='cm', max_length=4)),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'POM global',
                'verbose_name_plural': 'POMs globals',
            },
        ),
        migrations.CreateModel(
            name='SizeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=60, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('descripcio', models.TextField(blank=True)),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sistema de talles',
                'verbose_name_plural': 'Sistemes de talles',
            },
        ),
        migrations.CreateModel(
            name='TascaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=80, unique=True)),
                ('nom_en', models.CharField(max_length=200)),
                ('nom_ca', models.CharField(max_length=200)),
                ('nom_es', models.CharField(max_length=200)),
                ('fase', models.CharField(choices=[('Proto', 'Proto'), ('Fit', 'Fit'), ('SizeSet', 'SizeSet'), ('PP', 'PP'), ('TOP', 'TOP')], max_length=20)),
                ('tipus', models.CharField(choices=[('Interna', 'Interna'), ('Externa', 'Externa'), ('Validacio', 'Validació')], max_length=20)),
                ('minuts_estandard', models.PositiveIntegerField()),
                ('es_gate', models.BooleanField(default=False)),
                ('resultat_gate_opcions', models.JSONField(blank=True, default=list)),
                ('facturable', models.BooleanField(default=False)),
                ('ordre_base', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tasca global',
                'verbose_name_plural': 'Tasques globals',
                'ordering': ['ordre_base', 'codi'],
            },
        ),
        migrations.CreateModel(
            name='GarmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_client', models.CharField(max_length=60)),
                ('nom_client', models.CharField(max_length=120)),
                ('grup', models.CharField(max_length=40)),
                ('actiu', models.BooleanField(default=True)),
                ('garment_type_global', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_types', to='pom.garmenttypeglobal')),
            ],
            options={
                'verbose_name': 'Tipus garment (tenant)',
                'verbose_name_plural': 'Tipus garment (tenant)',
            },
        ),
        migrations.CreateModel(
            name='GradingRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('actiu', models.BooleanField(default=True)),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_rule_sets', to='pom.garmenttype')),
                ('size_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_rule_sets', to='pom.sizesystem')),
            ],
            options={
                'verbose_name': 'Joc de regles grading',
                'verbose_name_plural': 'Jocs de regles grading',
            },
        ),
        migrations.CreateModel(
            name='POMMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_client', models.CharField(max_length=30)),
                ('nom_client', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('actiu', models.BooleanField(default=True)),
                ('pom_global', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters', to='pom.pomglobal')),
            ],
            options={
                'verbose_name': 'POM (tenant)',
                'verbose_name_plural': 'POMs (tenant)',
            },
        ),
        migrations.CreateModel(
            name='SizeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=30)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('valor_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('size_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talles', to='pom.sizesystem')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Talles',
                'ordering': ['size_system', 'ordre'],
                'unique_together': {('size_system', 'etiqueta')},
            },
        ),
        migrations.CreateModel(
            name='POMEstadisticaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveIntegerField(default=0)),
                ('mitjana', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('m2', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('segment', models.CharField(max_length=20)),
                ('talla_label', models.CharField(max_length=30)),
                ('garment_type_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadistiques_globals', to='pom.garmenttypeglobal')),
                ('pom_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadistiques_globals', to='pom.pomglobal')),
            ],
            options={
                'verbose_name': 'Estadística POM global',
                'verbose_name_plural': 'Estadístiques POM globals',
                'unique_together': {('pom_global', 'garment_type_global', 'segment', 'talla_label')},
            },
        ),
        migrations.CreateModel(
            name='POMEstadisticaTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.CharField(max_length=80)),
                ('talla_label', models.CharField(max_length=30)),
                ('n', models.PositiveIntegerField(default=0)),
                ('mitjana', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('m2', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadistiques', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Estadística POM tenant',
                'verbose_name_plural': 'Estadístiques POM tenant',
                'unique_together': {('pom', 'garment_type', 'talla_label')},
            },
        ),
        migrations.CreateModel(
            name='GarmentPOMMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatori', models.BooleanField(default=False)),
                ('is_key', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pom_maps', to='pom.garmenttype')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garment_maps', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Mapa garment ↔ POM',
                'verbose_name_plural': 'Mapes garment ↔ POM',
                'ordering': ['garment_type', 'ordre'],
                'unique_together': {('garment_type', 'pom')},
            },
        ),
        migrations.CreateModel(
            name='GradingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logica', models.CharField(choices=[('LINEAR', 'Linear'), ('STEP', 'Step'), ('FIXED', 'Fixed'), ('ZERO', 'Zero'), ('EXCEPTION', 'Exception')], max_length=20)),
                ('valor_base', models.DecimalField(decimal_places=4, max_digits=10)),
                ('increment', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('valors_step', models.JSONField(blank=True, null=True)),
                ('actiu', models.BooleanField(default=True)),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='pom.gradingruleset')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regles_grading', to='pom.pommaster')),
                ('talla_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regles_base', to='pom.sizedefinition')),
            ],
            options={
                'verbose_name': 'Regla grading',
                'verbose_name_plural': 'Regles grading',
                'unique_together': {('rule_set', 'pom')},
            },
        ),
    ]
