# Generated by Django 6.0.5 on 2026-05-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=40, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('descripcio', models.TextField(blank=True)),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Família de garment',
                'verbose_name_plural': 'Famílies de garment',
                'ordering': ['codi'],
            },
        ),
        migrations.CreateModel(
            name='POMCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=20, unique=True)),
                ('nom_en', models.CharField(blank=True, max_length=120)),
                ('nom_ca', models.CharField(blank=True, max_length=120)),
                ('descripcio', models.TextField(blank=True)),
                ('body_area', models.CharField(blank=True, max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria POM',
                'verbose_name_plural': 'Categories POM',
                'ordering': ['display_order', 'codi'],
            },
        ),
        migrations.RemoveField(
            model_name='gradingruleset',
            name='garment_type',
        ),
        migrations.AddField(
            model_name='gradingruleset',
            name='garment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grading_rule_sets', to='pom.garmentgroup'),
        ),
        migrations.AddField(
            model_name='pommaster',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poms', to='pom.pomcategory'),
        ),
    ]
