# Generated by Django 6.0.5 on 2026-05-25 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0002_garmentgroup_pomcategory_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMesuraPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=20)),
                ('n_mostres', models.PositiveIntegerField(default=0)),
                ('mitjana', models.FloatField(default=0.0)),
                ('m2_acum', models.FloatField(default=0.0)),
                ('desviacio', models.FloatField(default=0.0)),
                ('darrera_actualitzacio', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_perfil', to='tenants.client')),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_perfil', to='pom.garmenttype')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesures_perfil', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Perfil mesures client',
                'verbose_name_plural': 'Perfils mesures client',
                'ordering': ['client', 'garment_type', 'pom', 'talla'],
                'unique_together': {('client', 'garment_type', 'pom', 'talla')},
            },
        ),
        migrations.CreateModel(
            name='GradingException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(max_length=20)),
                ('value_cm', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_exceptions', to='pom.pommaster')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='pom.gradingruleset')),
            ],
            options={
                'verbose_name': 'Excepció de grading',
                'verbose_name_plural': 'Excepcions de grading',
                'unique_together': {('rule_set', 'pom', 'size_label')},
            },
        ),
    ]
