# Generated by Django 6.0.5 on 2026-05-26 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0003_sprint3_4_grading_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurementISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_iso', models.CharField(blank=True, help_text='Referencia ISO 8559-1 — ex: 5.3.4', max_length=20)),
                ('codi_intern', models.CharField(help_text='Codi FHORT intern — ex: BUST_GIRTH', max_length=50, unique=True)),
                ('nom_en', models.CharField(help_text='Nom EN (idioma de treball)', max_length=200)),
                ('nom_cat', models.CharField(blank=True, max_length=200)),
                ('nom_es', models.CharField(blank=True, max_length=200)),
                ('categoria', models.CharField(choices=[('VERTICAL', 'Vertical measurements (§5.1)'), ('WIDTH_DEPTH', 'Widths and depths (§5.2)'), ('GIRTH', 'Girth / circumference (§5.3)'), ('SURFACE', 'Surface measurements (§5.4)'), ('HAND_FOOT', 'Hand and foot (§5.5)'), ('OTHER', 'Other (§5.6)'), ('CALCULATED', 'Calculated (§5.7)')], max_length=20)),
                ('htm_en', models.TextField(blank=True, help_text='How To Measure — instruccions completes EN')),
                ('figura_iso', models.CharField(blank=True, help_text='Figura de la norma — ex: Fig. 62', max_length=20)),
                ('es_primaria_iso', models.BooleanField(default=False, help_text='Es dimensio primaria per designacio de talla (ISO 8559-2)')),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categoria', 'codi_iso'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(choices=[('WOVEN', 'Woven (Pla)'), ('KNIT', 'Knit (Punt Jersey)'), ('STRETCH_KNIT', 'Stretch Knit (Punt Elastic)'), ('TECHNICAL', 'Technical')], max_length=20, unique=True)),
                ('nom_en', models.CharField(max_length=100)),
                ('nom_cat', models.CharField(blank=True, max_length=100)),
                ('nom_es', models.CharField(blank=True, max_length=100)),
                ('mesures_en_mitja', models.BooleanField(default=False, help_text='Knit specs typically use HALF measurements')),
                ('tolerancia_critica_cm', models.DecimalField(decimal_places=2, default=0.6, max_digits=4)),
                ('tolerancia_secundaria_cm', models.DecimalField(decimal_places=2, default=0.6, max_digits=4)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='FitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(choices=[('SLIM', 'Slim'), ('REGULAR', 'Regular'), ('RELAXED', 'Relaxed'), ('LOOSE', 'Loose'), ('OVERSIZED', 'Oversized')], max_length=20, unique=True)),
                ('nom_en', models.CharField(max_length=100)),
                ('nom_cat', models.CharField(blank=True, max_length=100)),
                ('nom_es', models.CharField(blank=True, max_length=100)),
                ('descripcio_en', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('ease_bust_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Ease estandar pit en cm', max_digits=5, null=True)),
                ('ease_waist_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ease_hip_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ease_thigh_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('client_definible', models.BooleanField(default=False, help_text='Si True, el client pot crear instancies propies')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(choices=[('WOMAN', 'Woman'), ('MAN', 'Man'), ('UNISEX_ADULT', 'Unisex Adult'), ('BABY_GIRL', 'Baby Girl'), ('BABY_BOY', 'Baby Boy'), ('BABY_UNISEX', 'Baby Unisex'), ('TODDLER_GIRL', 'Toddler Girl'), ('TODDLER_BOY', 'Toddler Boy'), ('GIRL', 'Girl'), ('BOY', 'Boy'), ('TEEN_GIRL', 'Teen Girl'), ('TEEN_BOY', 'Teen Boy'), ('MATERNITY', 'Maternity')], max_length=20, unique=True)),
                ('nom_en', models.CharField(max_length=100)),
                ('nom_cat', models.CharField(blank=True, max_length=100)),
                ('nom_es', models.CharField(blank=True, max_length=100)),
                ('age_min_months', models.IntegerField(blank=True, null=True)),
                ('age_max_months', models.IntegerField(blank=True, null=True)),
                ('primary_dimension', models.CharField(choices=[('BUST', 'Bust girth'), ('CHEST', 'Chest girth'), ('HEIGHT_CM', 'Height (cm)'), ('WAIST', 'Waist girth')], default='BUST', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='garmenttype',
            name='construccio_habitual',
            field=models.CharField(blank=True, help_text='Ex: WOVEN, KNIT, BOTH, STRETCH_KNIT', max_length=50),
        ),
        migrations.AddField(
            model_name='gradingruleset',
            name='codi_sistema',
            field=models.CharField(blank=True, help_text='Codi de referencia — ex: EU_WOVEN_WOMAN_REGULAR', max_length=50),
        ),
        migrations.AddField(
            model_name='gradingruleset',
            name='is_system_default',
            field=models.BooleanField(default=False, help_text='True = ve del seed data estandard ISO'),
        ),
        migrations.AddField(
            model_name='gradingruleset',
            name='parent_version',
            field=models.ForeignKey(blank=True, help_text='NULL = original estandard. Apunta al pare si es versio client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='pom.gradingruleset'),
        ),
        migrations.AddField(
            model_name='gradingruleset',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sizedefinition',
            name='age_months_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sizedefinition',
            name='age_months_min',
            field=models.IntegerField(blank=True, help_text='Mesos minim per a baby/kids sizes', null=True),
        ),
        migrations.AddField(
            model_name='sizedefinition',
            name='body_bust_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Perimetre pit (bust/chest) corporal', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sizedefinition',
            name='body_height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Alcada corporal de referencia (ISO 8559-1)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sizedefinition',
            name='body_hip_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sizedefinition',
            name='body_waist_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sizesystem',
            name='base_unit',
            field=models.CharField(blank=True, choices=[('ALPHA', 'Alpha (XS/S/M/L...)'), ('NUMERIC_EU', 'Numeric EU (34/36/38...)'), ('NUMERIC_US', 'Numeric US (0/2/4...)'), ('CM_HEIGHT', 'CM Height (50/56/62...)'), ('MONTHS', 'Months (0M/3M/6M...)'), ('AGE_YEARS', 'Age Years (6Y/8Y...)')], help_text='Tipus de designacio de talles', max_length=20),
        ),
        migrations.AddField(
            model_name='sizesystem',
            name='norma_ref',
            field=models.CharField(blank=True, help_text='Ex: ISO 8559-2, ASTM D5585', max_length=50),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='body_measure_iso',
            field=models.ForeignKey(blank=True, help_text='Mesura corporal ISO 8559-1 equivalent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poms_globals', to='pom.bodymeasurementiso'),
        ),
        migrations.AddField(
            model_name='gradingruleset',
            name='construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_rule_sets', to='pom.constructiontype'),
        ),
        migrations.AddField(
            model_name='gradingruleset',
            name='fit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_rule_sets', to='pom.fittype'),
        ),
        migrations.CreateModel(
            name='SizingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=True, help_text='El sistema suggereix aquest perfil per defecte')),
                ('version', models.IntegerField(default=1)),
                ('modified_by_id', models.IntegerField(blank=True, help_text="ID de l'usuari que ha modificat (cross-schema)", null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizing_profiles', to='pom.constructiontype')),
                ('fit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizing_profiles', to='pom.fittype')),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizing_profiles', to='pom.garmenttype')),
                ('grading_rule_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizing_profiles', to='pom.gradingruleset')),
                ('parent_profile', models.ForeignKey(blank=True, help_text='NULL = perfil estandard. Apunta al pare si es versio client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='pom.sizingprofile')),
                ('size_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizing_profiles', to='pom.sizesystem')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizing_profiles', to='pom.target')),
            ],
            options={
                'ordering': ['target__display_order', 'garment_type__nom_client'],
            },
        ),
        migrations.AddField(
            model_name='garmenttype',
            name='targets_recomanats',
            field=models.ManyToManyField(blank=True, related_name='garment_types', to='pom.target'),
        ),
        migrations.AddField(
            model_name='gradingruleset',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_rule_sets', to='pom.target'),
        ),
        migrations.AddField(
            model_name='sizesystem',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_systems', to='pom.target'),
        ),
    ]
