# Generated by Django 6.0.5 on 2026-05-26 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0004_sprint_s1_foundations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingruleset',
            name='size_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grading_rule_sets', to='pom.sizesystem'),
        ),
    ]
