# Generated by Django 6.0.5 on 2026-05-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0005_sprint_s1_grading_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingRuleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pom_codi', models.CharField(blank=True, help_text="Codi POM cached per si el POM s'elimina", max_length=20)),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_nou', models.DecimalField(decimal_places=2, max_digits=6)),
                ('logica_anterior', models.CharField(blank=True, max_length=20)),
                ('logica_nova', models.CharField(blank=True, max_length=20)),
                ('modificat_per_id', models.IntegerField(blank=True, help_text='ID usuari cross-schema', null=True)),
                ('modificat_per_nom', models.CharField(blank=True, max_length=200)),
                ('modificat_at', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(blank=True, max_length=500)),
                ('pom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_history', to='pom.pomglobal')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pom.gradingruleset')),
            ],
            options={
                'ordering': ['-modificat_at'],
            },
        ),
    ]
