# Generated by Django 6.0.5 on 2026-05-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0006_sprint_s4_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomglobal',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='applies_knit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='applies_swim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='applies_woven',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='body_section',
            field=models.CharField(blank=True, choices=[('FRONT', 'Front'), ('BACK', 'Back'), ('SIDE', 'Side'), ('SLEEVE', 'Sleeve'), ('BOTH', 'Both'), ('HEAD', 'Head')], max_length=20),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='descripcio_ca',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='end_point',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='is_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='iso_ref',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='line',
            field=models.CharField(blank=True, choices=[('STRAIGHT', 'Straight'), ('CURVED', 'Curved'), ('ALONG CURVE', 'Along curve'), ('ANGLED', 'Angled')], max_length=20),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='orientation',
            field=models.CharField(blank=True, choices=[('HORIZONTAL', 'Horizontal'), ('VERTICAL', 'Vertical'), ('CIRCUMFERENCE', 'Circumference'), ('CURVED', 'Curved'), ('DIAGONAL', 'Diagonal')], max_length=20),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='reference_point',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='scope',
            field=models.CharField(blank=True, choices=[('HALF', 'Half'), ('FULL', 'Full'), ('CALCULATED', 'Calculated')], max_length=20),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='start_point',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='state',
            field=models.CharField(blank=True, choices=[('FLAT', 'Flat'), ('RELAXED', 'Relaxed'), ('STRETCHED', 'Stretched'), ('ON_BODY', 'On body')], max_length=20),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='tol_prod_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='tol_samp_cm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pomglobal',
            name='nom_es',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
