# Generated by Django 6.0.5 on 2026-05-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0007_pomglobal_abbreviation_pomglobal_applies_knit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garmenttypeglobal',
            options={'ordering': ['grup', 'display_order', 'codi'], 'verbose_name': 'Tipus garment global', 'verbose_name_plural': 'Tipus garment globals'},
        ),
        migrations.AddField(
            model_name='garmenttype',
            name='is_system',
            field=models.BooleanField(default=False, help_text='True = ve del catàleg global canònic, no esborrable'),
        ),
        migrations.AddField(
            model_name='garmenttype',
            name='nom_ca',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='garmenttype',
            name='nom_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='garmenttype',
            name='nom_es',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='garmenttypeglobal',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='garmenttypeglobal',
            name='is_system',
            field=models.BooleanField(default=True, help_text='True = catàleg canònic, no esborrable'),
        ),
    ]
