# Generated by Django 6.0.5 on 2026-05-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0008_alter_garmenttypeglobal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingruleset',
            name='targets',
            field=models.ManyToManyField(blank=True, help_text='Un RuleSet pot aplicar a múltiples targets (ex: BABY_GIRL+BABY_BOY+BABY_UNISEX).', related_name='grading_rule_sets', to='pom.target', verbose_name='Targets aplicables'),
        ),
        migrations.AlterField(
            model_name='gradingrule',
            name='increment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='gradingrule',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gradingruleset',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_rule_sets_legacy', to='pom.target'),
        ),
    ]
