# Generated by Django 6.0.5 on 2026-05-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0009_gradingset_targets_m2m_decimal2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pommaster',
            name='origen_import',
            field=models.CharField(blank=True, default='', help_text="Referència del model/fitxa des d'on s'ha creat aquest POM", max_length=200, verbose_name='Origen importació'),
        ),
        migrations.AddField(
            model_name='pommaster',
            name='pendent_revisio',
            field=models.BooleanField(default=False, help_text="POM creat automàticament des d'importació. Requereix revisió de la patronista.", verbose_name='Pendent de revisió'),
        ),
    ]
