# Generated by Django 6.0.5 on 2026-05-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0010_pommaster_pendent_revisio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pommaster',
            name='tolerancia_default_minus',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=5),
        ),
        migrations.AddField(
            model_name='pommaster',
            name='tolerancia_default_plus',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=5),
        ),
    ]
