# Generated by Django 6.0.5 on 2026-05-30 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0011_pommaster_tolerancia_default_minus_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmesuraperfil',
            options={'ordering': ['codi_client', 'garment_type', 'pom', 'talla'], 'verbose_name': 'Perfil mesures client', 'verbose_name_plural': 'Perfils mesures client'},
        ),
        migrations.AlterUniqueTogether(
            name='clientmesuraperfil',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clientmesuraperfil',
            name='codi_client',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='clientmesuraperfil',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesures_perfil', to='tenants.client'),
        ),
        migrations.AlterUniqueTogether(
            name='clientmesuraperfil',
            unique_together={('codi_client', 'garment_type', 'pom', 'talla')},
        ),
    ]
