# Generated by Django 6.0.5 on 2026-06-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0012_alter_clientmesuraperfil_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmenttype',
            name='descripcio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='garmenttypeglobal',
            name='descripcio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
