# Generated by Django 6.0.5 on 2026-06-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0013_garmenttype_descripcio_garmenttypeglobal_descripcio'),
        ('tasks', '0017_gateevent_kind_alter_modeltask_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='garmentpommap',
            unique_together={('garment_type', 'pom')},
        ),
        migrations.AddField(
            model_name='garmentpommap',
            name='garment_type_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pom_maps', to='tasks.garmenttypeitem'),
        ),
        migrations.AlterField(
            model_name='garmentpommap',
            name='garment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pom_maps', to='pom.garmenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='garmentpommap',
            unique_together={('garment_type', 'pom'), ('garment_type_item', 'pom')},
        ),
    ]
