# Generated by Django 6.0.5 on 2026-06-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0014_alter_garmentpommap_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmentpommap',
            name='pendent_revisio',
            field=models.BooleanField(default=False),
        ),
    ]
