# Generated by Django 6.0.5 on 2026-06-03 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0015_garmentpommap_pendent_revisio'),
        ('tasks', '0017_gateevent_kind_alter_modeltask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garmentpommap',
            options={'ordering': ['garment_type_item', 'ordre'], 'verbose_name': 'Mapa garment ↔ POM', 'verbose_name_plural': 'Mapes garment ↔ POM'},
        ),
        migrations.AlterUniqueTogether(
            name='garmentpommap',
            unique_together={('garment_type_item', 'pom')},
        ),
        migrations.RemoveField(
            model_name='garmentpommap',
            name='garment_type',
        ),
    ]
