# Generated by Django 6.0.5 on 2026-06-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0016_alter_garmentpommap_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmentpommap',
            name='nivell',
            field=models.CharField(blank=True, choices=[('K', 'Key'), ('M', 'Mandatory'), ('O', 'Optional'), ('D', 'Detail-dependent')], default='O', max_length=1),
        ),
    ]
