# Generated by Django 6.0.5 on 2026-06-11 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0017_garmentpommap_nivell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizesystem',
            name='customer_codi',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Codi client'),
        ),
        migrations.AddField(
            model_name='sizesystem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_systems', to='pom.sizesystem', verbose_name='Sistema pare'),
        ),
    ]
