# Generated by Django 6.0.5 on 2026-06-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0018_size_system_parent_customer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sizingprofile',
            unique_together={('size_system', 'target', 'construction', 'fit_type')},
        ),
    ]
