# Generated by Django 6.0.5 on 2026-06-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0019_alter_sizingprofile_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sizingprofile',
            unique_together=set(),
        ),
    ]
