# Generated by Django 6.0.5 on 2026-06-15 07:19
# 0a: migració mecànica SizeSystem.target (FK) → SizeSystem.targets (M2M).
# Ordre: AddField(targets) → RunPython(copia target→targets) → RemoveField(target).
# La data migration s'executa per esquema (pom és TENANT_APP): migrate_schemas la
# corre a cada tenant, copiant els lligams propis de cada esquema.

from django.db import migrations, models


def copy_target_to_targets(apps, schema_editor):
    """Per cada SizeSystem amb FK target no NULL, replica el lligam a la M2M targets."""
    SizeSystem = apps.get_model('pom', 'SizeSystem')
    for ss in SizeSystem.objects.filter(target__isnull=False):
        ss.targets.add(ss.target_id)


def copy_targets_to_target(apps, schema_editor):
    """Reverse: el primer target de la M2M torna a la FK (RemoveField.reverse ja l'ha recreat)."""
    SizeSystem = apps.get_model('pom', 'SizeSystem')
    for ss in SizeSystem.objects.all():
        first = ss.targets.first()
        if first is not None:
            ss.target = first
            ss.save(update_fields=['target'])


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0020_alter_sizingprofile_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizesystem',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='size_systems', to='pom.target'),
        ),
        migrations.RunPython(copy_target_to_targets, copy_targets_to_target),
        migrations.RemoveField(
            model_name='sizesystem',
            name='target',
        ),
    ]
