# Generated by Django 6.0.5 on 2026-06-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0021_remove_sizesystem_target_sizesystem_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingrule',
            name='increment_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='gradingrule',
            name='increment_break',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='gradingrule',
            name='talla_break_label',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='gradingrule',
            name='talla_break_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
