# Generated by Django 6.0.5 on 2026-06-17 06:07

from django.db import migrations


def complete_pom91_size_system(apps, schema_editor):
    """Completa el forat de seed: assigna size_system=NUMERIC_EU_W al canònic
    EU_WOVEN_WOMAN_NUMERIC, que és l'únic is_system_default amb size_system NULL.

    Defensiva i idempotent (es resol per CODI, mai per pk — varien per tenant):
      - Només actua si el ruleset existeix I size_system és NULL (no sobreescriu).
      - Si NUMERIC_EU_W no existeix al tenant → skip silenciós (no peta).
      - Si >1 ruleset matxeja → log i no actua (evita ambigüitat).
    NO altera cap regla de grading; només completa metadada de classificació.
    """
    GradingRuleSet = apps.get_model('pom', 'GradingRuleSet')
    SizeSystem = apps.get_model('pom', 'SizeSystem')

    qs = GradingRuleSet.objects.filter(
        codi_sistema='EU_WOVEN_WOMAN_NUMERIC',
        size_system__isnull=True,
    )
    n = qs.count()
    if n == 0:
        # Cap ruleset pendent (no existeix o ja té size_system) → res a fer.
        return
    if n > 1:
        print(f"  [pom 0023] SKIP: {n} rulesets 'EU_WOVEN_WOMAN_NUMERIC' amb "
              f"size_system NULL — ambigu, no s'actua.")
        return

    numeric_eu_w = SizeSystem.objects.filter(
        codi='NUMERIC_EU_W', customer_codi='',
    ).first()
    if numeric_eu_w is None:
        # Tenant sense aquest SizeSystem canònic → no trenquem la migració.
        print("  [pom 0023] SKIP: SizeSystem 'NUMERIC_EU_W' (canònic) no existeix "
              "al tenant.")
        return

    rs = qs.first()
    rs.size_system = numeric_eu_w
    rs.save(update_fields=['size_system'])
    print(f"  [pom 0023] OK: ruleset '{rs.codi_sistema}' (pk={rs.pk}) → "
          f"size_system='NUMERIC_EU_W' (pk={numeric_eu_w.pk}).")


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0022_gradingrule_increment_base_and_more'),
    ]

    operations = [
        migrations.RunPython(complete_pom91_size_system, migrations.RunPython.noop),
    ]
