# Generated by Django 6.0.5 on 2026-06-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0023_complete_pom91_numeric_size_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingrule',
            name='valor_base',
        ),
    ]
