# Generated by Django 6.0.5 on 2026-06-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0024_remove_gradingrule_valor_base'),
        ('tasks', '0022_garmenttypeitem_base_size_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBaseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tol_minus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tol_plus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('garment_type_item', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='base_measurements', to='tasks.garmenttypeitem')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_base_measurements', to='pom.pommaster')),
            ],
            options={
                'verbose_name': "Mesura base d'item",
                'verbose_name_plural': "Mesures base d'item",
                'ordering': ['garment_type_item', 'pom'],
                'unique_together': {('garment_type_item', 'pom')},
            },
        ),
    ]
