# Generated by Django 6.0.5 on 2026-06-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0025_itembasemeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembasemeasurement',
            name='nom_fitxa',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
