# Generated by Django 6.0.5 on 2026-07-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0026_itembasemeasurement_nom_fitxa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TascaGlobal',
        ),
    ]
