# Generated by Django 6.0.5 on 2026-07-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0027_delete_tascaglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingruleset',
            name='pendents_vincular',
            field=models.JSONField(blank=True, default=list, help_text='Codis de document no vinculats a cap POM en crear el run (pendents de vincular).'),
        ),
    ]
