# Generated by Django 6.0.5 on 2026-07-08 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0028_gradingruleset_pendents_vincular'),
        ('tasks', '0034_supplier_adreca_linia1_supplier_adreca_linia2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingruleset',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_rule_sets', to='tasks.customer'),
        ),
        migrations.CreateModel(
            name='CustomerPOMAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=60)),
                ('client_description', models.CharField(blank=True, default='', max_length=200)),
                ('origen', models.CharField(choices=[('IMPORT', 'Import'), ('MANUAL', 'Manual'), ('MIGRACIO', 'Migració')], default='MANUAL', max_length=10)),
                ('pendent_revisio', models.BooleanField(default=False)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='pom_aliases', to='tasks.customer')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_aliases', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Àlies POM de client',
                'verbose_name_plural': 'Àlies POM de client',
                'indexes': [models.Index(fields=['customer', 'client_code'], name='idx_customer_client_code')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'client_code'), name='uniq_customer_client_code')],
            },
        ),
    ]
