# Generated by Django 6.0.5 on 2026-07-08 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0032_migrate_dotted_codi_client_to_aliases'),
        ('tasks', '0037_modeltask_off_recipe_modeltask_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizingprofile',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizing_profiles', to='tasks.customer'),
        ),
    ]
