# Generated by Django 6.0.5 on 2026-07-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0035_customerpomalias_dictionary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingruleset',
            name='origen',
            field=models.CharField(blank=True, choices=[('CANONICAL', 'Canònic FHORT'), ('CLIENT_RUN', 'Derivat de run de client'), ('IMPORT', 'Importat')], help_text='Procedència. NULL = no classificat (anterior a la llei PROVINENÇA).', max_length=12, null=True),
        ),
    ]
