# Generated by Django 6.0.5 on 2026-07-13 16:14
#
# G6/1a — DROP de `pom_gradingexception` (DIAGNOSI_G6_DUAL_PATH §B2.1).
#
# AUDITORIA EN FRED, feta ABANS d'escriure aquesta migració (i que és la condició per poder-la
# escriure; si hi hagués aparegut una sola fila o un sol escriptor, l'sprint s'aturava):
#
#   · files a `fhort.pom_gradingexception`   → 0
#   · files a `public.pom_gradingexception`  → 0   (POMMaster viu als dos schemes; s'han mirat els dos)
#   · escriptors a l'aplicació               → CAP. No hi ha viewset, ni serializer, ni URL, ni cap
#                                               hit als dos frontends. Només seeds/importadors legacy,
#                                               tots retirats en aquest mateix commit.
#   · lectors                                → només `_load_grading_exceptions` (motor), retirat.
#   · relacions inverses (`GradingRuleSet.exceptions`, `POMMaster.grading_exceptions`)
#                                            → declarades i MAI usades enlloc.
#
# La substitució ja estava feta i escrita: `models_app.ModelGradingOverride` (acotat a UN model)
# va néixer explícitament per rellevar aquesta (penjada de la plantilla COMPARTIDA, que filtrava
# a tots els models del set). El que aquesta migració enterra és el cadàver, no el mecanisme.
#
# Reversible: el reverse de DeleteModel és CreateModel (Django el reconstrueix de l'estat). Recrearia
# la taula BUIDA — que és exactament el que hi havia.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0037_alter_customerpomalias_pom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradingException',
        ),
    ]
