# Generated by Django 6.0.5 on 2026-07-16 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0038_delete_gradingexception'),
        ('tasks', '0038_modeltask_fitting_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingruleset',
            name='garment_type_item',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Node fi de la identitat del contenidor de client (llei CONTENIDOR). NULL = canònic/no-client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_rule_sets', to='tasks.garmenttypeitem'),
        ),
        migrations.AddConstraint(
            model_name='gradingruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('origen', 'CLIENT_RUN')), fields=('customer', 'size_system', 'garment_type_item', 'fit_type'), name='uniq_client_container_identity'),
        ),
    ]
