# Generated by Django 6.0.5 on 2026-07-17 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0039_gradingruleset_garment_type_item_and_more'),
        ('tasks', '0038_modeltask_fitting_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSetScopeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('GROUP', 'Grup'), ('TYPE', 'Família'), ('ITEM', 'Item')], max_length=6)),
                ('garment_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope_nodes', to='pom.garmentgroup')),
                ('garment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope_nodes', to='pom.garmenttype')),
                ('garment_type_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope_nodes', to='tasks.garmenttypeitem')),
                ('rule_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_nodes', to='pom.gradingruleset')),
            ],
            options={
                'verbose_name': "Node d'àmbit de grading",
                'verbose_name_plural': "Nodes d'àmbit de grading",
                'constraints': [models.UniqueConstraint(condition=models.Q(('node_type', 'GROUP')), fields=('rule_set', 'garment_group'), name='uniq_scope_group'), models.UniqueConstraint(condition=models.Q(('node_type', 'TYPE')), fields=('rule_set', 'garment_type'), name='uniq_scope_type'), models.UniqueConstraint(condition=models.Q(('node_type', 'ITEM')), fields=('rule_set', 'garment_type_item'), name='uniq_scope_item')],
            },
        ),
    ]
