# Generated by Django 6.0.5 on 2026-07-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0040_rulesetscopenode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garmenttype',
            name='targets_recomanats',
        ),
    ]
