# Generated by Django 6.0.5 on 2026-07-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0044_p9_itembasemeasurement_provinenca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizingprofile',
            name='grading_rule_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sizing_profiles', to='pom.gradingruleset'),
        ),
    ]
