# Generated by Django 6.0.5 on 2026-07-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0045_sizingprofile_grading_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='codi',
            field=models.CharField(choices=[('WOMAN', 'Woman'), ('MAN', 'Man'), ('UNISEX_ADULT', 'Unisex Adult'), ('NEWBORN_GIRL', 'Newborn Girl'), ('NEWBORN_BOY', 'Newborn Boy'), ('NEWBORN_UNISEX', 'Newborn Unisex'), ('BABY_GIRL', 'Baby Girl'), ('BABY_BOY', 'Baby Boy'), ('KID_GIRL', 'Kid Girl'), ('KID_BOY', 'Kid Boy'), ('TEEN_GIRL', 'Teen Girl'), ('TEEN_BOY', 'Teen Boy'), ('MATERNITY', 'Maternity')], max_length=20, unique=True),
        ),
    ]
