# Generated by Django 6.0.5 on 2026-07-24 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0046_alter_target_codi'),
        ('tasks', '0039_backfill_codi_global_self'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBaseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('PROMOCIO', "Promogut des d'un model"), ('MASTER', 'Màster de catàleg'), ('MANUAL', 'Creat manualment')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('base_size_definition', models.ForeignKey(help_text="Talla base del set (on s'expressen els valors).", on_delete=django.db.models.deletion.PROTECT, related_name='base_set_for_items', to='pom.sizedefinition')),
                ('fit_type', models.ForeignKey(blank=True, help_text='Buit = Regular (convenció de lookup).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_base_sets', to='pom.fittype')),
                ('garment_type_item', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='base_sets', to='tasks.garmenttypeitem')),
                ('size_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_base_sets', to='pom.sizesystem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_base_sets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Set de mesures base d'item",
                'verbose_name_plural': "Sets de mesures base d'item",
                'ordering': ['garment_type_item', 'size_system', 'fit_type'],
            },
        ),
        migrations.AddField(
            model_name='itembasemeasurement',
            name='base_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='pom.itembaseset'),
        ),
        migrations.AddConstraint(
            model_name='itembaseset',
            constraint=models.UniqueConstraint(fields=('garment_type_item', 'size_system', 'fit_type'), name='uniq_itembaseset_item_system_fit'),
        ),
        migrations.AddConstraint(
            model_name='itembaseset',
            constraint=models.UniqueConstraint(condition=models.Q(('fit_type__isnull', True)), fields=('garment_type_item', 'size_system'), name='uniq_itembaseset_item_system_nofit'),
        ),
    ]
