# Generated by Django 6.0.5 on 2026-07-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0049_itembasemeasurement_base_set_notnull'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itembasemeasurement',
            unique_together={('base_set', 'pom')},
        ),
    ]
