# Generated by Django 6.0.5 on 2026-07-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0050_itembasemeasurement_key_base_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternPieceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('nom_en', models.CharField(max_length=120)),
                ('nom_ca', models.CharField(max_length=120)),
                ('nom_es', models.CharField(max_length=120)),
                ('classe', models.CharField(choices=[('cos', 'Cos'), ('maniga', 'Màniga'), ('banda', 'Banda'), ('tira', 'Tira'), ('panell', 'Panell'), ('complement', 'Complement')], max_length=12)),
                ('is_system', models.BooleanField(default=False)),
                ('pendent_revisio', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('SEED', 'Sembra'), ('MANUAL', 'Manual'), ('IMPORT', 'Importació')], default='MANUAL', max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rol de peça de patró',
                'verbose_name_plural': 'Rols de peça de patró',
                'ordering': ['display_order', 'slug'],
            },
        ),
    ]
