# Generated by Django 6.0.5 on 2026-08-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0057_c4_g4_retira_comportes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('nom_en', models.CharField(max_length=120)),
                ('nom_ca', models.CharField(max_length=120)),
                ('nom_es', models.CharField(max_length=120)),
                ('eix', models.CharField(choices=[('POSICIO', 'Posició'), ('ESTAT', 'Estat')], db_index=True, max_length=8)),
                ('sufix', models.CharField(blank=True, default='', max_length=4)),
                ('is_system', models.BooleanField(default=False)),
                ('pendent_revisio', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('SEED', 'Sembra'), ('MANUAL', 'Manual'), ('IMPORT', 'Importació')], default='MANUAL', max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Instància de mesura',
                'verbose_name_plural': 'Instàncies de mesura',
                'ordering': ['eix', 'display_order', 'slug'],
            },
        ),
    ]
