# Generated by Django 6.0.5 on 2026-08-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0058_diccionari_instancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpomalias',
            name='es_instancia',
            field=models.BooleanField(default=False, help_text='Aquest codi és una REPETICIÓ del POM apuntat, no una mesura pròpia. El matcher hi resol el POM però deixa la fila a «assignar instància».'),
        ),
    ]
