# Generated by Django 6.0.5 on 2026-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0060_extended_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpomalias',
            name='origen',
            field=models.CharField(choices=[('IMPORT', 'Import'), ('MANUAL', 'Manual'), ('MIGRACIO', 'Migració'), ('DICCIONARI', 'Diccionari'), ('MODEL', "Nascut d'un model")], default='MANUAL', max_length=10),
        ),
    ]
