# Generated by Django 6.0.5 on 2026-08-06 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0061_alter_customerpomalias_origen'),
        ('tasks', '0048_tasktype_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizesystem',
            name='construccions',
            field=models.ManyToManyField(blank=True, related_name='size_systems', to='pom.constructiontype', verbose_name='Construccions'),
        ),
        migrations.AddField(
            model_name='sizesystem',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_systems', to='tasks.customer', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='sizesystem',
            name='fits',
            field=models.ManyToManyField(blank=True, related_name='size_systems', to='pom.fittype', verbose_name='Fits'),
        ),
        migrations.AddField(
            model_name='sizesystem',
            name='grups',
            field=models.ManyToManyField(blank=True, related_name='size_systems', to='pom.garmentgroup', verbose_name='Grups de peça'),
        ),
        migrations.AddField(
            model_name='sizesystem',
            name='tipus_escala',
            field=models.CharField(blank=True, choices=[('ALPHA', 'Alpha (XS/S/M/L…)'), ('NUM', 'Numèrica (34/36/38…)'), ('MESOS', 'Mesos i edat (0M/3M · 2/4/6 anys)'), ('ALTURA', 'Alçada en cm (50/56/62…)')], default='', help_text='Deduït de les etiquetes de talla. Buit = no deduïble sol.', max_length=10, verbose_name="Tipus d'escala"),
        ),
    ]
