# Generated by Django 6.0.5 on 2026-08-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0072_cat22_sembra_garmentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentGroupPOMMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatori', models.BooleanField(default=False)),
                ('is_key', models.BooleanField(default=False)),
                ('nivell', models.CharField(blank=True, choices=[('K', 'Key'), ('M', 'Mandatory'), ('O', 'Optional'), ('D', 'Detail-dependent')], default='O', max_length=1)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('pendent_revisio', models.BooleanField(default=False)),
                ('capa', models.CharField(db_index=True, default='exterior', help_text='Capa de mesura: slug de pom.MeasurementLayer (per SLUG, mai per PK).', max_length=20)),
                ('instancia', models.CharField(db_index=True, default='', help_text="Instància del POM dins la capa: slug compost canònic. '' és la instància única.", max_length=60)),
                ('garment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pom_maps', to='pom.garmentgroup')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garment_group_maps', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Mapa grup ↔ POM',
                'verbose_name_plural': 'Mapes grup ↔ POM',
                'ordering': ['garment_group', 'ordre'],
                'unique_together': {('garment_group', 'pom', 'capa', 'instancia')},
            },
        ),
        migrations.CreateModel(
            name='GarmentTypePOMMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatori', models.BooleanField(default=False)),
                ('is_key', models.BooleanField(default=False)),
                ('nivell', models.CharField(blank=True, choices=[('K', 'Key'), ('M', 'Mandatory'), ('O', 'Optional'), ('D', 'Detail-dependent')], default='O', max_length=1)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('pendent_revisio', models.BooleanField(default=False)),
                ('capa', models.CharField(db_index=True, default='exterior', help_text='Capa de mesura: slug de pom.MeasurementLayer (per SLUG, mai per PK).', max_length=20)),
                ('instancia', models.CharField(db_index=True, default='', help_text="Instància del POM dins la capa: slug compost canònic. '' és la instància única.", max_length=60)),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pom_maps', to='pom.garmenttype')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garment_type_maps', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Mapa família ↔ POM',
                'verbose_name_plural': 'Mapes família ↔ POM',
                'ordering': ['garment_type', 'ordre'],
                'unique_together': {('garment_type', 'pom', 'capa', 'instancia')},
            },
        ),
    ]
