# Generated by Django 6.0.5 on 2026-08-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0073_u2_acumulacio_poms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fittype',
            name='codi',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('SLIM', 'Slim / Fitted'), ('RELAXED', 'Relaxed'), ('OVERSIZED', 'Oversized'), ('FLARED', 'Flared'), ('TAPERED', 'Tapered'), ('STRAIGHT', 'Straight'), ('BODYCON', 'Bodycon'), ('ATHLETIC', 'Athletic / Performance'), ('CUSTOM', 'Custom (client)')], max_length=20, unique=True),
        ),
    ]
