# Generated by Django 6.0.5 on 2026-08-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0075_pommaster_codi_client_unic_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ref', models.CharField(help_text="Referència estable de l'objecte traduït (p.ex. 'pom:142').", max_length=120)),
                ('lang', models.CharField(help_text='Codi ISO 639-1 en minúscules (ca, es, fr…).', max_length=5)),
                ('text', models.TextField(blank=True, help_text='La traducció.')),
                ('source_text', models.TextField(blank=True, help_text='Text original (EN) del qual surt la traducció; si canvia, la fila es refresca.')),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Traducció memoritzada',
                'verbose_name_plural': 'Traduccions memoritzades',
                'constraints': [models.UniqueConstraint(fields=('source_ref', 'lang'), name='uniq_translationcache_ref_lang')],
            },
        ),
    ]
