"""PRE-TREN DE LA SEMBRA v5 — les quatre columnes del catàleg que no tenien on anar (23/08).

**ADDITIVA I DE L'ESPÈCIE 0078**: quatre columnes noves a `pom_pomglobal`, **totes amb el
default buit**. Cap fila canvia de valor, cap lector canvia de resposta i cap `POMMaster` es
toca; fins que la sembra (S2) les ompli, el sistema es comporta exactament com abans.

D'on surten: el full `CATALEG_SISTEMA_POM_v5_COMPLET_r2.xlsx` porta `Pos.`, `Règim`,
`Ancoratge` i `Capa` per als 165 POMs, i fins avui es reportaven i es perdien — la sembra v4
ja ho va deixar escrit el 09/08 («tres columnes del corpus no tenen destí a l'esquema… no
s'han inventat camps ni s'han abocat a `notes`»). Pre-tren autoritzat per Agus el 23/08.

  · `display_order`  — l'ordre del POM DINS de la família. 0 = el full no ho diu.
  · `regim`          — Amplada · Llarg · Col·locació · Fix
  · `ancoratge`      — Cota · Caiguda · Component · Tirada
  · `capa_defecte`   — 🔑 i NO `capa`: la capa és de la PERTINENÇA (`GarmentPOMMap.capa`) i el
                       catàleg no la pot decidir, només la PROPOSA.

Els valors són **els literals del full** i les `choices` només els declaren: traduir-los a
codis seria una taula de conversió més per mantenir, i el que han de llegir igual els dos
entorns són els mateixos bytes del mateix arxiu.

`pom` és SHARED i TENANT alhora (`settings.py:55,68`): `migrate_schemas` (MAI `--schema`) la
posa a `public` i a cada tenant. **Reversible**: el revers treu les quatre columnes i no toca
cap altra dada.
"""
# Generated by Django 6.0.5 on 2026-08-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0080_posicions_front_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomglobal',
            name='ancoratge',
            field=models.CharField(blank=True, choices=[('Cota', 'Cota'), ('Caiguda', 'Caiguda'), ('Component', 'Component'), ('Tirada', 'Tirada')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='capa_defecte',
            field=models.CharField(blank=True, default='', help_text='Capa que el catàleg PROPOSA (slug de pom.MeasurementLayer). Buit = cap proposta; la capa real la decideix la pertinença.', max_length=20),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pomglobal',
            name='regim',
            field=models.CharField(blank=True, choices=[('Amplada', 'Amplada'), ('Llarg', 'Llarg'), ('Col·locació', 'Col·locació'), ('Fix', 'Fix')], default='', max_length=20),
        ),
    ]
