"""EL NOM BUIT MANA EL CANÒNIC — validació, no esquema (23/08).

`sqlmigrate` la resol en **no-op**: `blank` és validació de Django i la columna ja era NOT NULL
amb cadena buida. El que canvia és el SIGNIFICAT: fins avui un `POMMaster` havia de tenir nom
propi, i `nomenclatura.noms_de` el feia guanyar sempre; per això un POM lligat al catàleg del
sistema seguia ensenyant el nom vell —i només en anglès— encara que el global portés el
canònic i les traduccions.

Amb el nom buit, la cascada cau al `POMGlobal` i la fitxa ensenya EN, CA i ES del catàleg. És
la decisió d'Agus del 23/08: **el nom del tenant que duplica o divergeix del canònic deixa de
manar**. Qui l'aplica és `adopta_nom_del_canonic`, que demana flag explícit i guarda de
recompte (llei dels panys).
"""
# Generated by Django 6.0.5 on 2026-08-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0081_sembra_v5_cataleg_pomglobal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pommaster',
            name='nom_client',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
