"""LA MARCA D'EDICIÓ D'UN ÀLIES — additiva i nul·la (23/08).

Una columna nova a `pom_customerpomalias`, `NULL` a totes les files: cap àlies existent canvia
de res i cap lector canvia de resposta. L'estampa **només** l'edició des de la biblioteca de
nomenclatura.

Per què no `actualitzat_at`: és `auto_now` i el mou qualsevol desa —una sembra, una migració de
dades—, o sigui que no distingeix «algú ho ha corregit» de «una comanda hi ha passat per sobre».

🔑 I l'`origen` NO es toca: un àlies nascut d'un IMPORT que després algú corregeix segueix sent
d'IMPORT. L'origen diu D'ON VE; la marca d'edició diu que algú l'ha tocat després. Són dues
preguntes i volen dues columnes.
"""
# Generated by Django 6.0.5 on 2026-08-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0082_nom_client_buit_mana_el_canonic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpomalias',
            name='editat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Editat el'),
        ),
    ]
