# Generated by Django 6.0.5 on 2026-08-26 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0083_alies_marca_edicio'),
        ('tasks', '0053_ronda_fora_de_comanda_ronda_linia_comanda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system', models.BooleanField(default=False)),
                ('pendent_revisio', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('SEED', 'Sembra'), ('MANUAL', 'Manual'), ('IMPORT', 'Importació')], default='MANUAL', max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('source_ref', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('nom_en', models.CharField(max_length=120)),
                ('nom_ca', models.CharField(max_length=120)),
                ('nom_es', models.CharField(max_length=120)),
                ('zone', models.CharField(choices=[('neck', 'Coll'), ('shoulder', 'Espatlla'), ('arm', 'Braç'), ('torso', 'Tors'), ('waist', 'Cintura'), ('leg', 'Cama'), ('any', 'Qualsevol')], max_length=12)),
                ('kind', models.CharField(choices=[('opening', 'Obertura'), ('seam', 'Costura'), ('finished', 'Vora acabada'), ('internal', 'Interna'), ('structural', 'Estructural')], max_length=12)),
                ('mates_slug', models.CharField(blank=True, default='', max_length=60)),
                ('needs_piece_role', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rol de vora',
                'verbose_name_plural': 'Rols de vora',
                'ordering': ['display_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='GCPieceRoleMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_role', models.CharField(max_length=60, unique=True)),
                ('ftt_slug', models.CharField(max_length=60)),
                ('face', models.CharField(blank=True, choices=[('', 'Sense cara'), ('front', 'Davant'), ('back', 'Darrere')], default='', max_length=6)),
                ('nota', models.TextField(blank=True, default='')),
                ('source_ref', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Mapa de rol de peça GarmentCode→FTT',
                'verbose_name_plural': 'Mapa de rols de peça GarmentCode→FTT',
                'ordering': ['gc_role'],
            },
        ),
        migrations.CreateModel(
            name='LandmarkRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system', models.BooleanField(default=False)),
                ('pendent_revisio', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('SEED', 'Sembra'), ('MANUAL', 'Manual'), ('IMPORT', 'Importació')], default='MANUAL', max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('source_ref', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('nom_en', models.CharField(max_length=120)),
                ('nom_ca', models.CharField(max_length=120)),
                ('nom_es', models.CharField(max_length=120)),
                ('zone', models.CharField(choices=[('neck', 'Coll'), ('shoulder', 'Espatlla'), ('arm', 'Braç'), ('torso', 'Tors'), ('waist', 'Cintura'), ('leg', 'Cama'), ('any', 'Qualsevol')], max_length=12)),
                ('derivable', models.BooleanField(default=False)),
                ('derivation_op', models.CharField(choices=[('shared_endpoint', 'Extrem compartit per dues vores'), ('far_endpoint', "Extrem llunyà d'una vora"), ('extremum', 'Extrem geomètric'), ('manual', 'Marcat a mà')], default='manual', max_length=20)),
                ('derivation_input', models.JSONField(blank=True, default=dict)),
                ('derivation_tiebreak', models.CharField(blank=True, default='', max_length=20)),
                ('evidence_num', models.IntegerField(blank=True, null=True)),
                ('evidence_den', models.IntegerField(blank=True, null=True)),
                ('evidence_ref', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Rol de punt notable',
                'verbose_name_plural': 'Rols de punt notable',
                'ordering': ['display_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='GarmentTypeItemEdgeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system', models.BooleanField(default=False)),
                ('pendent_revisio', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('SEED', 'Sembra'), ('MANUAL', 'Manual'), ('IMPORT', 'Importació')], default='MANUAL', max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('source_ref', models.TextField(blank=True, default='')),
                ('piece_role_slug', models.CharField(max_length=60)),
                ('face', models.CharField(blank=True, choices=[('', 'Sense cara'), ('front', 'Davant'), ('back', 'Darrere')], default='', max_length=6)),
                ('edge_role_slug', models.CharField(max_length=60)),
                ('presence', models.CharField(choices=[('core', 'Nucli'), ('common', 'Comuna'), ('rare', 'Rara')], max_length=8)),
                ('min_count', models.PositiveSmallIntegerField(default=1)),
                ('max_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observed_n', models.IntegerField(blank=True, null=True)),
                ('observed_den', models.IntegerField(blank=True, null=True)),
                ('observed_ref', models.TextField(blank=True, default='')),
                ('garment_type_item', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='edge_profiles', to='tasks.garmenttypeitem')),
            ],
            options={
                'verbose_name': 'Perfil de vores per item de garment',
                'verbose_name_plural': 'Perfils de vores per item de garment',
                'ordering': ['garment_type_item', 'display_order', 'piece_role_slug', 'edge_role_slug'],
                'constraints': [models.UniqueConstraint(fields=('garment_type_item', 'piece_role_slug', 'face', 'edge_role_slug'), name='uniq_gtiedgeprofile_canonic')],
            },
        ),
        migrations.CreateModel(
            name='SeamPairTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system', models.BooleanField(default=False)),
                ('pendent_revisio', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('SEED', 'Sembra'), ('MANUAL', 'Manual'), ('IMPORT', 'Importació')], default='MANUAL', max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('source_ref', models.TextField(blank=True, default='')),
                ('seam_kind', models.CharField(choices=[('union', 'Unió'), ('dart', 'Pinça'), ('centre', 'Centre'), ('level_join', 'Unió de nivells'), ('insert_join', "Unió d'inserció")], max_length=12)),
                ('piece_role_a_slug', models.CharField(max_length=60)),
                ('face_a', models.CharField(blank=True, choices=[('', 'Sense cara'), ('front', 'Davant'), ('back', 'Darrere')], default='', max_length=6)),
                ('edge_role_a_slug', models.CharField(max_length=60)),
                ('piece_role_b_slug', models.CharField(max_length=60)),
                ('face_b', models.CharField(blank=True, choices=[('', 'Sense cara'), ('front', 'Davant'), ('back', 'Darrere')], default='', max_length=6)),
                ('edge_role_b_slug', models.CharField(max_length=60)),
                ('co_generated', models.BooleanField(default=False)),
                ('observed_seams', models.IntegerField(blank=True, null=True)),
                ('observed_patterns', models.IntegerField(blank=True, null=True)),
                ('observed_den', models.IntegerField(blank=True, null=True)),
                ('observed_ref', models.TextField(blank=True, default='')),
                ('garment_type_item', models.ForeignKey(blank=True, db_constraint=False, help_text='NULL = plantilla genèrica, val per a qualsevol tipus de garment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seam_pair_templates', to='tasks.garmenttypeitem')),
            ],
            options={
                'verbose_name': 'Plantilla de parella de costura',
                'verbose_name_plural': 'Plantilles de parella de costura',
                'ordering': ['display_order', 'seam_kind', 'piece_role_a_slug', 'edge_role_a_slug'],
                'constraints': [models.UniqueConstraint(fields=('garment_type_item', 'seam_kind', 'piece_role_a_slug', 'face_a', 'edge_role_a_slug', 'piece_role_b_slug', 'face_b', 'edge_role_b_slug'), name='uniq_seampairtemplate_canonic')],
            },
        ),
    ]
