# Generated by Django 6.0.5 on 2026-08-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0084_cataleg_semantic_f3'),
        ('tasks', '0053_ronda_fora_de_comanda_ronda_linia_comanda_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seampairtemplate',
            name='uniq_seampairtemplate_canonic',
        ),
        migrations.AddConstraint(
            model_name='seampairtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('garment_type_item__isnull', False)), fields=('garment_type_item', 'seam_kind', 'piece_role_a_slug', 'face_a', 'edge_role_a_slug', 'piece_role_b_slug', 'face_b', 'edge_role_b_slug'), name='uniq_seampairtemplate_canonic'),
        ),
        migrations.AddConstraint(
            model_name='seampairtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('garment_type_item__isnull', True)), fields=('seam_kind', 'piece_role_a_slug', 'face_a', 'edge_role_a_slug', 'piece_role_b_slug', 'face_b', 'edge_role_b_slug'), name='uniq_seampairtemplate_canonic_generic'),
        ),
    ]
