# Generated by Django 6.0.5 on 2026-09-16 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0087_m3_cicle_vida_model'),
        ('pom', '0086_ordre_canonic_instancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpomalias',
            name='model_origen',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Model des del qual es va aprendre aquest àlies (import o vinculació manual).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alies_apresos', to='models_app.model', verbose_name="Model d'origen"),
        ),
    ]
