# Generated by Django 6.0.5 on 2026-09-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0087_m3_cicle_vida_model'),
        ('pom', '0087_alies_model_origen'),
        ('tasks', '0054_bloc_a_cost_hora_per_tasca'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerpomalias',
            name='uniq_customer_client_code',
        ),
        migrations.AddConstraint(
            model_name='customerpomalias',
            constraint=models.UniqueConstraint(fields=('customer', 'client_code', 'pom'), name='uniq_customer_client_code_pom'),
        ),
        migrations.AddConstraint(
            model_name='customerpomalias',
            constraint=models.UniqueConstraint(condition=models.Q(('pom__isnull', True)), fields=('customer', 'client_code'), name='uniq_customer_client_code_pom_null'),
        ),
    ]
