# Generated by Django 6.0.5 on 2026-07-07 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0032_distill_time_seeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(help_text='Nom canònic EN; display i18n a la UI.', max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(help_text='Nom canònic EN; display i18n a la UI.', max_length=200)),
                ('nature', models.CharField(choices=[('INTERNAL_SERVICE', 'Internal service'), ('EXTERNAL_SERVICE', 'External service'), ('GOODS', 'Goods'), ('PACK', 'Pack')], max_length=20)),
                ('price_mode', models.CharField(choices=[('FIXED', 'Fixed'), ('TIME_BASED', 'Time based')], default='FIXED', max_length=20)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preu de venda per unitat (FIXED).', max_digits=10, null=True)),
                ('sale_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tarifa de VENDA per minut (TIME_BASED). ≠ cost intern.', max_digits=10, null=True)),
                ('markup_pct', models.DecimalField(decimal_places=2, default=0, help_text='% de marge sobre el cost (externs/goods i TIME_BASED).', max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='commerce.unit')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_packs', to='commerce.product')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='commerce.product')),
            ],
            options={
                'verbose_name': 'Product component',
                'verbose_name_plural': 'Product components',
                'ordering': ['pack', 'component'],
                'unique_together': {('pack', 'component')},
            },
        ),
        migrations.CreateModel(
            name='ProductPriceGTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preu de venda per a aquest article en aquest GTI.', max_digits=10)),
                ('garment_type_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_exceptions', to='tasks.garmenttypeitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_exceptions', to='commerce.product')),
            ],
            options={
                'verbose_name': 'Product price exception (GTI)',
                'verbose_name_plural': 'Product price exceptions (GTI)',
                'ordering': ['product', 'garment_type_item'],
                'unique_together': {('product', 'garment_type_item')},
            },
        ),
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.SlugField(help_text='Referència a TaskType.code (mai PK).')),
                ('qty', models.DecimalField(decimal_places=2, default=1, help_text="Quantitat esperada d'aquesta tasca a la recepta.", max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='commerce.product')),
            ],
            options={
                'verbose_name': 'Product recipe line',
                'verbose_name_plural': 'Product recipe lines',
                'ordering': ['product', 'task_code'],
                'unique_together': {('product', 'task_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text="Preu de compra d'aquest proveïdor per a l'article.", max_digits=10)),
                ('is_default', models.BooleanField(default=False, help_text='Proveïdor triat per defecte a la línia.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='commerce.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_offers', to='tasks.supplier')),
            ],
            options={
                'verbose_name': 'Product supplier',
                'verbose_name_plural': 'Product suppliers',
                'ordering': ['product', '-is_default', 'cost_price'],
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
