# Generated by Django 6.0.5 on 2026-07-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_seed_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('last_seq', models.PositiveIntegerField(default=0, help_text='Últim número reservat.')),
            ],
            options={
                'verbose_name': 'Document sequence',
                'verbose_name_plural': 'Document sequences',
                'unique_together': {('doc_type', 'year')},
            },
        ),
    ]
