# Generated by Django 6.0.5 on 2026-07-07 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenantconfig_hourly_rate'),
        ('commerce', '0003_documentsequence'),
        ('tasks', '0034_supplier_adreca_linia1_supplier_adreca_linia2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, help_text="Generat a save() (reserve_document_number). Mai editable per l'usuari.", max_length=30, unique=True)),
                ('doc_type', models.CharField(choices=[('quote', 'Quote')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text="Import d'impostos (manual a B2; sense motor fiscal).", max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.userprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tasks.customer')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Override lliure del name del Product a la línia.', max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Preu congelat en crear la línia (còpia, no FK viva).', max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='quantity × unit_price, guardat.', max_digits=12)),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordre manual dins el document.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='commerce.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commerce.quote')),
            ],
            options={
                'verbose_name': 'Quote line',
                'verbose_name_plural': 'Quote lines',
                'ordering': ['quote', 'position', 'id'],
            },
        ),
    ]
