# Generated by Django 6.0.5 on 2026-07-08 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_seed_minute_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(help_text='Nom canònic; display i18n a la UI.', max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment terms',
                'verbose_name_plural': 'Payment terms',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTermLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('days_offset', models.PositiveIntegerField(default=0, help_text='Dies des de la data del document.')),
                ('position', models.PositiveIntegerField(default=0)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commerce.paymentterms')),
            ],
            options={
                'verbose_name': 'Payment term line',
                'verbose_name_plural': 'Payment term lines',
                'ordering': ['terms', 'position', 'id'],
            },
        ),
    ]
