# Generated by Django 6.0.5 on 2026-07-08 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_seed_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text="Tipus d'IVA de l'article (classificador de grup).", max_digits=4),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_documents', to='commerce.paymentterms'),
        ),
    ]
