# Generated by Django 6.0.5 on 2026-07-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_product_tax_rate_quote_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='tax_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA calculat sobre bases agregades (B3a). No editable.', max_digits=12),
        ),
    ]
