# Generated by Django 6.0.5 on 2026-07-08 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_quote_tax_breakdown_alter_quote_tax_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDueDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position', models.PositiveIntegerField(default=0)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_dates', to='commerce.quote')),
            ],
            options={
                'verbose_name': 'Document due date',
                'verbose_name_plural': 'Document due dates',
                'ordering': ['quote', 'position', 'id'],
            },
        ),
    ]
