# Generated by Django 6.0.5 on 2026-07-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantconfig_logo_file'),
        ('commerce', '0010_documentduedate'),
        ('tasks', '0035_customer_payment_method_customer_payment_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Override lliure del name del Product a la línia.', max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Preu congelat en crear la línia (còpia, no FK viva).', max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='quantity × unit_price, guardat.', max_digits=12)),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordre manual dins el document.')),
                ('qty_allocated', models.DecimalField(decimal_places=2, default=0, help_text='Quantitat imputada (≤ quantity). Control de cartera (B4).', max_digits=12)),
            ],
            options={
                'verbose_name': 'Sales order line',
                'verbose_name_plural': 'Sales order lines',
                'ordering': ['order', 'position', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='documentduedate',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Document due date', 'verbose_name_plural': 'Document due dates'},
        ),
        migrations.AlterField(
            model_name='documentduedate',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due_dates', to='commerce.quote'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='doc_type',
            field=models.CharField(choices=[('quote', 'Quote'), ('sales_order', 'Sales order')], max_length=20),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, help_text="Generat a save() (reserve_document_number). Mai editable per l'usuari.", max_length=30, unique=True)),
                ('doc_type', models.CharField(choices=[('quote', 'Quote'), ('sales_order', 'Sales order')], max_length=20)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='IVA calculat sobre bases agregades (B3a). No editable.', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_breakdown', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.userprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tasks.customer')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_documents', to='commerce.paymentterms')),
                ('source_quote', models.OneToOneField(blank=True, help_text='Oferta origen (traçabilitat). 1 oferta → 1 comanda (unique).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order', to='commerce.quote')),
            ],
            options={
                'verbose_name': 'Sales order',
                'verbose_name_plural': 'Sales orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentduedate',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due_dates', to='commerce.salesorder'),
        ),
        migrations.AddConstraint(
            model_name='documentduedate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quote__isnull', False), ('sales_order__isnull', True)), models.Q(('quote__isnull', True), ('sales_order__isnull', False)), _connector='OR'), name='duedate_exactly_one_parent'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commerce.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='commerce.product'),
        ),
    ]
