# Generated by Django 6.0.5 on 2026-07-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantconfig_logo_file'),
        ('commerce', '0011_salesorderline_alter_documentduedate_options_and_more'),
        ('models_app', '0051_documenttemplate_created_by'),
        ('tasks', '0036_alter_modeltask_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text="Generat a save() (reserve_document_number 'work_order'). Mai editable.", max_length=30, unique=True)),
                ('kind', models.CharField(choices=[('ORDER', 'Order'), ('COLLECTOR', 'Collector')], default='ORDER', max_length=20)),
                ('origin', models.CharField(choices=[('MANUAL', 'Manual'), ('EXTERNAL_BUS', 'External bus')], default='MANUAL', max_length=20)),
                ('period', models.CharField(blank=True, help_text="'YYYY-MM' — només per COLLECTOR (mes de recollida).", max_length=7)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('price_snapshot', models.JSONField(blank=True, default=dict)),
                ('recipe_snapshot', models.JSONField(blank=True, default=dict)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_closed', to='accounts.userprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders_created', to='accounts.userprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='tasks.customer')),
                ('model', models.ForeignKey(blank=True, help_text='null = col·lector (no lligat a un model concret).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='models_app.model')),
                ('order_line', models.ForeignKey(blank=True, help_text='Línia de comanda origen (nullable: encàrrec sense comanda / col·lector).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='commerce.salesorderline')),
            ],
            options={
                'verbose_name': 'Work order',
                'verbose_name_plural': 'Work orders',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'COLLECTOR')), fields=('customer', 'period'), name='uniq_collector_customer_period'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'COLLECTOR'), _negated=True), models.Q(('model__isnull', True), ('order_line__isnull', True)), _connector='OR'), name='collector_no_model_no_orderline')],
            },
        ),
    ]
