# Generated by Django 6.0.5 on 2026-07-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantconfig_logo_file'),
        ('commerce', '0012_workorder'),
        ('tasks', '0037_modeltask_off_recipe_modeltask_work_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EXTRA_BILL', 'Extra billed'), ('EXTRA_ABSORB', 'Extra absorbed'), ('DEDUCTION', 'Deduction')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Import (extres +, deduccions −). Decimal 0.01 (B3a).', max_digits=12)),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('model_task', models.ForeignKey(blank=True, help_text="L'extra/tasca resolta. Null per a deducció de concepte lliure.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='tasks.modeltask')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_resolved', to='accounts.userprofile')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='commerce.workorder')),
            ],
            options={
                'verbose_name': 'Work order adjustment',
                'verbose_name_plural': 'Work order adjustments',
                'ordering': ['work_order', 'id'],
            },
        ),
    ]
