# Generated by Django 6.0.5 on 2026-07-08 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantconfig_logo_file'),
        ('commerce', '0013_workorderadjustment'),
        ('tasks', '0037_modeltask_off_recipe_modeltask_work_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Cost real pagat al proveïdor (unitari).', max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, help_text='Preu de venda al client (unitari).', max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('incurred_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to='accounts.userprofile')),
                ('product', models.ForeignKey(help_text='Article extern (EXTERNAL_SERVICE) o mercaderia (GOODS).', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='commerce.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='tasks.supplier')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='commerce.workorder')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['work_order', 'id'],
            },
        ),
    ]
