# Generated by Django 6.0.5 on 2026-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantconfig_logo_file'),
        ('commerce', '0014_expense'),
        ('tasks', '0037_modeltask_off_recipe_modeltask_work_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workorderadjustment',
            constraint=models.UniqueConstraint(fields=('work_order', 'model_task'), name='uniq_adjustment_per_task'),
        ),
    ]
