# Generated by Django 6.0.5 on 2026-07-08 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantconfig_logo_file'),
        ('commerce', '0015_workorderadjustment_uniq_adjustment_per_task'),
        ('tasks', '0037_modeltask_off_recipe_modeltask_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='doc_type',
            field=models.CharField(choices=[('quote', 'Quote'), ('sales_order', 'Sales order'), ('delivery_note', 'Delivery note')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='doc_type',
            field=models.CharField(choices=[('quote', 'Quote'), ('sales_order', 'Sales order'), ('delivery_note', 'Delivery note')], max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, help_text="Generat a save() (reserve_document_number). Mai editable per l'usuari.", max_length=30, unique=True)),
                ('doc_type', models.CharField(choices=[('quote', 'Quote'), ('sales_order', 'Sales order'), ('delivery_note', 'Delivery note')], max_length=20)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='IVA calculat sobre bases agregades (B3a). No editable.', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_breakdown', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to='accounts.userprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tasks.customer')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes_issued', to='accounts.userprofile')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_documents', to='commerce.paymentterms')),
            ],
            options={
                'verbose_name': 'Delivery note',
                'verbose_name_plural': 'Delivery notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='delivery_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes_included', to='commerce.deliverynote'),
        ),
        migrations.CreateModel(
            name='DeliveryNoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Override lliure del name del Product a la línia.', max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Preu congelat en crear la línia (còpia, no FK viva).', max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, help_text='quantity × unit_price, guardat.', max_digits=12)),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordre manual dins el document.')),
                ('line_kind', models.CharField(choices=[('TASK', 'Task'), ('EXTRA', 'Extra'), ('DEDUCTION', 'Deduction'), ('EXPENSE', 'Expense'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_note_lines', to='commerce.workorderadjustment')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commerce.deliverynote')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_note_lines', to='commerce.expense')),
                ('model_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_note_lines', to='tasks.modeltask')),
                ('product', models.ForeignKey(blank=True, help_text='Nullable (override): una línia TASK/DEDUCTION/MANUAL pot no tenir article.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_note_lines', to='commerce.product')),
                ('work_order', models.ForeignKey(blank=True, help_text="WO d'origen de la línia (PROTECT: un WO albaranat no es pot esborrar).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_note_lines', to='commerce.workorder')),
            ],
            options={
                'verbose_name': 'Delivery note line',
                'verbose_name_plural': 'Delivery note lines',
                'ordering': ['delivery_note', 'position', 'id'],
            },
        ),
    ]
