# Generated by Django 6.0.5 on 2026-07-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_alter_quote_doc_type_alter_salesorder_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynoteline',
            name='internal_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minuts interns reals; fora del document (mai al PDF).', max_digits=10, null=True),
        ),
    ]
