# Generated by Django 6.0.5 on 2026-07-09 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantconfig_logo_file'),
        ('commerce', '0017_deliverynoteline_internal_minutes'),
        ('models_app', '0051_documenttemplate_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='invoiced_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='invoiced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes_invoiced', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='deliverynoteline',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_note_lines', to='models_app.model'),
        ),
        migrations.AddField(
            model_name='deliverynoteline',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('INVOICED', 'Invoiced')], default='DRAFT', max_length=20),
        ),
    ]
