# Generated by Django 6.0.5 on 2026-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_deliverynote_invoiced_at_deliverynote_invoiced_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Descripció canònica EN; display i18n a la UI.'),
        ),
    ]
