# Generated by Django 6.0.5 on 2026-07-20 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='orphaned_from_line',
            field=models.ForeignKey(blank=True, help_text="Línia de comanda d'on es va desassignar aquest WO (orfe).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphaned_work_orders', to='commerce.salesorderline'),
        ),
    ]
