# Generated by Django 6.0.5 on 2026-07-20 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tenantconfig_legal_footer'),
        ('commerce', '0020_workorder_orphaned_from_line'),
        ('models_app', '0057_model_reanchored_by_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteLineModelIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, help_text="Quantitat d'aquest model que es pensa produir per a la línia (informatiu).", max_digits=12)),
                ('position', models.PositiveIntegerField(default=0, help_text='Ordre manual dins la línia.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_line_intents_created', to='accounts.userprofile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_line_intents', to='models_app.model')),
                ('quote_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_intents', to='commerce.quoteline')),
            ],
            options={
                'verbose_name': 'Quote line model intent',
                'verbose_name_plural': 'Quote line model intents',
                'ordering': ['quote_line', 'position', 'id'],
                'unique_together': {('quote_line', 'model')},
            },
        ),
    ]
