# Generated by Django 6.0.5 on 2026-08-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_quotelinemodelintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='rounds_included',
            field=models.PositiveIntegerField(blank=True, help_text="Quantes voltes (rondes) cobreix el preu d'aquesta línia. null = sense límit; 0 = cap volta inclosa. FIT-5: el numeral viu a la comanda, mai al producte.", null=True),
        ),
    ]
