# Generated by Django 6.0.5 on 2026-09-09 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_salesorderline_rounds_included'),
        ('tasks', '0053_ronda_fora_de_comanda_ronda_linia_comanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynoteline',
            name='encarrec_directe',
            field=models.BooleanField(default=False, help_text='A7: volta fora del pacte — targeta pròpia, preu lliure, sense pressupost.'),
        ),
        migrations.AddField(
            model_name='deliverynoteline',
            name='linia_comanda',
            field=models.ForeignKey(blank=True, help_text='Línia de comanda que va proposar el preu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_note_lines', to='commerce.salesorderline'),
        ),
        migrations.AddField(
            model_name='deliverynoteline',
            name='rondes',
            field=models.ManyToManyField(blank=True, help_text='Voltes que aquesta línia cobreix. Buida a les línies llegades (per tasca) i a les manuals.', related_name='delivery_note_lines', to='tasks.ronda'),
        ),
    ]
