import { useState, useEffect, useCallback, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'

const API = import.meta.env.VITE_API_URL || ''

// Helper: schema pdfme complet = default del plugin + overrides (posició, mida, contingut...).
const mk = (def, over) => ({ ...def, ...over })

// ---- Template base de la fitxa (funció pura) --------------------------------
// Geometria A4 horitzontal (297×210). padding [24,10,24,10]: top 24 (header 18mm + 6 marge),
// bottom 24, laterals 10 de seguretat. staticSchema = capçalera/peu/caixa repetits a cada
// pàgina i NO movibles pel tècnic (readOnly). schemas: [[]] = una pàgina buida per editar.
// NOTA: pdfme no té prop "bold" al text (el negreta requereix registrar una font bold);
// amb la font per defecte s'aproxima amb mida/color. Els tokens de número de pàgina al peu
// dret necessiten el motor d'expressions de pdfme (no activat aquí) → text de crèdit fix.
function buildBaseTemplate(meta, defs) {
  const { textDef, rectDef } = defs
  const modelLine = meta.modelName ? `${meta.modelCode} · ${meta.modelName}` : meta.modelCode
  const metaLine = meta.authorNames ? `v${meta.version} · ${meta.authorNames}` : `v${meta.version}`
  const staticSchema = [
    // Capçalera
    mk(rectDef, { name: 'hdr_band', position: { x: 10, y: 10 }, width: 277, height: 18, color: '#f3ece0', borderColor: '#caa450', borderWidth: 0.2, readOnly: true }),
    mk(textDef, { name: 'hdr_client', position: { x: 12, y: 12 }, width: 85, height: 6, content: meta.customerName || '—', fontSize: 9, fontColor: '#7a5c10', readOnly: true }),
    mk(textDef, { name: 'hdr_model', position: { x: 100, y: 12 }, width: 100, height: 6, content: modelLine, fontSize: 9, alignment: 'center', fontColor: '#7a5c10', readOnly: true }),
    mk(textDef, { name: 'hdr_meta', position: { x: 240, y: 12 }, width: 45, height: 6, content: metaLine, fontSize: 8, alignment: 'right', fontColor: '#7a5c10', readOnly: true }),
    // Peu
    mk(rectDef, { name: 'ftr_band', position: { x: 10, y: 192 }, width: 277, height: 10, color: '#f3ece0', borderColor: '#caa450', borderWidth: 0.2, readOnly: true }),
    // Peu esquerra: nom de pàgina — editable pel tècnic (readOnly:false)
    mk(textDef, { name: 'ftr_pagename', position: { x: 12, y: 194 }, width: 90, height: 5, content: '', fontSize: 7, readOnly: false }),
    // Peu dreta: crèdit fix
    mk(textDef, { name: 'ftr_gen', position: { x: 200, y: 194 }, width: 85, height: 5, content: 'Generated by FHORT Textile Tech', fontSize: 7, alignment: 'right', fontColor: '#999999', readOnly: true }),
    // Caixa útil (border-only verd, visible a l'editor)
    mk(rectDef, { name: 'usefulbox', position: { x: 10, y: 28 }, width: 277, height: 162, color: '', borderColor: '#16a34a', borderWidth: 0.4, readOnly: true }),
  ]
  return { basePdf: { width: 297, height: 210, padding: [24, 10, 24, 10], staticSchema }, schemas: [[]] }
}

const hasSavedTemplate = (tj) =>
  tj && typeof tj === 'object' && Array.isArray(tj.schemas) && tj.schemas.length > 0

// Editor de fitxa tècnica — pantalla full-screen, FORA del layout principal (sense sidebar).
// pdfme es carrega amb dynamic import() dins useEffect (lazy: el bundle pesat només entra
// quan aquest component es munta, no afecta la resta de l'app).
export default function TechSheetEditor() {
  const { id } = useParams()
  const navigate = useNavigate()
  const token = localStorage.getItem('access_token')
  const authHeaders = { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }
  const uploadHeaders = { Authorization: `Bearer ${token}` }

  const [sheet, setSheet] = useState(null)
  const [model, setModel] = useState(null)
  const [lockState, setLockState] = useState('loading') // 'loading' | 'owned' | 'conflict' | 'error'
  const [conflict, setConflict] = useState(null)

  const [fitxers, setFitxers] = useState([])
  const [uploading, setUploading] = useState(false)

  // pdfme Designer
  const canvasRef = useRef(null)
  const designerRef = useRef(null)
  const pdfmeRef = useRef(null)      // { generate, getInputFromTemplate, plugins, defs }
  const saveTimer = useRef(null)
  const ownedRef = useRef(false)     // té el lock? (per evitar PATCH 403 en bucle)
  const assetSeq = useRef(0)         // comptador per noms únics d'asset (sense Date.now/random)
  const [designerState, setDesignerState] = useState('idle') // 'idle'|'loading'|'ready'|'error'
  const [designerErr, setDesignerErr] = useState('')
  const [saveState, setSaveState] = useState(null) // null|'saving'|'saved'|'error'|'readonly'
  const [exporting, setExporting] = useState(false)
  const [addingId, setAddingId] = useState(null)

  useEffect(() => { ownedRef.current = lockState === 'owned' }, [lockState])

  const loadFitxers = useCallback(() => {
    return fetch(`${API}/api/v1/model-fitxers/?model=${id}&ordering=-data_pujada`, { headers: authHeaders })
      .then(r => (r.ok ? r.json() : null))
      .then(d => { if (d) setFitxers(d.results || d || []) })
      .catch(() => {})
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id])

  // Autosave amb debounce real de 2s. Només desa si tenim el lock (sinó PATCH → 403).
  const debouncedSave = useCallback((template) => {
    if (!ownedRef.current) { setSaveState('readonly'); return }
    setSaveState('saving')
    if (saveTimer.current) clearTimeout(saveTimer.current)
    saveTimer.current = setTimeout(async () => {
      try {
        const r = await fetch(`${API}/api/v1/models/${id}/tech-sheet/update/`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('access_token')}` },
          body: JSON.stringify({ template_json: template }),
        })
        setSaveState(r.ok ? 'saved' : 'error')
      } catch { setSaveState('error') }
    }, 2000)
  }, [id])

  // Càrrega de dades (model, estat, lock, assets) — efecte original.
  useEffect(() => {
    if (!id) return
    let cancelled = false

    fetch(`${API}/api/v1/models/${id}/`, { headers: authHeaders })
      .then(r => (r.ok ? r.json() : null))
      .then(data => { if (!cancelled && data) setModel(data) })
      .catch(() => {})

    fetch(`${API}/api/v1/models/${id}/tech-sheet/`, { headers: authHeaders })
      .then(r => r.json())
      .then(data => { if (!cancelled) setSheet(data) })
      .catch(() => {})

    fetch(`${API}/api/v1/models/${id}/tech-sheet/lock/`, { method: 'POST', headers: authHeaders })
      .then(async r => {
        if (cancelled) return
        if (r.ok) { setSheet(await r.json()); setLockState('owned') }
        else if (r.status === 409) { setConflict(await r.json()); setLockState('conflict') }
        else { setLockState('error') }
      })
      .catch(() => { if (!cancelled) setLockState('error') })

    loadFitxers()

    return () => {
      cancelled = true
      fetch(`${API}/api/v1/models/${id}/tech-sheet/unlock/`, {
        method: 'POST', headers: authHeaders, keepalive: true,
      }).catch(() => {})
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id])

  // Inicialització del Designer: una sola vegada, quan model + sheet estan llestos.
  const canInit = !!sheet && !!model
  useEffect(() => {
    if (!canInit || designerRef.current || !canvasRef.current) return
    let disposed = false
    setDesignerState('loading')

    ;(async () => {
      try {
        const [uiMod, genMod, schemasMod, commonMod] = await Promise.all([
          import('@pdfme/ui'),
          import('@pdfme/generator'),
          import('@pdfme/schemas'),
          import('@pdfme/common'),
        ])
        if (disposed) return
        const { Designer } = uiMod
        const { generate } = genMod
        const { getInputFromTemplate } = commonMod
        const { text, image, rectangle } = schemasMod
        const plugins = { Text: text, Image: image, Rectangle: rectangle }
        const defs = {
          textDef: text.propPanel.defaultSchema,
          rectDef: rectangle.propPanel.defaultSchema,
          imageDef: image.propPanel.defaultSchema,
        }
        pdfmeRef.current = { generate, getInputFromTemplate, plugins, defs }

        const meta = {
          modelCode: model?.codi_intern || `#${id}`,
          modelName: model?.nom_prenda || '',
          customerName: model?.codi_client || '',
          version: sheet?.versio ?? 1,
          authorNames: model?.responsable_nom || model?.created_by_nom || '',
        }
        const tpl = hasSavedTemplate(sheet?.template_json)
          ? sheet.template_json
          : buildBaseTemplate(meta, defs)

        const designer = new Designer({ domContainer: canvasRef.current, template: tpl, plugins })
        designer.onChangeTemplate(t => debouncedSave(t))
        designerRef.current = designer
        setDesignerState('ready')
      } catch (e) {
        if (!disposed) { setDesignerErr(String(e?.message || e)); setDesignerState('error') }
      }
    })()

    return () => {
      disposed = true
      if (saveTimer.current) clearTimeout(saveTimer.current)
      try { designerRef.current?.destroy?.() } catch { /* noop */ }
      designerRef.current = null
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [canInit])

  // Pujada de fitxer (multipart). Refresca la llista en acabar.
  const handleUpload = async (file) => {
    if (!file) return
    setUploading(true)
    const fd = new FormData()
    fd.append('fitxer', file)
    fd.append('nom', file.name)
    try {
      const r = await fetch(`${API}/api/v1/models/${id}/upload-fitxer/`, {
        method: 'POST', headers: uploadHeaders, body: fd,
      })
      if (r.ok) await loadFitxers()
    } finally {
      setUploading(false)
    }
  }

  // Croquis: afegir un asset (fitxer) com a image schema al llenç.
  const addAssetToCanvas = async (f) => {
    const designer = designerRef.current
    const P = pdfmeRef.current
    if (!designer || !P) return
    let url = f.url_extern
    if (!url && f.fitxer) url = f.fitxer.startsWith('http') ? f.fitxer : `${API}${f.fitxer}`
    if (!url) return
    setAddingId(f.id)
    try {
      const blob = await fetch(url).then(r => { if (!r.ok) throw new Error('fetch ' + r.status); return r.blob() })
      const dataURL = await new Promise((res, rej) => {
        const fr = new FileReader()
        fr.onload = () => res(fr.result)
        fr.onerror = () => rej(new Error('FileReader error'))
        fr.readAsDataURL(blob)
      })
      const tpl = designer.getTemplate()
      // Nom únic: avança el comptador fins a un nom lliure (evita col·lisió amb assets desats).
      const used = new Set(tpl.schemas.flat().map(s => s.name))
      while (used.has(`asset_${assetSeq.current}`)) assetSeq.current += 1
      const asset = mk(P.defs.imageDef, {
        name: `asset_${assetSeq.current}`, type: 'image',
        position: { x: 15, y: 35 }, width: 80, height: 60, content: dataURL,
      })
      assetSeq.current += 1
      const next = {
        ...tpl,
        schemas: tpl.schemas.length ? tpl.schemas.map((pg, i) => (i === 0 ? [...pg, asset] : pg)) : [[asset]],
      }
      designer.updateTemplate(next)
      debouncedSave(next)
    } catch { /* silenci: el croquis no s'afegeix; no trenca l'editor */ }
    finally { setAddingId(null) }
  }

  // Exportar PDF (WYSIWYG: la mateixa template del Designer).
  const onExport = async () => {
    const designer = designerRef.current
    const P = pdfmeRef.current
    if (!designer || !P) return
    setExporting(true)
    try {
      const template = designer.getTemplate()
      const inputs = P.getInputFromTemplate(template)
      const pdf = await P.generate({ template, inputs, plugins: P.plugins })
      const blob = new Blob([pdf.buffer], { type: 'application/pdf' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${model?.codi_intern || id}_fitxa_v${sheet?.versio ?? 1}.pdf`
      a.click()
      URL.revokeObjectURL(url)
    } catch (e) {
      setDesignerErr('Export: ' + String(e?.message || e))
    } finally {
      setExporting(false)
    }
  }

  const badge = (() => {
    if (lockState === 'loading') return { text: 'Carregant…', bg: 'var(--gray-l)', fg: 'var(--text-main)' }
    if (lockState === 'owned') return { text: 'Editant', bg: 'var(--gold)', fg: 'var(--white)' }
    if (lockState === 'conflict') return {
      text: `Bloquejada per ${conflict?.locked_by || 'un altre usuari'}`,
      bg: 'var(--warn-bg)', fg: 'var(--warn)',
    }
    return { text: 'Error de bloqueig', bg: 'var(--warn-bg)', fg: 'var(--warn)' }
  })()

  const saveLabel = { saving: 'Desant…', saved: 'Desat', error: 'Error desant', readonly: 'Només lectura' }[saveState]

  const headerBtn = {
    display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, padding: '6px 10px',
    borderRadius: 6, border: '0.5px solid var(--gray-l)', background: 'var(--white)',
    cursor: 'pointer', color: 'var(--text-main)',
  }

  return (
    <div style={{ width: '100vw', height: '100vh', display: 'flex', flexDirection: 'column', background: 'var(--bg, #faf7f2)' }}>
      <header style={{
        display: 'flex', alignItems: 'center', gap: 12,
        padding: '0.7rem 1.2rem', borderBottom: '0.5px solid var(--gray-l)', background: 'var(--white)',
      }}>
        <button onClick={() => navigate(`/models/${id}`)} style={headerBtn}>
          <i className="ti ti-arrow-left" style={{ fontSize: 14 }} /> Tornar al model
        </button>
        <button onClick={onExport} disabled={designerState !== 'ready' || exporting}
          style={{ ...headerBtn, borderColor: 'var(--gold)', color: 'var(--gold)', opacity: designerState !== 'ready' || exporting ? 0.5 : 1 }}>
          <i className="ti ti-file-download" style={{ fontSize: 14 }} /> {exporting ? 'Exportant…' : 'Exportar PDF'}
        </button>
        <span style={{ fontSize: 14, fontWeight: 600, color: 'var(--text-main)' }}>
          {model?.codi_intern || `#${id}`}{model?.nom_prenda ? ` · ${model.nom_prenda}` : ''}
        </span>
        {sheet?.estat === 'tancat' && (
          <span style={{ fontSize: 11, color: 'var(--text-muted, #999)' }}>
            <i className="ti ti-lock" style={{ fontSize: 11, marginRight: 4 }} />Fitxa tancada
          </span>
        )}
        {saveLabel && (
          <span style={{ fontSize: 11, color: saveState === 'error' ? 'var(--warn)' : 'var(--text-muted, #999)' }}>
            {saveLabel}
          </span>
        )}
        <span style={{
          marginLeft: 'auto', fontSize: 11, fontWeight: 500, padding: '3px 10px',
          borderRadius: 10, background: badge.bg, color: badge.fg, whiteSpace: 'nowrap',
        }}>
          {badge.text}
        </span>
      </header>

      <main style={{ flex: 1, display: 'flex', minHeight: 0 }}>
        {/* Cos central — el Designer pdfme es munta a canvasRef. */}
        <div style={{ flex: 1, position: 'relative', minWidth: 0 }}>
          <div ref={canvasRef} style={{ position: 'absolute', inset: 0 }} />
          {designerState !== 'ready' && (
            <div style={{
              position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
              background: 'var(--bg, #faf7f2)', pointerEvents: designerState === 'error' ? 'auto' : 'none',
            }}>
              <div style={{ textAlign: 'center', color: 'var(--text-muted, #999)' }}>
                <i className={`ti ${designerState === 'error' ? 'ti-alert-triangle' : 'ti-file-text'}`} style={{ fontSize: 40, opacity: 0.5 }} />
                <p style={{ marginTop: 12, fontSize: 15 }}>
                  {designerState === 'error' ? `Error carregant l'editor: ${designerErr}` : 'Carregant editor de fitxa…'}
                </p>
              </div>
            </div>
          )}
        </div>

        {/* Panell d'assets inline — fitxers del model + pujada + afegir al llenç (croquis). */}
        <aside style={{
          width: 320, flexShrink: 0, borderLeft: '0.5px solid var(--gray-l)',
          background: 'var(--white)', display: 'flex', flexDirection: 'column', minHeight: 0,
        }}>
          <div style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '0.7rem 1rem', borderBottom: '0.5px solid var(--gray-l)',
          }}>
            <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-main)' }}>
              <i className="ti ti-paperclip" style={{ fontSize: 13, marginRight: 6 }} />
              Assets del model
            </span>
            <span style={{ fontSize: 11, color: 'var(--text-muted, #999)' }}>{fitxers.length}</span>
          </div>

          <label style={{
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
            margin: '0.8rem 1rem', padding: '8px', fontSize: 12, fontWeight: 500,
            borderRadius: 6, border: '0.5px dashed var(--gold)', color: 'var(--gold)',
            cursor: uploading ? 'default' : 'pointer',
            background: uploading ? 'var(--gray-l)' : 'transparent',
          }}>
            <i className="ti ti-upload" style={{ fontSize: 13 }} />
            {uploading ? 'Pujant…' : 'Pujar fitxer'}
            <input type="file" hidden disabled={uploading}
              onChange={e => { const f = e.target.files[0]; e.target.value = ''; handleUpload(f) }} />
          </label>

          <div style={{ flex: 1, overflowY: 'auto', padding: '0 1rem 1rem' }}>
            {fitxers.length === 0 ? (
              <p style={{ fontSize: 12, color: 'var(--text-muted, #999)', textAlign: 'center', marginTop: 8 }}>
                Cap fitxer encara.
              </p>
            ) : (
              fitxers.map(f => {
                const hasUrl = !!(f.url_extern || f.fitxer)
                return (
                  <div key={f.id} style={{ padding: '7px 0', borderBottom: '0.5px solid var(--gray-l)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <i className="ti ti-file" style={{ fontSize: 14, color: 'var(--text-muted, #999)', flexShrink: 0 }} />
                      <div style={{ minWidth: 0, flex: 1 }}>
                        <div style={{ fontSize: 12, color: 'var(--text-main)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }} title={f.nom_fitxer}>
                          {f.nom_fitxer}
                        </div>
                        <div style={{ fontSize: 10, color: 'var(--text-muted, #999)' }}>
                          {f.tipus}{f.versio ? ` · v${f.versio}` : ''}
                        </div>
                      </div>
                    </div>
                    <button
                      onClick={() => addAssetToCanvas(f)}
                      disabled={!hasUrl || designerState !== 'ready' || addingId === f.id}
                      title={hasUrl ? 'Afegir al llenç' : 'Sense URL de fitxer'}
                      style={{
                        marginTop: 5, display: 'flex', alignItems: 'center', gap: 4, fontSize: 11,
                        padding: '3px 8px', borderRadius: 5, border: '0.5px solid var(--gold)',
                        background: 'var(--white)', color: 'var(--gold)',
                        cursor: (!hasUrl || designerState !== 'ready') ? 'default' : 'pointer',
                        opacity: (!hasUrl || designerState !== 'ready') ? 0.45 : 1,
                      }}>
                      <i className="ti ti-photo-plus" style={{ fontSize: 12 }} />
                      {addingId === f.id ? 'Afegint…' : 'Afegir al llenç'}
                    </button>
                  </div>
                )
              })
            )}
          </div>
        </aside>
      </main>
    </div>
  )
}
