# Generated by Django 6.0.5 on 2026-07-12 19:22

import django.db.models.deletion
import fhort.patterns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_tenantconfig_address_tenantconfig_city_and_more'),
        ('models_app', '0056_modelfitxer_derivat_de_model'),
        ('tasks', '0038_modeltask_fitting_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versio', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('nom_fitxer', models.CharField(max_length=255)),
                ('fitxer_dxf', models.FileField(blank=True, null=True, upload_to=fhort.patterns.models.pattern_file_upload_to)),
                ('mida_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('mimetype', models.CharField(blank=True, max_length=100)),
                ('nom_rul', models.CharField(blank=True, max_length=255)),
                ('fitxer_rul', models.FileField(blank=True, null=True, upload_to=fhort.patterns.models.pattern_file_upload_to)),
                ('mida_rul_bytes', models.BigIntegerField(default=0)),
                ('checksum_rul', models.CharField(blank=True, max_length=64)),
                ('font_cad', models.CharField(blank=True, help_text="'polypattern', 'tuka'…", max_length=40)),
                ('escala_mm', models.FloatField(default=1.0, help_text='Factor de les unitats natives del fitxer a mm.')),
                ('unitats_metode', models.CharField(blank=True, help_text="Com s'han sabut les unitats: header / document_text / geometry / assumed.", max_length=20)),
                ('unitats_confianca', models.CharField(blank=True, max_length=10)),
                ('empremta', models.JSONField(blank=True, default=dict)),
                ('grade_table', models.JSONField(blank=True, null=True)),
                ('data_pujada', models.DateTimeField(auto_now_add=True)),
                ('garment_type_item', models.ForeignKey(blank=True, help_text='Patró de biblioteca (base de catàleg). La seva autoria és post-traçadora.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pattern_files', to='tasks.garmenttypeitem')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pattern_files', to='models_app.model')),
                ('pujat_per', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_files_pujats', to='accounts.userprofile')),
                ('source_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_files_sembrats', to='models_app.itemfitxer')),
                ('versio_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_posteriors', to='patterns.patternfile')),
            ],
            options={
                'verbose_name': 'Fitxer de patró',
                'verbose_name_plural': 'Fitxers de patró',
                'ordering': ['-data_pujada'],
            },
        ),
        migrations.CreateModel(
            name='PatternPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_block', models.CharField(max_length=120)),
                ('rol', models.CharField(blank=True, max_length=120)),
                ('contorns', models.JSONField(blank=True, default=list)),
                ('grain', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_entities', models.JSONField(blank=True, default=list)),
                ('doblec_original', models.JSONField(blank=True, null=True)),
                ('insert_at', models.JSONField(blank=True, default=list)),
                ('has_sew', models.BooleanField(default=False)),
                ('has_fold', models.BooleanField(default=False)),
                ('unknown_layers', models.JSONField(blank=True, default=list)),
                ('pattern_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='patterns.patternfile')),
            ],
            options={
                'verbose_name': 'Peça de patró',
                'verbose_name_plural': 'Peces de patró',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PatternPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mena', models.CharField(choices=[('vertex', 'Vèrtex'), ('notch', 'Piquet')], default='vertex', max_length=10)),
                ('boundary_index', models.IntegerField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('tipus', models.CharField(choices=[('turn', 'Gir'), ('curve', 'Corba'), ('unclassified', 'Sense classificar')], default='unclassified', max_length=15)),
                ('grade_rule_num', models.IntegerField(blank=True, null=True)),
                ('rastre', models.JSONField(blank=True, null=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='patterns.patternpiece')),
            ],
            options={
                'verbose_name': 'Punt de patró',
                'verbose_name_plural': 'Punts de patró',
                'ordering': ['piece', 'mena', 'boundary_index', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PatternSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vora', models.IntegerField(help_text='Índex de la vora dins la peça (boundary_index).')),
                ('t_inici', models.FloatField(help_text='0.0–1.0 sobre la longitud de la vora.')),
                ('t_fi', models.FloatField()),
                ('tipus_vora', models.CharField(blank=True, max_length=15)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='patterns.patternpiece')),
            ],
            options={
                'verbose_name': 'Segment de patró',
                'verbose_name_plural': 'Segments de patró',
                'ordering': ['piece', 'vora', 't_inici'],
            },
        ),
        migrations.AddConstraint(
            model_name='patternfile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('garment_type_item__isnull', True), ('model__isnull', False)), models.Q(('garment_type_item__isnull', False), ('model__isnull', True)), _connector='OR'), name='patternfile_xor_model_item'),
        ),
        migrations.AddConstraint(
            model_name='patternfile',
            constraint=models.UniqueConstraint(fields=('versio_anterior',), name='patternfile_un_sol_successor'),
        ),
        migrations.AddConstraint(
            model_name='patternpiece',
            constraint=models.UniqueConstraint(fields=('pattern_file', 'nom_block'), name='patternpiece_block_unic_per_fitxer'),
        ),
        migrations.AddIndex(
            model_name='patternpoint',
            index=models.Index(fields=['piece', 'boundary_index', 'ordre'], name='patterns_pa_piece_i_51ab63_idx'),
        ),
    ]
