# Generated by Django 6.0.5 on 2026-07-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tenantconfig_address_tenantconfig_city_and_more'),
        ('models_app', '0056_modelfitxer_derivat_de_model'),
        ('patterns', '0001_initial'),
        ('pom', '0036_gradingruleset_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SewRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('casat', 'Casat'), ('frunzit', 'Frunzit'), ('pinca', 'Pinça')], default='casat', max_length=10)),
                ('diferencial_cm', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('creat_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sew_relations_creades', to='accounts.userprofile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sew_relations', to='models_app.model')),
                ('segments_a', models.ManyToManyField(related_name='sew_relations_a', to='patterns.patternsegment')),
                ('segments_b', models.ManyToManyField(related_name='sew_relations_b', to='patterns.patternsegment')),
            ],
            options={
                'verbose_name': 'Costura',
                'verbose_name_plural': 'Costures',
                'ordering': ['model', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PatternPOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definicio_mesura', models.JSONField(default=dict)),
                ('valor_mesurat_cm', models.FloatField(blank=True, null=True)),
                ('metode', models.CharField(choices=[('recta', 'Distància recta'), ('vora', 'Longitud per vora')], default='recta', max_length=10)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('creat_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_poms_creats', to='accounts.userprofile')),
                ('pattern_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poms', to='patterns.patternpiece')),
                ('pom_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pattern_poms', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'POM ancorat',
                'verbose_name_plural': 'POMs ancorats',
                'ordering': ['pattern_piece', 'pom_master'],
                'constraints': [models.UniqueConstraint(fields=('pattern_piece', 'pom_master'), name='patternpom_un_ancoratge_per_peca')],
            },
        ),
    ]
