# Generated by Django 6.0.5 on 2026-07-12 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tenantconfig_address_tenantconfig_city_and_more'),
        ('fitting', '0015_fittingsession_finished_at_and_more'),
        ('patterns', '0002_sewrelation_patternpom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versio_patro', models.PositiveIntegerField()),
                ('destination_profile', models.CharField(max_length=40)),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('texts_shown', models.TextField()),
                ('grading_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pattern_export_acknowledgements', to='fitting.gradingversion')),
                ('pattern_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_acknowledgements', to='patterns.patternfile')),
                ('usuari', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_exports_reconeguts', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': "Reconeixement d'exportació",
                'verbose_name_plural': "Reconeixements d'exportació",
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['pattern_file', '-data'], name='patterns_ex_pattern_1e850b_idx')],
            },
        ),
    ]
