# Generated by Django 6.0.5 on 2026-07-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0004_patternsegment_nom_patternsegment_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewrelation',
            name='nom',
            field=models.CharField(blank=True, help_text='Nom triat a mà. Buit: es genera dels trams que uneix.', max_length=160),
        ),
    ]
