# Generated by Django 6.0.5 on 2026-07-13 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tenantconfig_address_tenantconfig_city_and_more'),
        ('models_app', '0056_modelfitxer_derivat_de_model'),
        ('patterns', '0005_sewrelation_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='SewProposalRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motiu', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sew_proposal_rejections', to='models_app.model')),
                ('rebutjat_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sew_proposals_rebutjades', to='accounts.userprofile')),
                ('segment_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebuigs_com_a', to='patterns.patternsegment')),
                ('segment_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebuigs_com_b', to='patterns.patternsegment')),
            ],
            options={
                'verbose_name': 'Proposta de costura rebutjada',
                'verbose_name_plural': 'Propostes de costura rebutjades',
                'ordering': ['-data'],
                'constraints': [models.UniqueConstraint(fields=('segment_a', 'segment_b'), name='sewproposalrejection_una_per_parella')],
            },
        ),
    ]
