# Generated by Django 6.0.5 on 2026-07-13 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tenantconfig_address_tenantconfig_city_and_more'),
        ('models_app', '0056_modelfitxer_derivat_de_model'),
        ('patterns', '0006_sewproposalrejection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DartProposalRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motiu', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dart_proposal_rejections', to='models_app.model')),
                ('punt_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebuigs_pinca_com_a', to='patterns.patternpoint')),
                ('punt_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebuigs_pinca_com_b', to='patterns.patternpoint')),
                ('punt_vertex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebuigs_pinca_com_vertex', to='patterns.patternpoint')),
                ('rebutjat_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dart_proposals_rebutjades', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Proposta de pinça rebutjada',
                'verbose_name_plural': 'Propostes de pinça rebutjades',
                'ordering': ['-data'],
                'constraints': [models.UniqueConstraint(fields=('punt_a', 'punt_vertex', 'punt_b'), name='dartproposalrejection_una_per_pinca')],
            },
        ),
    ]
