# Generated by Django 6.0.5 on 2026-07-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0007_dartproposalrejection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternsegment',
            name='origen',
            field=models.CharField(choices=[('auto', 'Derivat (gir a gir)'), ('natural', 'Derivat (costura natural)'), ('declarat', 'Declarat pel patronista')], default='auto', max_length=10),
        ),
    ]
