# Generated by Django 6.0.5 on 2026-07-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tenantconfig_address_tenantconfig_city_and_more'),
        ('patterns', '0008_alter_patternsegment_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=120)),
                ('t_inici', models.FloatField()),
                ('t_fi', models.FloatField()),
                ('accio', models.CharField(choices=[('confirmat', 'Confirmat tal com el motor el llegia'), ('allargat', 'Allargat respecte del que el motor llegia'), ('tallat', 'Escurçat respecte del que el motor llegia')], max_length=10)),
                ('vegades', models.PositiveIntegerField(default=1)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_at', models.DateTimeField(auto_now=True)),
                ('apres_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferencies_apreses', to='patterns.patternfile')),
                ('apres_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferencies_de_tram', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Preferència de tram per rol',
                'verbose_name_plural': 'Preferències de tram per rol',
                'ordering': ['rol', 't_inici'],
                'indexes': [models.Index(fields=['rol'], name='patterns_se_rol_8fbbb6_idx')],
                'constraints': [models.UniqueConstraint(fields=('rol', 'accio', 't_inici', 't_fi'), name='uniq_preferencia_rol_tram')],
            },
        ),
    ]
