# Generated by Django 6.0.5 on 2026-07-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tenantconfig_address_tenantconfig_city_and_more'),
        ('models_app', '0056_modelfitxer_derivat_de_model'),
        ('patterns', '0009_segmentpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='SewToleranceAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sew_relation_snapshot', models.IntegerField(help_text="L'id de la costura al moment de decidir (sobreviu si s'esborra).")),
                ('accio', models.CharField(choices=[('accepta', 'Accepta'), ('desaccepta', 'Desaccepta')], max_length=12)),
                ('tipus_relacio', models.CharField(help_text='casat/frunzit/pinca al moment de decidir.', max_length=12)),
                ('mena_tolerancia', models.CharField(help_text='La banda de llindars aplicada (muntatge/casat/pinca).', max_length=12)),
                ('desajust_cm', models.FloatField(help_text='El desviament congelat, en cm.')),
                ('grau', models.CharField(help_text='ok/warn/err al moment de decidir.', max_length=4)),
                ('llindar_verd_mm', models.FloatField(blank=True, null=True)),
                ('llindar_groc_mm', models.FloatField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, default='', help_text='Motiu opcional de la decisió.')),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decidit_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sew_tolerance_decisions', to='accounts.userprofile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sew_tolerance_acceptances', to='models_app.model')),
                ('sew_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tolerance_acceptances', to='patterns.sewrelation')),
            ],
            options={
                'verbose_name': 'Acceptació de tolerància de costura',
                'verbose_name_plural': 'Acceptacions de tolerància de costura',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['model', '-data'], name='patterns_se_model_i_7cecbf_idx'), models.Index(fields=['sew_relation', '-data'], name='patterns_se_sew_rel_02f3eb_idx')],
            },
        ),
    ]
