# Generated by Django 6.0.5 on 2026-07-30 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0010_sewtoleranceacceptance'),
        ('pom', '0051_patternpiecerole'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternpiece',
            name='estat_peca',
            field=models.CharField(choices=[('produccio', 'De producció'), ('treball', 'De treball'), ('referencia', 'De referència'), ('plantilla', 'Plantilla')], default='produccio', max_length=12),
        ),
        migrations.AddField(
            model_name='patternpiece',
            name='lateralitat',
            field=models.CharField(blank=True, choices=[('', 'Sense lateralitat'), ('L', 'Esquerra'), ('R', 'Dreta')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='patternpiece',
            name='nom',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='patternpiece',
            name='ordinal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patternpiece',
            name='piece_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='pom.patternpiecerole'),
        ),
        migrations.AddField(
            model_name='patternpiece',
            name='rol_origen',
            field=models.CharField(blank=True, choices=[('', 'Sense rol'), ('llegit', 'Llegit pel motor'), ('confirmat', 'Confirmat per una persona'), ('corregit', 'Corregit per una persona')], default='', max_length=10),
        ),
    ]
