# Generated by Django 6.0.5 on 2026-07-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tenantconfig_legal_footer'),
        ('patterns', '0012_backfill_rol_segmentpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceIdentityAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versio_patro', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=list)),
                ('data', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('texts_shown', models.TextField()),
                ('pattern_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_acknowledgements', to='patterns.patternfile')),
                ('usuari', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identitats_peces_confirmades', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': "Acta d'identitat de peces",
                'verbose_name_plural': "Actes d'identitat de peces",
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['pattern_file', '-data'], name='patterns_pi_pattern_00000d_idx')],
            },
        ),
    ]
