# Generated by Django 6.0.5 on 2026-07-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0013_pieceidentityacknowledgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternpiece',
            name='rol_origen',
            field=models.CharField(blank=True, choices=[('', 'Sense rol'), ('llegit', 'Llegit pel motor'), ('assignat', 'Assignat per una persona'), ('confirmat', 'Confirmat per una persona'), ('corregit', 'Corregit per una persona')], default='', max_length=10),
        ),
    ]
