# Generated by Django 6.0.5 on 2026-08-24 09:37

"""El mètode ORTOGONAL entra al vocabulari de `PatternPOM.metode`.

Només `choices`: Postgres no en desa cap constraint, així que aquesta migració no
genera ni una línia de SQL (`sqlmigrate` surt buit). Existeix igualment perquè l'estat
de les migracions i el dels models han de dir el mateix — si no, el `makemigrations`
següent de qualsevol altra sessió se l'inventaria.

Cap fila existent no canvia de valor: 'recta' i 'vora' segueixen sent el que eren.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0014_alter_patternpiece_rol_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternpom',
            name='metode',
            field=models.CharField(choices=[('recta', 'Distància recta'), ('vora', 'Longitud per vora'), ('ortogonal', 'Caiguda ortogonal')], default='recta', max_length=10),
        ),
    ]
