# Generated by Django 6.0.5 on 2026-08-24 11:00

"""El mètode PROJECCIÓ entra al vocabulari de `PatternPOM.metode`.

Germana de la 0015 i pel mateix motiu: només `choices`, o sigui `sqlmigrate` buit. Existeix
perquè l'estat de les migracions i el dels models diguin el mateix, no perquè hi hagi res a
alterar a la taula.

Cap fila existent no canvia de valor.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0015_patternpom_metode_ortogonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternpom',
            name='metode',
            field=models.CharField(choices=[('recta', 'Distància recta'), ('vora', 'Longitud per vora'), ('ortogonal', 'Caiguda ortogonal'), ('projeccio', 'Projecció sobre un eix')], default='recta', max_length=10),
        ),
    ]
