# Generated by Django 6.0.5 on 2026-08-24 11:05

"""On seu la línia de cota d'un POM ancorat. PRESENTACIÓ, mai mesura.

Primera migració d'aquesta sèrie que TOCA la taula de debò (les 0015 i 0016 eren només
`choices`). Columna nova amb `default=0.0` i `NOT NULL`: totes les files existents queden
amb la cota sobre la mesura, que és exactament on es dibuixava fins avui. Cap valor mesurat
no es toca ni es pot tocar des d'aquí.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0016_patternpom_metode_projeccio'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternpom',
            name='cota_offset_mm',
            field=models.FloatField(default=0.0, help_text='Desplaçament perpendicular de la línia de cota, en mm. Presentació pura.'),
        ),
    ]
