# Generated by Django 6.0.5 on 2026-08-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0017_patternpom_cota_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternpiece',
            name='face',
            field=models.CharField(blank=True, choices=[('', 'Sense cara'), ('front', 'Davant'), ('back', 'Darrere')], db_index=True, default='', max_length=6),
        ),
    ]
