# Generated by Django 6.0.5 on 2026-08-26 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0018_patternpiece_face'),
        ('pom', '0084_cataleg_semantic_f3'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternsegment',
            name='edge_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='segments', to='pom.edgerole'),
        ),
    ]
