# Generated by Django 6.0.5 on 2026-08-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0019_patternsegment_edge_role'),
        ('pom', '0085_unicitat_generica_seampairtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternpiece',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patternpiece',
            name='proposed_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patternpiece',
            name='proposed_face',
            field=models.CharField(blank=True, choices=[('', 'Sense cara'), ('front', 'Davant'), ('back', 'Darrere')], default='', max_length=6),
        ),
        migrations.AddField(
            model_name='patternpiece',
            name='proposed_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_pieces', to='pom.patternpiecerole'),
        ),
        migrations.AddField(
            model_name='patternpiece',
            name='proposed_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
