# Generated by Django 6.0.5 on 2026-05-25 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('rol_nom', models.CharField(max_length=80)),
                ('actiu', models.BooleanField(default=True)),
                ('cost_hora', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('color_avatar', models.CharField(default='#888888', max_length=7)),
                ('permisos', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Perfil d'usuari",
                'verbose_name_plural': "Perfils d'usuari",
            },
        ),
    ]
