# Generated by Django 6.0.5 on 2026-05-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitat_mesura', models.CharField(choices=[('CM', 'Centimetres (EU)'), ('INCH', 'Inches (US)')], default='CM', max_length=10)),
                ('norma_referencia', models.CharField(choices=[('ISO_8559', 'ISO 8559 (EU)'), ('ASTM_D13', 'ASTM D13 (US)')], default='ISO_8559', max_length=20)),
                ('nom_empresa', models.CharField(blank=True, max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant Configuration',
            },
        ),
    ]
