# Generated by Django 6.0.5 on 2026-06-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sprint_s1_foundations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jornada_override',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
