# Generated by Django 6.0.5 on 2026-07-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_jornada_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
