# Generated by Django 6.0.5 on 2026-07-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenantconfig_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
    ]
