# Generated by Django 6.0.5 on 2026-07-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantconfig_logo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN de cobrament (emissor).', max_length=34),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='payment_notes',
            field=models.TextField(blank=True, help_text="Notes de pagament de l'emissor (PDF)."),
        ),
    ]
