# Generated by Django 6.0.5 on 2026-07-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tenantconfig_iban_tenantconfig_payment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='address',
            field=models.CharField(blank=True, help_text="Adreça de l'emissor.", max_length=200),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='country',
            field=models.CharField(default='ES', help_text='ISO 3166-1 alpha-2.', max_length=2),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='legal_name',
            field=models.CharField(blank=True, help_text="Raó social legal de l'emissor.", max_length=200),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='tax_id',
            field=models.CharField(blank=True, help_text="NIF/VAT/tax id de l'emissor.", max_length=20),
        ),
    ]
