# Generated by Django 6.0.5 on 2026-07-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tenantconfig_address_tenantconfig_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='legal_footer',
            field=models.TextField(blank=True, default='', help_text='Peu legal dels documents (registre mercantil, LOPD…).'),
        ),
    ]
