# Generated by Django 6.0.5 on 2026-05-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('models_app', '0001_initial'),
        ('pom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TascaCataleg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_custom', models.CharField(blank=True, max_length=200, null=True)),
                ('minuts_estandard', models.PositiveIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('tasca_global', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalegs_tenant', to='pom.tascaglobal')),
            ],
            options={
                'verbose_name': 'Catàleg de tasca (tenant)',
                'verbose_name_plural': 'Catàlegs de tasca (tenant)',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ModelTasca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('estat', models.CharField(choices=[('Pendent', 'Pendent'), ('EnCurs', 'En curs'), ('Feta', 'Feta'), ('Bloquejada', 'Bloquejada')], default='Pendent', max_length=20)),
                ('data_limit', models.DateField(blank=True, null=True)),
                ('minuts_assignats', models.PositiveIntegerField()),
                ('minuts_reals', models.PositiveIntegerField(default=0)),
                ('cost_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_gate', models.BooleanField(default=False)),
                ('resultat_gate', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO_OK', 'No OK'), ('EXCEPCIO', 'Excepció')], max_length=20, null=True)),
                ('gate_data', models.DateTimeField(blank=True, null=True)),
                ('gate_notes', models.TextField(blank=True, null=True)),
                ('gate_revisat_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gates_revisades', to='accounts.userprofile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasques', to='models_app.model')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasques_assignades', to='accounts.userprofile')),
                ('tasca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancies', to='tasks.tascacataleg')),
            ],
            options={
                'verbose_name': 'Tasca de model',
                'verbose_name_plural': 'Tasques de model',
                'ordering': ['model', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='TimerEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inici', models.DateTimeField()),
                ('fi', models.DateTimeField(blank=True, null=True)),
                ('minuts', models.PositiveIntegerField(blank=True, null=True)),
                ('actiu', models.BooleanField(default=True)),
                ('model_tasca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='tasks.modeltasca')),
                ('tecnic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timers', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Entrada de timer',
                'verbose_name_plural': 'Entrades de timer',
                'ordering': ['-inici'],
            },
        ),
    ]
