# Generated by Django 6.0.5 on 2026-05-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0002_garmentgroup_pomcategory_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipologiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=40, unique=True)),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('familia', models.CharField(blank=True, max_length=80)),
                ('familia_codi', models.CharField(blank=True, max_length=20)),
                ('complexitat', models.CharField(blank=True, max_length=40, null=True)),
                ('patrons_aprox', models.CharField(blank=True, max_length=20, null=True)),
                ('slots_cad_client', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('slots_digitalitzacio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('slots_des_de_zero', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('slots_conf_proto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('slots_conf_proto_sample', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('slots_conf_proto_sample_size', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actiu', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('garment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipologies', to='pom.garmenttype')),
            ],
            options={
                'verbose_name': 'Tipologia de model',
                'verbose_name_plural': 'Tipologies de model',
                'ordering': ['familia_codi', 'codi'],
            },
        ),
    ]
