# Generated by Django 6.0.5 on 2026-05-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tipologiamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltasca',
            name='color_codi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='modeltasca',
            name='hores_reals',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='modeltasca',
            name='item_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modeltasca',
            name='paquet_origen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modeltasca',
            name='slots_base',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='modeltasca',
            name='slots_reals',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='modeltasca',
            name='tipus_encarrec',
            field=models.CharField(blank=True, choices=[('Proto', 'Proto'), ('Fit Sample', 'Fit Sample'), ('Size Set', 'Size Set'), ('PP Sample', 'PP Sample'), ('TOP Sample', 'TOP Sample'), ('Producció', 'Producció')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='modeltasca',
            name='cost_real',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
