# Generated by Django 6.0.5 on 2026-05-25 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0002_garmentgroup_pomcategory_and_more'),
        ('tasks', '0003_sprint1a_new_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_custom', models.CharField(blank=True, max_length=200, null=True)),
                ('minuts_estandard', models.PositiveIntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('nom_tasca', models.CharField(blank=True, max_length=200, null=True)),
                ('tipus_tasca', models.CharField(choices=[('Interna', 'Interna'), ('Externa', 'Externa'), ('Validació', 'Validació')], default='Interna', max_length=20)),
                ('fase', models.CharField(choices=[('Disseny', 'Disseny'), ('Tècnic', 'Tècnic'), ('Prototip', 'Prototip'), ('Mostres', 'Mostres'), ('Preproducció', 'Preproducció'), ('Producció', 'Producció')], default='Disseny', max_length=20)),
                ('ordre_base', models.IntegerField(default=0)),
                ('slots_base', models.FloatField(default=0.0, help_text='Referència orientativa. Els slots reals vénen de la tipologia del model.')),
                ('facturable', models.BooleanField(default=True, help_text='Els gates i tasques de validació no son facturables.')),
                ('bloqueja_model', models.BooleanField(default=False)),
                ('gate', models.BooleanField(default=False)),
                ('resultat_gate', models.CharField(blank=True, choices=[('OK', 'OK'), ('NO OK', 'NO OK'), ('EXCEPCIÓ', 'EXCEPCIÓ')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tasca_global', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalegs_tenant', to='pom.tascaglobal')),
            ],
            options={
                'verbose_name': 'Tasca (catàleg tenant)',
                'verbose_name_plural': 'Tasques (catàleg tenant)',
                'ordering': ['ordre_base', 'ordre'],
            },
        ),
        migrations.AlterField(
            model_name='modeltasca',
            name='tasca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancies', to='tasks.tasca'),
        ),
        migrations.DeleteModel(
            name='TascaCataleg',
        ),
    ]
