# Generated by Django 6.0.5 on 2026-05-25 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_sprint1b_rename_tasca'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaquetServei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('actiu', models.BooleanField(default=True)),
                ('grup', models.CharField(blank=True, choices=[('Patronatge', 'Patronatge'), ('Tech Pack', 'Tech Pack'), ('Mostres', 'Mostres'), ('Producció', 'Producció')], max_length=50, null=True)),
                ('multiplicador', models.FloatField(blank=True, null=True)),
                ('slots_base', models.FloatField(blank=True, null=True)),
                ('ordre_popup', models.IntegerField(blank=True, null=True)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('notes_comercials', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paquet de servei',
                'verbose_name_plural': 'Paquets de servei',
                'ordering': ['ordre_popup', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PaquetServeiTasca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('opcional', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('paquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasques', to='tasks.paquetservei')),
                ('tasca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquets', to='tasks.tasca')),
            ],
            options={
                'verbose_name': 'Tasca de paquet',
                'verbose_name_plural': 'Tasques de paquet',
                'ordering': ['ordre'],
                'unique_together': {('paquet', 'tasca')},
            },
        ),
    ]
