# Generated by Django 6.0.5 on 2026-05-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_sprint1b_new_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasca',
            name='resultat_gate',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('NO_OK', 'No OK'), ('EXCEPCIO', 'Excepció')], max_length=20, null=True),
        ),
    ]
