# Generated by Django 6.0.5 on 2026-05-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_tasca_resultat_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltasca',
            name='cost_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
