# Generated by Django 6.0.5 on 2026-05-31 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sprint_s1_foundations'),
        ('models_app', '0022_modelgradingoverride'),
        ('tasks', '0007_alter_modeltasca_cost_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('default_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Task type',
                'verbose_name_plural': 'Task types',
                'ordering': ['default_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ModelTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paused', 'Paused'), ('InProgress', 'InProgress'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='accounts.userprofile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_tasks', to='models_app.model')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='tasks.tasktype')),
            ],
            options={
                'verbose_name': 'Model task',
                'verbose_name_plural': 'Model tasks',
                'ordering': ['model', 'order'],
            },
        ),
    ]
