# Generated by Django 6.0.5 on 2026-05-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sprint_s1_foundations'),
        ('tasks', '0008_tasktype_modeltask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerentrada',
            name='model_tasca',
        ),
        migrations.AddField(
            model_name='modeltask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modeltask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timerentrada',
            name='model_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='tasks.modeltask'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaskTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_transitions', to='accounts.userprofile')),
                ('model_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='tasks.modeltask')),
            ],
            options={
                'verbose_name': 'Task transition',
                'verbose_name_plural': 'Task transitions',
                'ordering': ['at'],
            },
        ),
        migrations.DeleteModel(
            name='ModelTasca',
        ),
    ]
