# Generated by Django 6.0.5 on 2026-05-31 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sprint_s1_foundations'),
        ('models_app', '0022_modelgradingoverride'),
        ('tasks', '0009_remove_timerentrada_model_tasca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_phase', models.CharField(blank=True, max_length=20, null=True)),
                ('to_phase', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_events', to='accounts.userprofile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_events', to='models_app.model')),
            ],
            options={
                'verbose_name': 'Gate event',
                'verbose_name_plural': 'Gate events',
                'ordering': ['at'],
            },
        ),
    ]
