# Generated by Django 6.0.5 on 2026-05-31 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0012_alter_clientmesuraperfil_options_and_more'),
        ('tasks', '0011_supplier_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltask',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Snapshot del temps estimat en crear la tasca (minuts).', null=True),
        ),
        migrations.CreateModel(
            name='GarmentTypeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('complexity_order', models.PositiveIntegerField(default=0, help_text='Ordre de complexitat creixent dins la família')),
                ('active', models.BooleanField(default=True)),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pom.garmenttype')),
            ],
            options={
                'verbose_name': 'Garment type item',
                'verbose_name_plural': 'Garment type items',
                'ordering': ['garment_type', 'complexity_order', 'code'],
                'unique_together': {('garment_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaskTimeEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('garment_type_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_estimates', to='tasks.garmenttypeitem')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_estimates', to='tasks.tasktype')),
            ],
            options={
                'verbose_name': 'Task time estimate',
                'verbose_name_plural': 'Task time estimates',
                'unique_together': {('garment_type_item', 'task_type')},
            },
        ),
    ]
