# Generated by Django 6.0.5 on 2026-05-31 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sprint_s1_foundations'),
        ('tasks', '0012_modeltask_estimated_minutes_garmenttypeitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('technician_count', models.PositiveIntegerField(default=1)),
                ('working_minutes_per_day', models.PositiveIntegerField(default=420)),
                ('blocked_dates', models.JSONField(blank=True, default=list)),
                ('model_sequence', models.JSONField(blank=True, default=list)),
                ('campaign_filter', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_snapshots', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Plan snapshot',
                'verbose_name_plural': 'Plan snapshots',
                'ordering': ['-computed_at'],
            },
        ),
    ]
