# Generated by Django 6.0.5 on 2026-05-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_plansnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktimeestimate',
            name='m2',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='tasktimeestimate',
            name='mean_minutes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tasktimeestimate',
            name='n',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
