# Generated by Django 6.0.5 on 2026-06-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_tasktimeestimate_m2_tasktimeestimate_mean_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltask',
            name='planned_end',
            field=models.DateTimeField(blank=True, help_text='Fi prevista calculada pel motor.', null=True),
        ),
        migrations.AddField(
            model_name='modeltask',
            name='planned_locked',
            field=models.BooleanField(default=False, help_text='Posició manual fixa: el recàlcul es col·loca al voltant.'),
        ),
        migrations.AddField(
            model_name='modeltask',
            name='planned_start',
            field=models.DateTimeField(blank=True, help_text='Inici previst calculat pel motor (calendari laboral).', null=True),
        ),
    ]
