# Generated by Django 6.0.5 on 2026-06-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_modeltask_planned_end_modeltask_planned_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paused', 'Paused'), ('InProgress', 'InProgress'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
