# Generated by Django 6.0.5 on 2026-06-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_modeltask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateevent',
            name='kind',
            field=models.CharField(choices=[('advance', 'advance'), ('regress', 'regress')], default='advance', max_length=10),
        ),
        migrations.AlterField(
            model_name='modeltask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paused', 'Paused'), ('InProgress', 'InProgress'), ('Done', 'Done')], default='Pending', max_length=20),
        ),
    ]
