# Generated by Django 6.0.5 on 2026-06-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0029_model_shrinkage_iso_key'),
        ('tasks', '0017_gateevent_kind_alter_modeltask_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modeltask',
            unique_together={('model', 'task_type')},
        ),
    ]
