# Generated by Django 6.0.5 on 2026-06-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_modeltask_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=3, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('is_self', models.BooleanField(default=False, help_text="El tenant com a client d'ell mateix (self-customer).")),
                ('codi_global', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['codi'],
            },
        ),
    ]
