# Generated by Django 6.0.5 on 2026-06-22 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0024_remove_gradingrule_valor_base'),
        ('tasks', '0021_add_customer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmenttypeitem',
            name='base_size_definition',
            field=models.ForeignKey(blank=True, help_text="Talla base de la plantilla de l'Item (on s'expressen els valors base). Lliure ara; es constrenyirà al run quan existeixi Item→GradingRuleSet.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_for_items', to='pom.sizedefinition'),
        ),
    ]
