# Generated by Django 6.0.5 on 2026-06-22 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0026_itembasemeasurement_nom_fitxa'),
        ('tasks', '0022_garmenttypeitem_base_size_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmenttypeitem',
            name='grading_rule_set',
            field=models.ForeignKey(blank=True, help_text="Context de grading de l'Item (un sol ruleset). Mutable; obligatori a la pàgina (Fase B). Constreny base_size_definition al seu size_system.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garment_type_items', to='pom.gradingruleset'),
        ),
        migrations.AlterField(
            model_name='garmenttypeitem',
            name='base_size_definition',
            field=models.ForeignKey(blank=True, help_text="Talla base de la plantilla de l'Item (on s'expressen els valors base). Es constreny al size_system del grading_rule_set (validat a clean()).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_for_items', to='pom.sizedefinition'),
        ),
    ]
