# Generated by Django 6.0.5 on 2026-06-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_garmenttypeitem_grading_rule_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='eina',
            field=models.CharField(blank=True, help_text="Slug de l'eina que transporta la tasca. null = transport manual / eina futura.", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='facturable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='fase',
            field=models.CharField(choices=[('Disseny', 'Disseny'), ('Dev. tècnic', 'Dev. tècnic'), ('Prototip', 'Prototip'), ('Mostres', 'Mostres'), ('Preproducció', 'Preproducció'), ('Producció', 'Producció')], default='Dev. tècnic', max_length=20),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='mode',
            field=models.CharField(blank=True, help_text="Context d'obertura de l'eina (sub-mode). null si sense eina.", max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='tipus',
            field=models.CharField(choices=[('Interna', 'Interna'), ('Externa-lliure', 'Externa-lliure')], default='Interna', max_length=20),
        ),
    ]
