# Generated by Django 6.0.5 on 2026-06-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0043_delete_modelservei'),
        ('tasks', '0025_seed_canonical_task_types'),
    ]

    operations = [
        # AlterUniqueTogether ha d'anar PRIMER: no es pot fer RemoveField d'un camp que
        # encara forma part d'un unique_together (l'autodetector ho va ordenar malament i
        # petava amb FieldDoesNotExist en executar-se sobre un schema real).
        migrations.AlterUniqueTogether(
            name='paquetserveitasca',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='paquetserveitasca',
            name='paquet',
        ),
        migrations.RemoveField(
            model_name='paquetserveitasca',
            name='tasca',
        ),
        migrations.RemoveField(
            model_name='tasca',
            name='tasca_global',
        ),
        migrations.DeleteModel(
            name='PaquetServei',
        ),
        migrations.DeleteModel(
            name='PaquetServeiTasca',
        ),
        migrations.DeleteModel(
            name='Tasca',
        ),
    ]
