# Generated by Django 6.0.5 on 2026-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_remove_paquetserveitasca_paquet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('task', 'task'), ('phase', 'phase')], max_length=10)),
                ('key', models.CharField(help_text="TaskType.code si scope='task'; TaskType.fase (nom de fase) si scope='phase'.", max_length=50)),
                ('minuts', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Time seed',
                'verbose_name_plural': 'Time seeds',
                'unique_together': {('scope', 'key')},
            },
        ),
    ]
