# Generated by Django 6.0.5 on 2026-06-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_timeseed'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltask',
            name='origen',
            field=models.CharField(choices=[('prevista', 'Prevista'), ('ad_hoc', 'Ad-hoc')], default='prevista', max_length=20),
        ),
    ]
