# Generated by Django 6.0.5 on 2026-06-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_modeltask_origen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipologiaModel',
        ),
    ]
