# Generated by Django 6.0.5 on 2026-07-07 14:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_jornada_override'),
        ('tasks', '0030_normalize_audit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeseed',
            name='origen',
            field=models.CharField(choices=[('ONBOARDING', 'ONBOARDING'), ('CAPTURA', 'CAPTURA'), ('MIGRACIO', 'MIGRACIO')], default='MIGRACIO', help_text="Procedència: sembra d'onboarding, captura conscient del PM, o destil·lació de cel·les teòriques.", max_length=12),
        ),
        migrations.AddField(
            model_name='timeseed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timeseed',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.userprofile'),
        ),
    ]
