# Generated by Django 6.0.5 on 2026-07-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_distill_time_seeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adreca_linia1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='adreca_linia2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='ciutat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='codi_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='condicions_pagament',
            field=models.CharField(blank=True, help_text='Termini/forma de pagament (text lliure).', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='descompte_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de descompte comercial per defecte.', max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_facturacio',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='nif',
            field=models.CharField(blank=True, help_text='NIF/VAT/tax id.', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='pais',
            field=models.CharField(default='ES', help_text='ISO 3166-1 alpha-2.', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='persona_contacte',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='rao_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='telefon_contacte',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
