# Generated by Django 6.0.5 on 2026-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_customer_adreca_linia1_customer_adreca_linia2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='adreca_linia1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='adreca_linia2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ciutat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='codi_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='condicions_compra',
            field=models.CharField(blank=True, help_text='Termini/forma de compra (text lliure).', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email_contacte',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='nif',
            field=models.CharField(blank=True, help_text='NIF/VAT/tax id.', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pais',
            field=models.CharField(default='ES', help_text='ISO 3166-1 alpha-2.', max_length=2),
        ),
        migrations.AddField(
            model_name='supplier',
            name='persona_contacte',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rao_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='telefon_contacte',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
