# Generated by Django 6.0.5 on 2026-07-08 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_seed_payment_terms'),
        ('tasks', '0034_supplier_adreca_linia1_supplier_adreca_linia2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(choices=[('TRANSFER', 'Bank transfer'), ('DIRECT_DEBIT', 'Direct debit'), ('CONFIRMING', 'Confirming'), ('CASH', 'Cash')], default='TRANSFER', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.ForeignKey(blank=True, help_text='Condició de pagament per defecte del client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_customers', to='commerce.paymentterms'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_regime',
            field=models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTRA_EU', 'Intra-EU'), ('EXPORT', 'Export'), ('EXEMPT', 'Exempt')], default='DOMESTIC', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, help_text='NIF-IVA intracomunitari; només informatiu v1 (sense VIES).', max_length=30),
        ),
    ]
