# Generated by Django 6.0.5 on 2026-07-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tenantconfig_logo_file'),
        ('models_app', '0051_documenttemplate_created_by'),
        ('tasks', '0035_customer_payment_method_customer_payment_terms_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modeltask',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='modeltask',
            constraint=models.UniqueConstraint(condition=models.Q(('origen', 'prevista')), fields=('model', 'task_type'), name='uniq_prevista_model_tasktype'),
        ),
    ]
