# Generated by Django 6.0.5 on 2026-07-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_workorder'),
        ('tasks', '0036_alter_modeltask_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltask',
            name='off_recipe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modeltask',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='commerce.workorder'),
        ),
    ]
