# Generated by Django 6.0.5 on 2026-07-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0015_fittingsession_finished_at_and_more'),
        ('tasks', '0037_modeltask_off_recipe_modeltask_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltask',
            name='fitting_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_tasks', to='fitting.fittingsession'),
        ),
    ]
