# Generated by Django 6.0.5 on 2026-07-23 05:14

from django.db import migrations, models


def backfill_codi_global(apps, schema_editor):
    """Fixa codi_global = codi per al self-Customer de cada tenant (identitat canònica,
    la mateixa que escriu bootstrap_tenant._close_onboarding). Els customers no-self es
    deixen a NULL: el TenantLink els resoldrà. Idempotent (només escriu si difereix)."""
    Customer = apps.get_model('tasks', 'Customer')
    for cust in Customer.objects.filter(is_self=True).exclude(codi_global=models.F('codi')):
        cust.codi_global = cust.codi
        cust.save(update_fields=['codi_global'])


def unbackfill(apps, schema_editor):
    """Revers: buida el codi_global dels self-customers (torna a l'estat placeholder)."""
    Customer = apps.get_model('tasks', 'Customer')
    Customer.objects.filter(is_self=True).update(codi_global=None)


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_quotelinemodelintent'),
        ('tasks', '0038_modeltask_fitting_session'),
    ]

    operations = [
        migrations.RunPython(backfill_codi_global, unbackfill),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('codi_global__isnull', False)), fields=('codi_global',), name='unic_codi_global_no_null'),
        ),
    ]
