# Generated by Django 6.0.5 on 2026-07-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_backfill_codi_global_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(blank=True, choices=[('ca', 'Català'), ('en', 'English'), ('es', 'Español')], default='', help_text="Idioma per defecte dels PDF comercials. Buit = sense preselecció; l'operador tria en emetre.", max_length=5),
        ),
    ]
