# Generated by Django 6.0.5 on 2026-07-27 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_customer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmenttypeitem',
            name='is_set',
            field=models.BooleanField(default=False, help_text='Aquest item és un CONJUNT: la seva composició viu a GarmentTypeItemPart.'),
        ),
        migrations.CreateModel(
            name='GarmentTypeItemPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Posició de la peça al conjunt (dona el sufix -01/-02/-03).')),
                ('nom_peca', models.CharField(blank=True, default='', help_text='Nom de la peça dins el conjunt (ex: «Top», «Bikini bottom»).', max_length=120)),
                ('part_item', models.ForeignKey(help_text="L'item que fa de PEÇA dins el conjunt.", on_delete=django.db.models.deletion.PROTECT, related_name='part_of', to='tasks.garmenttypeitem')),
                ('set_item', models.ForeignKey(help_text="L'item CONJUNT (el que té is_set=True).", on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='tasks.garmenttypeitem')),
            ],
            options={
                'verbose_name': "Peça d'un item-conjunt",
                'verbose_name_plural': 'Peces dels items-conjunt',
                'ordering': ['set_item', 'ordre', 'id'],
                'unique_together': {('set_item', 'part_item')},
            },
        ),
    ]
