# Generated by Django 6.0.5 on 2026-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_garmenttypeitem_set_i_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktransition',
            name='auto',
            field=models.CharField(blank=True, help_text="Marca d'automatisme. null = gest humà del tècnic; slug del guard que ha actuat en cas contrari.", max_length=32, null=True),
        ),
    ]
