# Generated by Django 6.0.5 on 2026-07-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_tasktransition_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerentrada',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Últim senyal de vida del tècnic sobre el tram obert. null = cap encara (val `inici`).', null=True),
        ),
    ]
