# Generated by Django 6.0.5 on 2026-08-05 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0078_c4_g3_retira_comportes'),
        ('tasks', '0043_timerentrada_last_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltask',
            name='mare',
            field=models.ForeignKey(blank=True, help_text='La tasca homònima de la volta anterior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filles', to='tasks.modeltask'),
        ),
        migrations.AddField(
            model_name='modeltask',
            name='motiu',
            field=models.CharField(blank=True, choices=[('nova_mostra', 'Nova mostra'), ('correccio', 'Correcció')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(help_text='Número de volta dins del model. La ronda 1 és implícita (ronda NULL).')),
                ('motiu', models.CharField(choices=[('nova_mostra', 'Nova mostra'), ('correccio', 'Correcció')], max_length=20)),
                ('oberta_el', models.DateTimeField(auto_now_add=True)),
                ('tancada_el', models.DateTimeField(blank=True, help_text='null = oberta. És la definició de «vigent».', null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondes', to='models_app.model')),
            ],
            options={
                'verbose_name': 'Ronda',
                'verbose_name_plural': 'Rondes',
                'ordering': ['model', 'seq'],
            },
        ),
        migrations.AddField(
            model_name='modeltask',
            name='ronda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasques', to='tasks.ronda'),
        ),
        migrations.AddConstraint(
            model_name='ronda',
            constraint=models.UniqueConstraint(fields=('model', 'seq'), name='uniq_ronda_model_seq'),
        ),
    ]
