# Generated by Django 6.0.5 on 2026-08-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0044_modeltask_mare_modeltask_motiu_ronda_modeltask_ronda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='es_lliurable',
            field=models.BooleanField(default=False, help_text='La tasca produeix un lliurable per al client (fitxa, patró).'),
        ),
    ]
