# Generated by Django 6.0.5 on 2026-08-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_cataleg_f1_sample_check_lliurables'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerentrada',
            name='origen',
            field=models.CharField(choices=[('mesurat', 'Mesurat'), ('declarat', 'Declarat')], default='mesurat', max_length=10),
        ),
    ]
