# Generated by Django 6.0.5 on 2026-08-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pom', '0073_u2_acumulacio_poms'),
        ('tasks', '0048_tasktype_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmenttypeitem',
            name='proposed_base_size_label',
            field=models.CharField(blank=True, default='', help_text="Etiqueta de la talla base proposada (p.ex. 'M'), dins de proposed_size_system. Etiqueta i no FK: les regles ancoren per etiqueta (CAT2.1).", max_length=30),
        ),
        migrations.AddField(
            model_name='garmenttypeitem',
            name='proposed_size_system',
            field=models.ForeignKey(blank=True, help_text='Run de talles que aquest item PROPOSA (suggeriment del catàleg). No mana sobre el size_system del joc de regles ni sobre cap ItemBaseSet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_by_items', to='pom.sizesystem'),
        ),
    ]
