# Generated by Django 6.0.5 on 2026-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0049_garmenttypeitem_proposed_base_size_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerentrada',
            name='consulta',
            field=models.BooleanField(default=None, help_text='True = tram tancat sense cap escriptura (consulta). null = nascut abans del camp: no jutjat, compta com sempre.', null=True),
        ),
        migrations.AddField(
            model_name='timerentrada',
            name='escriptura_at',
            field=models.DateTimeField(blank=True, help_text='Última ESCRIPTURA de dades dins del tram (batec_escriptura). null = cap.', null=True),
        ),
    ]
