# Generated by Django 6.0.5 on 2026-08-24 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tenantconfig_legal_footer'),
        ('tasks', '0050_j_consulta_marca_escriptura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, help_text='Quan es va entregar, segons qui ho informa. Per defecte ara.')),
                ('destinatari', models.CharField(help_text='A qui se li ha entregat. TEXT LLIURE: no és el client que factura.', max_length=200)),
                ('descripcio', models.TextField(blank=True, help_text="Què s'ha enviat, dit amb paraules. TEXT LLIURE: no hi ha cap artefacte lligat.")),
                ('data_ok', models.DateTimeField(blank=True, help_text='null = el client encara no ha dit res.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Quan es va ESCRIURE la fila (≠ `data`).')),
                ('qui_informa', models.ForeignKey(blank=True, help_text="Qui informa l'acte. SET_NULL: esborrar un usuari no esborra la història.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregues_informades', to='accounts.userprofile')),
                ('qui_informa_ok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oks_informats', to='accounts.userprofile')),
                ('ronda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='tasks.ronda')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregues',
                'ordering': ['-data'],
            },
        ),
    ]
