# Generated by Django 6.0.5 on 2026-08-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0051_m1_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktransition',
            name='nota',
            field=models.TextField(blank=True, help_text='Rastre en text del context del gest. null = res a dir.', null=True),
        ),
    ]
