# Generated by Django 6.0.5 on 2026-08-25 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_salesorderline_rounds_included'),
        ('tasks', '0052_m1_rastre_reobertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ronda',
            name='fora_de_comanda',
            field=models.BooleanField(default=False, help_text='FIT-12: aquesta volta supera el numeral de la comanda i es factura a part. Es resol en obrir i no es recalcula.'),
        ),
        migrations.AddField(
            model_name='ronda',
            name='linia_comanda',
            field=models.ForeignKey(blank=True, help_text="Línia de comanda que governava el numeral en obrir la volta. SET_NULL: esborrar la línia no ha d'esborrar la història de la volta. null = el model no tenia comanda (llavors no hi ha límit i no es desborda mai).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondes', to='commerce.salesorderline'),
        ),
        migrations.AddField(
            model_name='ronda',
            name='numeral_vigent',
            field=models.PositiveIntegerField(blank=True, help_text='El numeral que hi havia en obrir la volta (foto). null = sense límit.', null=True),
        ),
    ]
