# Generated by Django 6.0.5 on 2026-09-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0053_ronda_fora_de_comanda_ronda_linia_comanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltask',
            name='hourly_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="A3: cost/hora propi d'aquesta tasca. null = fes servir TenantConfig.hourly_rate. Cost INTERN: mai viatja al client.", max_digits=10, null=True),
        ),
    ]
