# Generated by Django 6.0.5 on 2026-05-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitxerVersio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_original', models.CharField(max_length=255)),
                ('nom_intern', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('patro', 'Patró'), ('disseny', 'Disseny'), ('fitting', 'Fitting'), ('document', 'Document'), ('ia_output', 'Sortida IA')], max_length=20)),
                ('versio', models.PositiveIntegerField()),
                ('path_relatiu', models.CharField(max_length=500)),
                ('mida_bytes', models.BigIntegerField()),
                ('mimetype', models.CharField(max_length=100)),
                ('checksum', models.CharField(max_length=64)),
                ('origen', models.CharField(choices=[('upload', 'Pujada manual'), ('ia_escalat', 'IA · escalat'), ('ia_marcada', 'IA · marcatge'), ('ia_ocr', 'IA · OCR')], default='upload', max_length=30)),
                ('prompt_ia', models.TextField(blank=True, null=True)),
                ('model_ia', models.CharField(blank=True, max_length=100, null=True)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('accessible_portal', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitxer_versions', to='models_app.model')),
                ('pujat_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitxer_versions_pujats', to='accounts.userprofile')),
                ('versio_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_posteriors', to='files.fitxerversio')),
            ],
            options={
                'verbose_name': 'Versió de fitxer',
                'verbose_name_plural': 'Versions de fitxer',
                'ordering': ['-data_creacio'],
            },
        ),
    ]
