# Generated by Django 6.0.5 on 2026-05-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('referencia', models.CharField(blank=True, max_length=80)),
                ('data_inici', models.DateField(blank=True, null=True)),
                ('data_fi', models.DateField(blank=True, null=True)),
                ('actiu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contracte',
                'verbose_name_plural': 'Contractes',
            },
        ),
        migrations.CreateModel(
            name='LiniaContracte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.CharField(max_length=200)),
                ('quantitat', models.PositiveIntegerField(default=0)),
                ('actiu', models.BooleanField(default=True)),
                ('contracte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='models_app.contracte')),
            ],
            options={
                'verbose_name': 'Línia de contracte',
                'verbose_name_plural': 'Línies de contracte',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_intern', models.CharField(max_length=40, unique=True)),
                ('codi_client', models.CharField(max_length=80)),
                ('codi_tenant', models.CharField(max_length=3)),
                ('any', models.PositiveSmallIntegerField()),
                ('temporada', models.CharField(choices=[('SS', 'Spring/Summer'), ('FW', 'Fall/Winter'), ('CO', 'Cruise'), ('SP', 'Special')], max_length=4)),
                ('sequencial', models.PositiveIntegerField()),
                ('nom_prenda', models.CharField(max_length=200)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('color_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fit_type', models.CharField(choices=[('Regular', 'Regular'), ('Slim', 'Slim'), ('Relaxed', 'Relaxed'), ('Oversize', 'Oversize'), ('Tailored', 'Tailored')], default='Regular', max_length=20)),
                ('estat', models.CharField(choices=[('Nou', 'Nou'), ('EnCurs', 'En curs'), ('EnRevisio', 'En revisió'), ('Tancat', 'Tancat')], default='Nou', max_length=20)),
                ('fase_actual', models.CharField(choices=[('Proto', 'Proto'), ('Fit', 'Fit'), ('SizeSet', 'SizeSet'), ('PP', 'PP'), ('TOP', 'TOP')], default='Proto', max_length=20)),
                ('prioritat', models.PositiveSmallIntegerField(default=3)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('data_objectiu', models.DateField(blank=True, null=True)),
                ('data_tancament', models.DateField(blank=True, null=True)),
                ('observacions', models.TextField(blank=True, null=True)),
                ('contracte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='models_app.contracte')),
                ('garment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='pom.garmenttype')),
                ('grading_rule_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='pom.gradingruleset')),
                ('linia_contracte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='models_app.liniacontracte')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models_responsable', to='accounts.userprofile')),
                ('size_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='pom.sizesystem')),
                ('talla_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models_base', to='pom.sizedefinition')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='ModelFitxer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fitxer', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Patro', 'Patró'), ('Disseny', 'Disseny'), ('Fitting', 'Fitting'), ('Document', 'Document')], max_length=20)),
                ('versio', models.CharField(max_length=10)),
                ('path_servidor', models.CharField(max_length=500)),
                ('accessible_portal', models.BooleanField(default=False)),
                ('data_pujada', models.DateTimeField(auto_now_add=True)),
                ('mida_bytes', models.BigIntegerField()),
                ('enviat_ia', models.BooleanField(default=False)),
                ('resultat_ia_path', models.CharField(blank=True, max_length=500, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitxers', to='models_app.model')),
                ('pujat_per', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitxers_pujats', to='accounts.userprofile')),
                ('versio_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_posteriors', to='models_app.modelfitxer')),
            ],
            options={
                'verbose_name': 'Fitxer de model',
                'verbose_name_plural': 'Fitxers de model',
            },
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['codi_tenant', 'any', 'temporada'], name='models_app__codi_te_6d00a5_idx'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['estat', 'fase_actual'], name='models_app__estat_a04328_idx'),
        ),
    ]
