# Generated by Django 6.0.5 on 2026-05-25 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_responsable', to='accounts.userprofile'),
        ),
    ]
