# Generated by Django 6.0.5 on 2026-05-25 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_alter_model_responsable'),
        ('pom', '0002_garmentgroup_pomcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='size_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='pom.sizesystem'),
        ),
        migrations.AlterField(
            model_name='model',
            name='talla_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_base', to='pom.sizedefinition'),
        ),
    ]
