# Generated by Django 6.0.5 on 2026-05-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_alter_model_size_system_alter_model_talla_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='familia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='slots_prev_confeccio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='slots_prev_tecnics',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='slots_reals_confeccio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='slots_reals_tecnic',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
