# Generated by Django 6.0.5 on 2026-05-25 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_sprint1a_new_fields'),
        ('tasks', '0005_sprint1b_new_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfitxer',
            name='descripcio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelfitxer',
            name='fitxer',
            field=models.FileField(blank=True, null=True, upload_to='model_fitxers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='modelfitxer',
            name='url_extern',
            field=models.URLField(blank=True, help_text="URL externa si el fitxer no s'emmagatzema aquí", null=True),
        ),
        migrations.CreateModel(
            name='ModelServei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_servei', models.CharField(blank=True, max_length=200, null=True)),
                ('grup', models.CharField(blank=True, max_length=50, null=True)),
                ('slots_base', models.FloatField(blank=True, null=True)),
                ('contractat', models.BooleanField(default=True)),
                ('ampliat', models.BooleanField(default=False)),
                ('estat_autoritzacio', models.CharField(blank=True, choices=[('Pendent', 'Pendent'), ('Autoritzat', 'Autoritzat'), ('Rebutjat', 'Rebutjat')], max_length=20, null=True)),
                ('data_autoritzacio', models.DateTimeField(blank=True, null=True)),
                ('linia_addicional', models.CharField(blank=True, max_length=100, null=True)),
                ('autoritzat_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacions_servei', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serveis_model', to='models_app.model')),
                ('servei', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models_servei', to='tasks.paquetservei')),
            ],
            options={
                'verbose_name': 'Servei del model',
                'verbose_name_plural': 'Serveis del model',
                'ordering': ['servei__ordre_popup', 'id'],
            },
        ),
    ]
