# Generated by Django 6.0.5 on 2026-05-25 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_sprint1b_new_models'),
        ('pom', '0002_garmentgroup_pomcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value_cm', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_measurements', to='models_app.model')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_measurements', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Mesura base',
                'verbose_name_plural': 'Mesures base',
                'ordering': ['model', 'pom'],
                'unique_together': {('model', 'pom')},
            },
        ),
    ]
