# Generated by Django 6.0.5 on 2026-05-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_sprint3_4_grading_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='base_size_label',
            field=models.CharField(blank=True, help_text='Etiqueta de la talla base (ha de coincidir amb un valor de size_run_model)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='size_run_model',
            field=models.CharField(blank=True, help_text="Talles del model separades per · o ; (p.ex. 'XS·S·M·L·XL')", max_length=200, null=True),
        ),
    ]
