# Generated by Django 6.0.5 on 2026-05-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0007_sprint3_4_model_size_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='darrera_activitat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
