# Generated by Django 6.0.5 on 2026-05-26 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0008_model_darrera_activitat'),
        ('pom', '0003_sprint3_4_grading_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='garment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='pom.garmentgroup'),
        ),
        migrations.AddField(
            model_name='model',
            name='origen_patro',
            field=models.CharField(blank=True, choices=[('CAD Client', 'CAD Client'), ('Digitalització', 'Digitalització'), ('Des de zero', 'Des de zero')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='versio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
