# Generated by Django 6.0.5 on 2026-05-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0010_sprint7a_design_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemeasurement',
            name='nom_fitxa',
            field=models.CharField(blank=True, default='', help_text='Nomenclatura de la fletxa al croquis (ex: A, 1, CH). Per defecte: abbreviation del POMGlobal.', max_length=20),
        ),
        migrations.AddField(
            model_name='basemeasurement',
            name='origen',
            field=models.CharField(choices=[('STANDARD', 'Estàndard (carregat del RuleSet)'), ('IMPORTED', 'Importat de fitxa externa'), ('MANUAL', 'Introduït manualment'), ('FITTED', 'Modificat en fitting'), ('CALCULATED', 'Calculat des de talla base + delta')], default='STANDARD', max_length=20),
        ),
    ]
