# Generated by Django 6.0.5 on 2026-05-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0011_basemeasurement_nom_fitxa_basemeasurement_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='nom_prenda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
