# Generated by Django 6.0.5 on 2026-05-28 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0012_alter_model_nom_prenda'),
        ('pom', '0010_pommaster_pendent_revisio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='codi_client',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='model',
            name='garment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='pom.garmenttype'),
        ),
    ]
