# Generated by Django 6.0.5 on 2026-05-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0013_alter_model_codi_client_alter_model_garment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='construction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='target',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
