# Generated by Django 6.0.5 on 2026-05-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0014_model_construction_model_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basemeasurement',
            options={'ordering': ['model', 'ordre', 'pom'], 'verbose_name': 'Mesura base', 'verbose_name_plural': 'Mesures base'},
        ),
        migrations.AddField(
            model_name='basemeasurement',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
