# Generated by Django 6.0.5 on 2026-05-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0015_alter_basemeasurement_options_basemeasurement_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfitxer',
            name='tipus',
            field=models.CharField(blank=True, default='ALTRES', max_length=30),
        ),
    ]
