# Generated by Django 6.0.5 on 2026-05-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0016_modelfitxer_tipus'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='fabric_composition',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='model',
            name='fabric_main',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='model',
            name='fabric_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='model',
            name='shrinkage_pct',
            field=models.FloatField(blank=True, help_text='Encongiment únic (%) si no és biaxial', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='shrinkage_type',
            field=models.CharField(choices=[('NONE', 'No definit'), ('ISO', 'Estàndard ISO'), ('SUPPLIER', 'Fabricant'), ('CUSTOM', 'Personalitzat')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='model',
            name='shrinkage_warp',
            field=models.FloatField(blank=True, help_text='Encongiment ordit/warp (%)', null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='shrinkage_weft',
            field=models.FloatField(blank=True, help_text='Encongiment trama/weft (%)', null=True),
        ),
    ]
