# Generated by Django 6.0.5 on 2026-05-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0017_model_fabric_composition_model_fabric_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='talla_base',
        ),
    ]
