# Generated by Django 6.0.5 on 2026-05-30 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0018_remove_model_talla_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_base', models.CharField(max_length=40, unique=True)),
                ('nom_comercial', models.CharField(blank=True, default='', max_length=200)),
                ('num_pieces', models.PositiveSmallIntegerField(help_text='Nombre de peces del conjunt. Immutable després de la creació.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Garment Set (conjunt)',
                'verbose_name_plural': 'Garment Sets (conjunts)',
                'ordering': ['codi_base'],
            },
        ),
        migrations.AddField(
            model_name='model',
            name='piece_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='garment_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peces', to='models_app.garmentset'),
        ),
    ]
