# Generated by Django 6.0.5 on 2026-05-30 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0005_sprint_s11_pomalert_extra'),
        ('models_app', '0019_garmentset_model_piece_number_model_garment_set'),
        ('pom', '0010_pommaster_pendent_revisio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basemeasurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basemeasurement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_measurements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model',
            name='measurements_version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MeasurementChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.FloatField(blank=True, null=True)),
                ('valor_nou', models.FloatField()),
                ('motiu', models.CharField(blank=True, default='', max_length=255)),
                ('context', models.CharField(max_length=50)),
                ('fora_de_tolerancia', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_log', to='models_app.basemeasurement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_changes', to=settings.AUTH_USER_MODEL)),
                ('fitting_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_changes', to='fitting.sizefitting')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_changes', to='models_app.model')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_changes', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Canvi de mesura',
                'verbose_name_plural': 'Canvis de mesura',
                'ordering': ['model', 'pom', 'created_at'],
            },
        ),
    ]
