# Generated by Django 6.0.5 on 2026-05-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0020_basemeasurement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemeasurement',
            name='tolerancia_minus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='basemeasurement',
            name='tolerancia_plus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
