# Generated by Django 6.0.5 on 2026-05-30 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sprint_s1_foundations'),
        ('fitting', '0008_fittingsession_piecefitting_fittingphoto_and_more'),
        ('models_app', '0021_basemeasurement_tolerancia_minus_and_more'),
        ('pom', '0011_pommaster_tolerancia_default_minus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelGradingOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(max_length=20)),
                ('value_cm', models.FloatField()),
                ('motiu', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_overrides_created', to='accounts.userprofile')),
                ('fitting_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_overrides', to='fitting.piecefitting')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_overrides', to='models_app.model')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_grading_overrides', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Override de grading (model)',
                'verbose_name_plural': 'Overrides de grading (model)',
                'ordering': ['model', 'pom', 'size_label'],
                'unique_together': {('model', 'pom', 'size_label')},
            },
        ),
    ]
