# Generated by Django 6.0.5 on 2026-05-31 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0022_modelgradingoverride'),
        ('tasks', '0012_modeltask_estimated_minutes_garmenttypeitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='garment_type_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='tasks.garmenttypeitem'),
        ),
    ]
