# Generated by Django 6.0.5 on 2026-05-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0023_model_garment_type_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='predicted_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='predicted_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
