# Generated by Django 6.0.5 on 2026-06-02 13:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_jornada_override'),
        ('models_app', '0024_model_predicted_end_model_predicted_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='familia',
        ),
        migrations.AddField(
            model_name='model',
            name='collection',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 6, 2, 13, 45, 45, 902152, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models_created', to='accounts.userprofile'),
        ),
    ]
