# Generated by Django 6.0.5 on 2026-06-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0025_remove_model_familia_model_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='fase_actual',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dev', 'Dev'), ('Proto', 'Proto'), ('SizeSet', 'SizeSet'), ('PP', 'PP'), ('TOP', 'TOP')], default='Pending', max_length=20),
        ),
    ]
