# Generated by Django 6.0.5 on 2026-06-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0027_data_fit_to_proto'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemeasurement',
            name='is_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='basemeasurement',
            name='base_value_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basemeasurement',
            name='origen',
            field=models.CharField(choices=[('STANDARD', 'Estàndard (carregat del RuleSet)'), ('IMPORTED', 'Importat de fitxa externa'), ('MANUAL', 'Introduït manualment'), ('FITTED', 'Modificat en fitting'), ('CALCULATED', 'Calculat des de talla base + delta'), ('TEMPLATE', 'Materialitzat de plantilla (sense valor encara)')], default='STANDARD', max_length=20),
        ),
    ]
