# Generated by Django 6.0.5 on 2026-06-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0028_basemeasurement_is_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='shrinkage_iso_key',
            field=models.CharField(blank=True, default='', help_text='Teixit ISO triat (id de la taula ISO)', max_length=40),
        ),
    ]
