# Generated by Django 6.0.5 on 2026-06-04 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_jornada_override'),
        ('models_app', '0029_model_shrinkage_iso_key'),
        ('tasks', '0018_alter_modeltask_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_at', models.DateTimeField(auto_now=True)),
                ('estat', models.CharField(choices=[('INICI', 'Inici'), ('CRIBRATGE', 'Cribratge'), ('TALLES', 'Talles'), ('EXTRACCIO', 'Extracció'), ('POMS', 'POMs'), ('IMPORT', 'Import'), ('CONFIRMAT', 'Confirmat'), ('DESCARTAT', 'Descartat')], default='INICI', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='import_sessions/%Y/%m/')),
                ('model_detectat', models.JSONField(blank=True, default=dict)),
                ('run_conciliat', models.JSONField(blank=True, default=dict)),
                ('poms_extrets', models.JSONField(blank=True, default=list)),
                ('resultat', models.JSONField(blank=True, default=dict)),
                ('historia_xat', models.JSONField(blank=True, default=list)),
                ('avisos', models.JSONField(blank=True, default=list)),
                ('creat_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to='accounts.userprofile')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to='models_app.model')),
                ('tipologia_confirmada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.garmenttypeitem')),
            ],
            options={
                'ordering': ['-data_creacio'],
            },
        ),
    ]
