# Generated by Django 6.0.5 on 2026-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0030_importsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importsession',
            name='estat',
            field=models.CharField(choices=[('INICI', 'Inici'), ('CRIBRATGE', 'Cribratge'), ('TALLES', 'Talles'), ('EXTRACCIO', 'Extracció'), ('POMS', 'POMs'), ('MESURES', 'Mesures'), ('MESURES_OK', 'Mesures OK'), ('IMPORT', 'Import'), ('CONFIRMAT', 'Confirmat'), ('DESCARTAT', 'Descartat')], default='INICI', max_length=20),
        ),
    ]
