# Generated by Django 6.0.5 on 2026-06-04 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0031_alter_importsession_estat'),
        ('tasks', '0019_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='tasks.customer'),
        ),
    ]
