# Generated by Django 6.0.5 on 2026-06-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_jornada_override'),
        ('models_app', '0032_model_customer'),
        ('tasks', '0020_seed_self_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCollectionImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='bulk_imports/%Y/%m/')),
                ('estat', models.CharField(choices=[('PUJAT', 'Pujat'), ('VALIDANT', 'Validant'), ('PREVISAT', 'Previsat'), ('IMPORTAT', 'Importat'), ('DESCARTAT', 'Descartat')], default='PUJAT', max_length=20)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('resum', models.JSONField(blank=True, default=dict)),
                ('resultat', models.JSONField(blank=True, default=list)),
                ('creat_per', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_imports', to='accounts.userprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_imports', to='tasks.customer')),
            ],
            options={
                'verbose_name': 'Importació massiva',
                'verbose_name_plural': 'Importacions massives',
                'ordering': ['-creat_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkCollectionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.PositiveIntegerField(help_text='Número de fila al fitxer Excel')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('estat', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error'), ('AVIS', 'Avís'), ('DUPLICAT', 'Duplicat')], max_length=20)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('importacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='models_app.bulkcollectionimport')),
                ('model_creat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_rows', to='models_app.model')),
            ],
            options={
                'verbose_name': "Fila d'importació massiva",
                'verbose_name_plural': "Files d'importació massiva",
                'ordering': ['importacio', 'row_num'],
            },
        ),
        migrations.CreateModel(
            name='ModelSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('season', models.CharField(choices=[('SS', 'Spring/Summer'), ('FW', 'Fall/Winter'), ('CO', 'Cruise'), ('SP', 'Special')], max_length=4)),
                ('last_seq', models.PositiveIntegerField(default=0, help_text='Últim seqüencial reservat')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_sequences', to='tasks.customer')),
            ],
            options={
                'verbose_name': 'Seqüència de model',
                'verbose_name_plural': 'Seqüències de model',
                'unique_together': {('customer', 'year', 'season')},
            },
        ),
    ]
