# Generated by Django 6.0.5 on 2026-06-06 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0034_techsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='consumption_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snapshot', models.CharField(max_length=40)),
                ('name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('period', models.CharField(max_length=7)),
                ('opaque_ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('merited_at', models.DateTimeField()),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_record', to='models_app.model')),
            ],
            options={
                'ordering': ['-merited_at'],
            },
        ),
    ]
