# Generated by Django 6.0.5 on 2026-06-11 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0035_consumption_record_and_field'),
        ('tasks', '0020_seed_self_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechSheetTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, default='', max_length=120)),
                ('template_json', models.JSONField(blank=True, default=dict)),
                ('actiu', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_sheet_template', to='tasks.customer')),
            ],
            options={
                'verbose_name': 'Tech sheet template',
                'verbose_name_plural': 'Tech sheet templates',
            },
        ),
    ]
