# Generated by Django 6.0.5 on 2026-06-16 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0036_tech_sheet_template'),
        ('pom', '0022_gradingrule_increment_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelGradingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logica', models.CharField(choices=[('LINEAR', 'Linear'), ('STEP', 'Step'), ('FIXED', 'Fixed'), ('ZERO', 'Zero'), ('EXCEPTION', 'Exception')], max_length=20)),
                ('increment', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valors_step', models.JSONField(blank=True, null=True)),
                ('increment_base', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('increment_break', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('talla_break_label', models.CharField(blank=True, max_length=30, null=True)),
                ('talla_break_pos', models.IntegerField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('IMPORTED', 'Importat de fitxa externa'), ('CANONICAL', 'Derivat canònicament'), ('MANUAL', 'Introduït manualment')], default='CANONICAL', max_length=20)),
                ('actiu', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_rules', to='models_app.model')),
                ('pom', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='model_grading_rules', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Regla grading (model)',
                'verbose_name_plural': 'Regles grading (model)',
                'unique_together': {('model', 'pom')},
            },
        ),
    ]
