# Generated by Django 6.0.5 on 2026-06-16 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_jornada_override'),
        ('models_app', '0037_modelgradingrule'),
        ('pom', '0022_gradingrule_increment_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemeasurement',
            name='origen',
            field=models.CharField(choices=[('STANDARD', 'Estàndard (carregat del RuleSet)'), ('IMPORTED', 'Importat de fitxa externa'), ('MANUAL', 'Introduït manualment'), ('FITTED', 'Modificat en fitting'), ('CALCULATED', 'Calculat des de talla base + delta'), ('TEMPLATE', 'Materialitzat de plantilla (sense valor encara)'), ('CHECKED', 'Validat en size check (proto a talla base)')], default='STANDARD', max_length=20),
        ),
        migrations.CreateModel(
            name='SizeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estat', models.CharField(choices=[('Pendent', 'Pendent'), ('Acceptat', 'Acceptat'), ('Descartat', 'Descartat')], default='Pendent', max_length=10)),
                ('talla_base_label', models.CharField(max_length=20)),
                ('missatge_fabricant', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolt_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_checks_creats', to='accounts.userprofile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_checks', to='models_app.model')),
                ('resolt_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_checks_resolts', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Validació de talla',
                'verbose_name_plural': 'Validacions de talla',
                'ordering': ['model', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SizeCheckLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_teoric', models.FloatField()),
                ('valor_real', models.FloatField(blank=True, null=True)),
                ('acceptat', models.BooleanField(default=False)),
                ('nota', models.CharField(blank=True, default='', max_length=200)),
                ('pom', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pom.pommaster')),
                ('size_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='models_app.sizecheck')),
            ],
            options={
                'verbose_name': 'Línia de validació de talla',
                'verbose_name_plural': 'Línies de validació de talla',
                'ordering': ['size_check', 'pom'],
                'unique_together': {('size_check', 'pom')},
            },
        ),
    ]
