# Generated by Django 6.0.5 on 2026-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0038_sizecheck_sizecheckline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizecheckline',
            name='acceptat',
        ),
        migrations.AddField(
            model_name='sizecheckline',
            name='decisio',
            field=models.CharField(blank=True, choices=[('tolerancia_acceptada', 'Tolerància acceptada'), ('valor_descartat', 'Valor descartat')], max_length=24, null=True),
        ),
    ]
