# Generated by Django 6.0.5 on 2026-06-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0039_sizecheckline_decisio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizecheck',
            name='estat',
            field=models.CharField(choices=[('Pendent', 'Pendent'), ('Acceptat', 'Acceptat'), ('Rebutjat', 'Rebutjat'), ('Descartat', 'Descartat')], default='Pendent', max_length=10),
        ),
    ]
