# Generated by Django 6.0.5 on 2026-06-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0040_sizecheck_estat_rebutjat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemeasurement',
            name='origen',
            field=models.CharField(choices=[('STANDARD', 'Estàndard (carregat del RuleSet)'), ('IMPORTED', 'Importat de fitxa externa'), ('MANUAL', 'Introduït manualment'), ('FITTED', 'Modificat en fitting'), ('CALCULATED', 'Calculat des de talla base + delta'), ('TEMPLATE', 'Materialitzat de plantilla (sense valor encara)'), ('CHECKED', 'Validat en size check (proto a talla base)'), ('ITEM_STANDARD', "Sembrat de l'estàndard de l'item (copy-at-the-moment)")], default='STANDARD', max_length=20),
        ),
    ]
