# Generated by Django 6.0.5 on 2026-06-23 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_jornada_override'),
        ('models_app', '0041_alter_basemeasurement_origen'),
        ('tasks', '0023_garmenttypeitem_grading_rule_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('estat', models.CharField(choices=[('open', 'Oberta'), ('resolved', 'Resolta')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchpoints_creats', to='accounts.userprofile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchpoints', to='models_app.model')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchpoints_resolts', to='accounts.userprofile')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchpoints', to='tasks.modeltask')),
            ],
            options={
                'verbose_name': 'Watchpoint',
                'verbose_name_plural': 'Watchpoints',
                'ordering': ['-created_at'],
            },
        ),
    ]
