# Generated by Django 6.0.5 on 2026-06-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0042_watchpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelServei',
        ),
    ]
