# Generated by Django 6.0.5 on 2026-06-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0043_delete_modelservei'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchpoint',
            name='dades',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
