# Generated by Django 6.0.5 on 2026-06-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0045_modelfitxer_versionat_invariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('descripcio', models.TextField(blank=True, default='')),
                ('fitxer_template', models.FileField(blank=True, null=True, upload_to='document_templates/%Y/%m/')),
                ('metadata_schema', models.JSONField(blank=True, default=dict)),
                ('is_sample', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('sistema', 'Mostra del sistema'), ('tenant', 'Creada al tenant')], default='tenant', max_length=20)),
                ('actiu', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
