# Generated by Django 6.0.5 on 2026-06-27 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0046_documenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfitxer',
            name='generat_des_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports_generats', to='models_app.modelfitxer'),
        ),
    ]
