# Generated by Django 6.0.5 on 2026-06-27 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0047_modelfitxer_generat_des_de'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FttDocumentLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('document_root', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ftt_lock', to='models_app.modelfitxer')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ftt_documents_locked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
