# Generated by Django 6.0.5 on 2026-06-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0048_fttdocumentlock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techsheet',
            name='estat',
        ),
    ]
