# Generated by Django 6.0.5 on 2026-06-27 17:18
from django.db import migrations


def migrate_remaining_techsheets(apps, schema_editor):
    """Idempotent: migra qualsevol TechSheet amb contingut v2 que encara NO tingui .ftt, just
    abans de fer el drop del model. A staging ja estava migrat (no-op); això protegeix PROD: el
    deploy migra-i-després-elimina de manera atòmica per tenant, sense perdre dades.

    Llegeix el TechSheet via el model històric (apps), i escriu el .ftt amb els serveis REALS
    (create_document → save_model_file, invariant is_current), inalterats per aquesta migració.
    """
    HistTechSheet = apps.get_model('models_app', 'TechSheet')
    from fhort.models_app.models import Model, ModelFitxer
    from fhort.models_app import services_ftt, services_ftt_document

    for sheet in HistTechSheet.objects.all():
        tj = sheet.template_json or {}
        if not (tj.get('version') == 2 and isinstance(tj.get('pages'), list) and tj.get('pages')):
            continue
        if ModelFitxer.objects.filter(model_id=sheet.model_id, tipus='TECHSHEET').exists():
            continue
        model = Model.objects.get(pk=sheet.model_id)
        meta = {
            'reference': model.codi_intern,
            'description': getattr(model, 'descripcio', '') or '',
            'season': getattr(model, 'temporada', '') or '',
        }
        document_json, assets = services_ftt.v2_to_document(tj, metadata=meta)
        services_ftt_document.create_document(model, document_json=document_json, assets=assets)


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0049_remove_techsheet_estat'),
    ]

    operations = [
        migrations.RunPython(migrate_remaining_techsheets, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='TechSheet',
        ),
    ]
