# Generated by Django 6.0.5 on 2026-07-06 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_jornada_override'),
        ('models_app', '0050_delete_techsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_templates_created', to='accounts.userprofile'),
        ),
    ]
