# Generated by Django 6.0.5 on 2026-07-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0051_documenttemplate_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfitxer',
            name='path_servidor',
        ),
    ]
