# Generated by Django 6.0.5 on 2026-07-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0052_remove_modelfitxer_path_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfitxer',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Patro', 'Patró'), ('Disseny', 'Disseny'), ('Fitting', 'Fitting'), ('Document', 'Document')], max_length=20),
        ),
        migrations.AlterField(
            model_name='modelfitxer',
            name='tipus',
            field=models.CharField(blank=True, choices=[('ALTRES', 'Altres'), ('DOCUMENT', 'Document'), ('TECHSHEET', 'Fitxa tècnica (.ftt)'), ('EXPORT', "PDF d'export"), ('PATRO', 'Patró'), ('ESCALAT', 'Escalat'), ('SKETCH_FLETXES', 'Sketch amb fletxes'), ('SKETCH_NET', 'Sketch net'), ('SKETCH_SVG', 'Sketch SVG'), ('MARCADA', 'Marcada'), ('RUL', 'RUL')], default='ALTRES', max_length=30),
        ),
    ]
