# Generated by Django 6.0.5 on 2026-07-09 18:54

import django.db.models.deletion
import fhort.models_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tenantconfig_address_tenantconfig_city_and_more'),
        ('models_app', '0053_modelfitxer_tipus_choices'),
        ('tasks', '0037_modeltask_off_recipe_modeltask_work_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFitxer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fitxer', models.CharField(max_length=255)),
                ('tipus', models.CharField(blank=True, choices=[('ALTRES', 'Altres'), ('DOCUMENT', 'Document'), ('TECHSHEET', 'Fitxa tècnica (.ftt)'), ('EXPORT', "PDF d'export"), ('PATRO', 'Patró'), ('ESCALAT', 'Escalat'), ('SKETCH_FLETXES', 'Sketch amb fletxes'), ('SKETCH_NET', 'Sketch net'), ('SKETCH_SVG', 'Sketch SVG'), ('MARCADA', 'Marcada'), ('RUL', 'RUL')], default='ALTRES', max_length=30)),
                ('versio', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('data_pujada', models.DateTimeField(auto_now_add=True)),
                ('mida_bytes', models.BigIntegerField()),
                ('fitxer', models.FileField(blank=True, null=True, upload_to=fhort.models_app.models.item_fitxer_upload_to)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('mimetype', models.CharField(blank=True, max_length=100)),
                ('garment_type_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitxers', to='tasks.garmenttypeitem')),
                ('pujat_per', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_fitxers_pujats', to='accounts.userprofile')),
                ('versio_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_posteriors', to='models_app.itemfitxer')),
            ],
            options={
                'verbose_name': 'Fitxer de catàleg (item)',
                'verbose_name_plural': 'Fitxers de catàleg (item)',
            },
        ),
    ]
