# Generated by Django 6.0.5 on 2026-07-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0054_itemfitxer'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfitxer',
            name='derivat_de_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_a_models', to='models_app.itemfitxer'),
        ),
    ]
