# Generated by Django 6.0.5 on 2026-07-10 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0055_modelfitxer_derivat_de_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfitxer',
            name='derivat_de_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivats', to='models_app.modelfitxer'),
        ),
    ]
