# Generated by Django 6.0.5 on 2026-07-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0056_modelfitxer_derivat_de_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='reanchored_by_start',
            field=models.BooleanField(default=False),
        ),
    ]
