# Generated by Django 6.0.5 on 2026-07-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0057_model_reanchored_by_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelgradingrule',
            name='origen',
            field=models.CharField(choices=[('IMPORTED', 'Importat de fitxa externa'), ('CANONICAL', 'Derivat canònicament'), ('CLIENT_RUN', 'Derivat de run de client'), ('MANUAL', 'Introduït manualment')], default='CANONICAL', max_length=20),
        ),
    ]
