# Generated by Django 6.0.5 on 2026-07-22 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tenantconfig_legal_footer'),
        ('models_app', '0058_alter_modelgradingrule_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cami', models.CharField(choices=[('cribratge', 'Cribratge'), ('revisio', 'Revisió'), ('extraccio', 'Extracció'), ('fallback', 'Fallback')], db_index=True, max_length=20)),
                ('model_ia', models.CharField(help_text="Model d'Anthropic (p.ex. claude-opus-4-7)", max_length=80)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cache_creation_tokens', models.IntegerField(default=0)),
                ('cache_read_tokens', models.IntegerField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to='accounts.userprofile')),
                ('import_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to='models_app.importsession')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to='models_app.model')),
            ],
            options={
                'verbose_name': "Ús d'IA",
                'verbose_name_plural': "Usos d'IA",
                'ordering': ['-created_at'],
            },
        ),
    ]
