# Generated by Django 6.0.5 on 2026-07-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0059_aiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='origen',
            field=models.CharField(choices=[('INTERN', 'Intern'), ('EXTERN', 'Extern')], db_index=True, default='INTERN', max_length=20),
        ),
    ]
