# Generated by Django 6.0.5 on 2026-07-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0060_model_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='studio_assignat',
            field=models.CharField(blank=True, db_index=True, default='', max_length=3),
        ),
    ]
