# Generated by Django 6.0.5 on 2026-07-26 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tenantconfig_legal_footer'),
        ('models_app', '0061_model_studio_assignat'),
        ('pom', '0050_itembasemeasurement_key_base_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='POMPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_slot', models.SlugField(max_length=40)),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('label_dx', models.FloatField(default=0)),
                ('label_dy', models.FloatField(default=0)),
                ('source_kind', models.CharField(choices=[('vector', 'Vector'), ('raster', 'Ràster')], default='vector', max_length=8)),
                ('creat_el', models.DateTimeField(auto_now_add=True)),
                ('actualitzat_el', models.DateTimeField(auto_now=True)),
                ('creat_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pom_placements_creats', to='accounts.userprofile')),
                ('item_fitxer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pom_placements', to='models_app.itemfitxer')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Col·locació de cota POM (precedent)',
                'verbose_name_plural': 'Col·locacions de cota POM (precedent)',
                'indexes': [models.Index(fields=['item_fitxer', 'view_slot'], name='idx_pomplacement_item_view')],
                'constraints': [models.UniqueConstraint(fields=('item_fitxer', 'pom', 'view_slot'), name='uniq_pomplacement_item_pom_view')],
            },
        ),
    ]
