# Generated by Django 6.0.5 on 2026-07-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0062_pomplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusage',
            name='n_proposades',
            field=models.IntegerField(blank=True, help_text='F3: cotes proposades en aquesta crida', null=True),
        ),
        migrations.AddField(
            model_name='aiusage',
            name='n_skip',
            field=models.IntegerField(blank=True, help_text='F3: POMs omesos (la IA no ho ha vist clar)', null=True),
        ),
        migrations.AlterField(
            model_name='aiusage',
            name='cami',
            field=models.CharField(choices=[('cribratge', 'Cribratge'), ('revisio', 'Revisió'), ('extraccio', 'Extracció'), ('fallback', 'Fallback'), ('proposta_cotes', 'Proposta de cotes (IA visió · F3)')], db_index=True, max_length=20),
        ),
    ]
