# Generated by Django 6.0.5 on 2026-07-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0063_aiusage_n_proposades_aiusage_n_skip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemeasurement',
            name='origen',
            field=models.CharField(choices=[('STANDARD', 'Estàndard (carregat del RuleSet)'), ('IMPORTED', 'Importat de fitxa externa'), ('MANUAL', 'Introduït manualment'), ('FITTED', 'Modificat en fitting'), ('CALCULATED', 'Calculat des de talla base + delta'), ('TEMPLATE', 'Materialitzat de plantilla (sense valor encara)'), ('CHECKED', 'Validat en size check (proto a talla base)'), ('ITEM_STANDARD', "Sembrat de l'estàndard de l'item (copy-at-the-moment)"), ('COPIED', "Copiat d'un altre model")], default='STANDARD', max_length=20),
        ),
    ]
