# Generated by Django 6.0.5 on 2026-07-27 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0064_basemeasurement_origen_copied'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionrecord',
            name='garment_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_record', to='models_app.garmentset'),
        ),
        migrations.AddField(
            model_name='garmentset',
            name='consumption_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_record', to='models_app.model'),
        ),
        migrations.AddConstraint(
            model_name='consumptionrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('garment_set__isnull', True), ('model__isnull', False)), models.Q(('garment_set__isnull', False), ('model__isnull', True)), _connector='OR'), name='consumptionrecord_model_xor_set'),
        ),
    ]
