# Generated by Django 6.0.5 on 2026-07-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0065_set1_meritacio_conjunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='federacio_estat',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
