# Generated by Django 6.0.5 on 2026-07-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0066_federacio_estat'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemeasurement',
            name='seccio',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
