# Generated by Django 6.0.5 on 2026-07-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0067_basemeasurement_seccio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemeasurement',
            name='origen',
            field=models.CharField(choices=[('STANDARD', 'Estàndard (carregat del RuleSet)'), ('IMPORTED', 'Importat de fitxa externa'), ('MANUAL', 'Introduït manualment'), ('FITTED', 'Modificat en fitting'), ('CALCULATED', 'Calculat des de talla base + delta'), ('TEMPLATE', 'Materialitzat de plantilla (sense valor encara)'), ('CHECKED', 'Validat en size check (proto a talla base)'), ('ITEM_STANDARD', "Sembrat de l'estàndard de l'item (copy-at-the-moment)"), ('COPIED', "Copiat d'un altre model"), ('FEDERAT', "Arribat de l'altra casa (federació)")], default='STANDARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelgradingrule',
            name='origen',
            field=models.CharField(choices=[('IMPORTED', 'Importat de fitxa externa'), ('CANONICAL', 'Derivat canònicament'), ('CLIENT_RUN', 'Derivat de run de client'), ('MANUAL', 'Introduït manualment'), ('FEDERAT', "Arribat de l'altra casa (federació)")], default='CANONICAL', max_length=20),
        ),
    ]
