# Generated by Django 6.0.5 on 2026-07-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0068_federat_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemeasurement',
            name='nom_canonic_model',
            field=models.CharField(blank=True, default='', help_text='Nom canònic (EN) amb què AQUEST model anomena la mesura. Buit: mana el catàleg (POMGlobal.nom_en).', max_length=160),
        ),
        migrations.AddField(
            model_name='basemeasurement',
            name='nom_traduit_model',
            field=models.CharField(blank=True, default='', help_text="Traducció del nom que fa servir el client d'aquest model. Buit: mana el catàleg (POMGlobal.nom_ca / POMMaster.nom_client).", max_length=160),
        ),
    ]
