# Generated by Django 6.0.5 on 2026-08-07 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0078_c4_g3_retira_comportes'),
        ('pom', '0063_n1_classifica_tipus_escala'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelgradingrule',
            name='derivat_de_rule_set',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Joc del qual es va materialitzar aquesta fila. NULL = autoria de pantalla, federació, o fila anterior a M3 (sense backfill: no es pot saber).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regles_residents_derivades', to='pom.gradingruleset'),
        ),
    ]
