# Generated by Django 6.0.5 on 2026-08-10 08:58

from django.conf import settings
"""SET-2/T2 — les unicitats de `models_app` incorporen el GARMENT, i les comportes el tanquen.

Fa en una sola migració el que la capa va fer en dues (`0071` + `0072`), pel mateix motiu
que ja va donar `0074` per a la instància: **obrir la clau i tancar-la alhora és una sola
decisió**. La parella de `fitting` és `fitting/0026`.

**LES CLAUS.** Mateix argument de seguretat per tercera vegada: la clau nova són les
mateixes columnes **més una**, o sigui estrictament més permissiva, i avui `garment` és
constant ('') a totes les files → 0 duplicats latents possibles. No pot rebutjar res que
abans passés ni deixar entrar cap duplicat que abans es barrés.
  · `BaseMeasurement`      → ('model','pom','capa','instancia','garment')
  · `ModelGradingOverride` → ('model','pom','size_label','capa','instancia','garment')
  · `SizeCheckLine`        → ('size_check','pom','capa','instancia','garment')

**CAP CONSTRAINT AMB NOM A RETIRAR I TORNAR A POSAR.** El pas de «Remove + Add amb el nom
que creix» que van necessitar `0071` i `0074` era NOMÉS per a `POMPlacement`, l'única taula
de la família que fa servir un `UniqueConstraint` amb nom en comptes d'`unique_together`.
`POMPlacement` queda fora d'aquesta onada per categoria (v. `0080`), o sigui que aquí el
pas és buit **per absència de subjecte, no per oblit**.

**LES COMPORTES `*_garment_gate_set2`.** Quatre, una per taula de `0080`. Mateixa bastida
que les de capa i instància, amb l'eix nou: la cadena de lectors encara indexa per
`(pom_id, capa, instancia)` i una segona peça escrita per accident abans de T4/T5 no
petaria enlloc — es fondria dins les llistes com la mare.

🔑 **QUÈ HA D'ESTAR VERD ABANS DE RETIRAR-LES** (invariant d'aquest sprint, i no és una
data sinó una condició): el test de R3. `germanes_de` (`services_derivacio.py:72-78`)
filtra per `(model, pom)` + «un eix diferent» i ESCRIU a les germanes (`aplica()`, :124,
invocada des de `services_size_check.py:255-257`). Amb dues peces i el filtre curt, dues
files amb la mateixa capa i instància passarien **les dues** branques de la `Q` → corregir
el pit del top mouria el de la calceta, amb el mateix valor i en silenci. Mentre la
comporta visqui, cap '02' pot existir i el filtre de R3 és un no-op.

APLICACIÓ SEGURA: auditat per SQL abans d'aplicar — el 100% de les files tenen
`garment = ''` (default de columna de `0080`) als schemes `fhort` i `los`: 29 + 39 + 0 + 28
files a `models_app`, cap NULL. La validació que Postgres fa en crear cada CHECK no pot
fallar.

⚠️ `ModelGradingRule` no hi és: la seva clau creix al seu propi tram (T3, decisió D4).
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tenantconfig_legal_footer'),
        ('fitting', '0026_set2_t2_garment_unicitats_comportes'),
        ('models_app', '0080_set2_t2_garment_columna'),
        ('pom', '0075_pommaster_codi_client_unic_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basemeasurement',
            unique_together={('model', 'pom', 'capa', 'instancia', 'garment')},
        ),
        migrations.AlterUniqueTogether(
            name='modelgradingoverride',
            unique_together={('model', 'pom', 'size_label', 'capa', 'instancia', 'garment')},
        ),
        migrations.AlterUniqueTogether(
            name='sizecheckline',
            unique_together={('size_check', 'pom', 'capa', 'instancia', 'garment')},
        ),
        migrations.AddConstraint(
            model_name='basemeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('garment', '')), name='models_app_basemeasurement_garment_gate_set2'),
        ),
        migrations.AddConstraint(
            model_name='measurementchangelog',
            constraint=models.CheckConstraint(condition=models.Q(('garment', '')), name='models_app_measurementchangelog_garment_gate_set2'),
        ),
        migrations.AddConstraint(
            model_name='modelgradingoverride',
            constraint=models.CheckConstraint(condition=models.Q(('garment', '')), name='models_app_modelgradingoverride_garment_gate_set2'),
        ),
        migrations.AddConstraint(
            model_name='sizecheckline',
            constraint=models.CheckConstraint(condition=models.Q(('garment', '')), name='models_app_sizecheckline_garment_gate_set2'),
        ),
    ]
