# Generated by Django 6.0.5 on 2026-08-10 10:08

"""SET-2/T3 — LA MURALLA S'OBRE: `ModelGradingRule` travessa el `garment` (i només ell).

`unique_together` passa de `('model','pom')` a `('model','pom','garment')`. És l'ÚNICA clau
del sistema que s'havia declarat explícitament que NO creixeria, amb acta de domini datada
(`models.py`, docstring de la classe) i dos tests que la vigilaven — o sigui que això és una
**reobertura conscient**, autoritzada per l'Agus (D4, 2026-08-10), i no un descuit.

EL MOTIU, I PER QUÈ NO DESMENTEIX L'ACTA. L'acta de la Montse diu «la sisa dreta i l'esquerra
gradúen igual» i parla de **germanes DINS d'una mateixa peça**: segueix sent certa paraula per
paraula. El que no diu —perquè quan es va escriure un model era una sola prenda— és que un top
i una calceta hagin de graduar igual. I no ho fan: una peça pot tenir el seu propi
`grading_rule_set` (D5), i un top per talla alfa amb una calceta per mesos són dues lleis
d'increments que ni tan sols parlen el mateix idioma de talles.

LA DISTINCIÓ QUE HO GOVERNA TOT: `capa` i `instancia` són **eixos de germanor** (dues cares de
la mateixa mesura → una sola llei) i per això NO entren aquí; `garment` és una **frontera**
(dues prendes → dues lleis possibles) i per això SÍ. La col·lecció canònica dels eixos de
germanor viu a `services_derivacio.EIXOS_DE_GERMANOR` i és la que llegeixen els pins.

L'ORDRE DE LES OPERACIONS el fixa Django i és el correcte: buida la clau vella ABANS d'afegir
la columna (una clau no pot referenciar una columna que encara no existeix) i la torna a posar
completa després. Les tres operacions cauen dins de la MATEIXA transacció, o sigui que la
finestra sense unicitat no és observable des de fora.

LA COMPORTA `..._garment_gate_set2` tanca una finestra que aquí és més estreta i més perillosa
que la de T2: `_load_grading_rules` (`pom/services.py:749`) indexa `{r.pom_id: r}`, un escalar
SENSE cap eix. Amb dues peces que compartissin un POM, la segona regla no petaria — **en
sobreescriuria la primera en memòria** i el motor graduaria tota una peça amb la llei de
l'altra, sense un sol log. **T4 és qui ensenya al motor a distingir-les**; fins llavors, aquí
no hi pot haver cap '02'.

LA SEMBRA, que és el que petava abans d'arribar-hi (`services.py`): el wipe era per MODEL
—sembrar la calceta esborrava les regles del top— i el `bulk_create` indexava per `pom_id` sol,
sense conflict-handling. Totes dues coses passen a `(model, garment)` en aquest mateix tram.

BACKFILL: cap (fast-default de PG11+). Auditat abans d'aplicar: **142 files a `fhort`** (les
del catàleg canònic de la sembra v4) i 0 a `los`. Totes reben `garment = ''` pel default del
`ADD COLUMN`, o sigui que la clau nova és estrictament més permissiva —mateixes columnes + una
amb valor constant: cap de les 142 pot xocar amb una altra— i la validació que Postgres fa en
crear el CHECK no pot fallar. Verificat per SQL, no assumit.

⚠️ `pom.GradingRule` NO es toca i el seu pin es REFORÇA: un ruleset és una llei reutilitzable
del catàleg, mai propietat d'un model, i no pot portar cap eix de model.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0081_set2_t2_garment_unicitats_comportes'),
        ('pom', '0075_pommaster_codi_client_unic_ci'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelgradingrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='modelgradingrule',
            name='garment',
            field=models.CharField(db_index=True, default='', help_text="Peça (garment) dins del model: codi de ModelGarment ('02', '03'…). '' és la peça mare, que és el Model mateix. Fins a la retirada de la comporta només s'admet '' (comporta CHECK a BD).", max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='modelgradingrule',
            unique_together={('model', 'pom', 'garment')},
        ),
        migrations.AddConstraint(
            model_name='modelgradingrule',
            constraint=models.CheckConstraint(condition=models.Q(('garment', '')), name='models_app_modelgradingrule_garment_gate_set2'),
        ),
    ]
