# Generated by Django 6.0.5 on 2026-08-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0082_set2_t3_modelgradingrule_garment'),
        ('pom', '0075_pommaster_codi_client_unic_ci'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelGarment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(help_text="Codi de la peça dins del model ('02', '03'…). Mai '': la peça mare és el model mateix i no té fila (D3).", max_length=20)),
                ('nom', models.CharField(blank=True, default='', help_text='Bateig del tècnic («Pantaló», «Caputxa»). Buit = encara sense batejar.', max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Ordre de presentació dins del model.')),
                ('size_run_model', models.CharField(blank=True, max_length=200, null=True)),
                ('base_size_label', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grading_rule_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garments_override', to='pom.gradingruleset')),
                ('model', models.ForeignKey(help_text='El model del qual aquesta peça forma part.', on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='models_app.model')),
                ('size_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garments_override', to='pom.sizesystem')),
            ],
            options={
                'verbose_name': 'Peça de model',
                'verbose_name_plural': 'Peces de model',
                'ordering': ['model_id', 'ordre', 'codi'],
                'constraints': [models.CheckConstraint(condition=models.Q(('codi', ''), _negated=True), name='models_app_modelgarment_codi_no_buit')],
                'unique_together': {('model', 'codi')},
            },
        ),
    ]
