# Generated by Django 6.0.5 on 2026-08-12 09:34

"""SET-2/#12 — LA MURALLA CAU: `garment` deixa de ser una columna congelada.

Retira les CINC comportes `*_garment_gate_set2` d'aquesta app —quatre de T2 (`0081`:
BaseMeasurement, MeasurementChangeLog, ModelGradingOverride, SizeCheckLine) i la de T3
(`0082`: ModelGradingRule)—. Les dues germanes de `fitting` cauen a `fitting/0027`, dins
de la mateixa onada i **no per separat**: v. l'apartat de l'encadenament, més avall.

**PER QUÈ ARA I NO ABANS.** Les comportes no eren una precaució genèrica: cadascuna tenia
escrit al seu costat què havia d'estar verd per poder-la treure, i el gate era el CODI, no
la data. Els tres deutes que les sostenien estan pagats i verificats un per un:

- **T4 · el motor.** `_load_grading_rules_per_garment` (`pom/services.py:820`) retorna
  `{(pom_id, garment): rule}`. Amb l'índex escalar de T3, dues peces que compartissin un
  POM no petaven: la segona regla **sobreescrivia la primera en memòria** i el motor
  graduava una peça sencera amb la llei de l'altra, sense un sol log.
- **T5 · els escriptors.** Les portes d'escriptura passen el `garment` avall en comptes
  d'assumir la prenda única.
- **R3 · les germanes.** `germanes_de` (`services_derivacio.py`) filtra per l'eix sencer
  (`EIXOS_DE_GERMANOR`), o sigui que corregir el pit del top ja no pot moure el de la
  calceta —el bug de creuament silenciós que la comporta de `BaseMeasurement` existia
  exactament per fer impossible.

**LA PROVA.** Suite sencera verda el 12/08 abans de tocar res: `Ran 1841 tests · OK`,
0 FAIL / 0 ERROR, i `manage.py check` net. Autoritzat per l'Agus sobre aquell verd.

**QUÈ NO ES TOCA.** `models_app_modelgarment_codi_no_buit` (D3, `0083`) es queda. No és una
comporta de transició: és una llei de domini permanent —una peça sense codi no és una peça—
i sobreviu a aquest tram. Qui audiți després de migrar ha de veure-la VIVA; si desapareix,
alguna cosa ha anat malament.

**REVERSIBILITAT, i el seu límit.** `RemoveConstraint` sap desfer-se sola i Django tornaria
a posar els CHECK. Però un `migrate` enrere només tornarà a passar **mentre no existeixi cap
fila amb `garment <> ''`**: en el moment que hi hagi dades multipeça reals, Postgres validarà
el CHECK contra les files i la reversió petarà. A partir d'aquí el camí enrere no és una
migració: és el backup (`backups/ftt_staging_pre_retirada_comportes_20260812T0900Z.dump`).

**BACKFILL: cap.** Això només DEIXA CAURE restriccions; no toca ni una fila. Les columnes
`garment` ja existien (T2, `0080`/`0081`) amb default `''`, o sigui que l'estat de les dades
just després d'aquesta migració és idèntic al de just abans: el que canvia és què s'hi podrà
escriure a partir d'ara.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0083_set2_t2bis_modelgarment'),
        # L'ORDRE ÉS PART DE LA PEÇA: les comportes de `fitting` s'obren ABANS que les
        # d'aquí. Escriure una mesura base encadena cap al motor, que escriu els specs dins
        # de la mateixa crida: amb la mesura oberta i l'spec encara tancat, la finestra entre
        # les dues migracions admetria una escriptura que petaria amb `CheckViolation`
        # (l'incident de `959147a5`). V. la capçalera de `fitting/0027`.
        ('fitting', '0027_set2_12_retirada_comportes_garment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='basemeasurement',
            name='models_app_basemeasurement_garment_gate_set2',
        ),
        migrations.RemoveConstraint(
            model_name='measurementchangelog',
            name='models_app_measurementchangelog_garment_gate_set2',
        ),
        migrations.RemoveConstraint(
            model_name='modelgradingoverride',
            name='models_app_modelgradingoverride_garment_gate_set2',
        ),
        migrations.RemoveConstraint(
            model_name='modelgradingrule',
            name='models_app_modelgradingrule_garment_gate_set2',
        ),
        migrations.RemoveConstraint(
            model_name='sizecheckline',
            name='models_app_sizecheckline_garment_gate_set2',
        ),
    ]
