# Generated by Django 6.0.5 on 2026-08-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0084_set2_12_retirada_comportes_garment'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='garment',
            field=models.CharField(blank=True, default='', help_text="Peça de destí de l'import: codi de ModelGarment ('02', '03'…). '' és la peça mare, que és el Model mateix.", max_length=20),
        ),
    ]
