# Generated by Django 6.0.5 on 2026-09-23 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0029_fittingsisterdecision_consentiment_germanes'),
        ('models_app', '0087_m3_cicle_vida_model'),
        ('pom', '0088_alies_unicitat_amb_pom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInstanceOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.CharField(db_index=True, default='exterior', help_text="Capa de mesura: slug de pom.MeasurementLayer. FIXA per a la parella —aquesta taula és només per a l'eix d'INSTÀNCIA (mateixa capa).", max_length=20)),
                ('instancia_origen', models.CharField(max_length=60)),
                ('instancia_desti', models.CharField(max_length=60)),
                ('delta', models.FloatField(help_text='instancia_desti.valor − instancia_origen.valor, en cm.')),
                ('origen', models.CharField(choices=[('FITTING', 'Confirmat en un fitting (consentiment de germanes)')], default='FITTING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_instance_offsets_creats', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_offsets', to='models_app.model')),
                ('piece_fitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_offsets_confirmats', to='fitting.piecefitting')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_instance_offsets', to='pom.pommaster')),
            ],
            options={
                'verbose_name': "Relació d'instàncies del model (folgança confirmada)",
                'verbose_name_plural': "Relacions d'instàncies del model (folgança confirmada)",
                'ordering': ['model', 'pom', 'capa', 'instancia_origen', 'instancia_desti'],
                'constraints': [models.UniqueConstraint(fields=('model', 'pom', 'capa', 'instancia_origen', 'instancia_desti'), name='modelinstanceoffset_unic_per_parella_direccional')],
            },
        ),
    ]
