# Generated by Django 6.0.5 on 2026-05-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('models_app', '0001_initial'),
        ('pom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(max_length=40)),
                ('descripcio', models.TextField()),
                ('estat', models.CharField(choices=[('Pendent', 'Pendent'), ('Aplicat', 'Aplicat'), ('Rebutjat', 'Rebutjat')], default='Pendent', max_length=20)),
            ],
            options={
                'verbose_name': 'Comentari de fitting',
                'verbose_name_plural': 'Comentaris de fitting',
            },
        ),
        migrations.CreateModel(
            name='FitCommentFitxer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_servidor', models.CharField(max_length=500)),
                ('nom_fitxer', models.CharField(max_length=255)),
                ('data_pujada', models.DateTimeField(auto_now_add=True)),
                ('fit_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitxers', to='fitting.fitcomment')),
            ],
            options={
                'verbose_name': 'Fitxer de comentari',
                'verbose_name_plural': 'Fitxers de comentari',
            },
        ),
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('tipus', models.CharField(choices=[('Proto', 'Proto'), ('Sample', 'Sample'), ('PPS', 'PPS')], max_length=20)),
                ('data_fitting', models.DateField()),
                ('lloc', models.CharField(blank=True, max_length=200, null=True)),
                ('estat', models.CharField(choices=[('Pendent', 'Pendent'), ('Aprovat', 'Aprovat'), ('AmbCorreccions', 'Amb correccions'), ('Rebutjat', 'Rebutjat')], default='Pendent', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fittings_responsable', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Fitting',
                'verbose_name_plural': 'Fittings',
                'ordering': ['size_fitting', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='fitcomment',
            name='fitting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentaris', to='fitting.fitting'),
        ),
        migrations.CreateModel(
            name='GradingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('aprovada', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('creat_per', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_versions_creades', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Versió de grading',
                'verbose_name_plural': 'Versions de grading',
                'ordering': ['size_fitting', '-data'],
            },
        ),
        migrations.AddField(
            model_name='fitcomment',
            name='resolt_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentaris_resolts', to='fitting.gradingversion'),
        ),
        migrations.CreateModel(
            name='SizeFitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('codi', models.CharField(max_length=60, unique=True)),
                ('tipus', models.CharField(choices=[('Proto', 'Proto'), ('Fit', 'Fit'), ('SizeSet', 'SizeSet'), ('PP', 'PP'), ('TOP', 'TOP')], max_length=20)),
                ('estat', models.CharField(choices=[('Pendent', 'Pendent'), ('BaseOberta', 'Base oberta'), ('BaseTancada', 'Base tancada'), ('TallesGenerades', 'Talles generades'), ('Tancat', 'Tancat')], default='Pendent', max_length=30)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_tancament', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('creat_per', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_fittings_creats', to='accounts.userprofile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_fittings', to='models_app.model')),
                ('sf_pare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fills', to='fitting.sizefitting')),
            ],
            options={
                'verbose_name': 'Size & Fitting',
                'verbose_name_plural': 'Size & Fittings',
                'ordering': ['model', 'numero'],
                'unique_together': {('model', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='POMAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('desviacio', 'Desviació'), ('fora_rang', 'Fora de rang'), ('manca', 'Manca'), ('conflicte', 'Conflicte')], max_length=20)),
                ('valor_detectat', models.DecimalField(decimal_places=4, max_digits=10)),
                ('valor_esperat', models.DecimalField(decimal_places=4, max_digits=10)),
                ('z_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('estat', models.CharField(choices=[('Pendent', 'Pendent'), ('Acceptat', 'Acceptat'), ('Corregit', 'Corregit')], default='Pendent', max_length=20)),
                ('creat_per', models.CharField(default='sistema', max_length=100)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_resolucio', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pom_alerts', to='models_app.model')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='pom.pommaster')),
                ('resolt_per', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pom_alerts_resoltes', to='accounts.userprofile')),
                ('size_fitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pom_alerts', to='fitting.sizefitting')),
            ],
            options={
                'verbose_name': 'Alerta POM',
                'verbose_name_plural': 'Alertes POM',
            },
        ),
        migrations.AddField(
            model_name='gradingversion',
            name='size_fitting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_versions', to='fitting.sizefitting'),
        ),
        migrations.AddField(
            model_name='fitting',
            name='size_fitting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fittings', to='fitting.sizefitting'),
        ),
        migrations.CreateModel(
            name='FittingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_target', models.DecimalField(decimal_places=4, max_digits=10)),
                ('valor_mesurat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('delta_real', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('estat', models.CharField(choices=[('ok', 'OK'), ('avis', 'Avís'), ('error', 'Error')], default='ok', max_length=10)),
                ('nota', models.CharField(blank=True, max_length=200, null=True)),
                ('fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='fitting.fitting')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pom.pommaster')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pom.sizedefinition')),
            ],
            options={
                'verbose_name': 'Línia de fitting',
                'verbose_name_plural': 'Línies de fitting',
                'unique_together': {('fitting', 'pom', 'talla')},
            },
        ),
        migrations.CreateModel(
            name='GradedSpecLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_target', models.DecimalField(decimal_places=4, max_digits=10)),
                ('valor_pare', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('motiu_delta', models.CharField(blank=True, max_length=200, null=True)),
                ('estat', models.CharField(choices=[('ok', 'OK'), ('avis', 'Avís'), ('error', 'Error')], default='ok', max_length=10)),
                ('avis_text', models.CharField(blank=True, max_length=500, null=True)),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pom.pommaster')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pom.sizedefinition')),
                ('grading_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='fitting.gradingversion')),
            ],
            options={
                'verbose_name': 'Línia spec gradada',
                'verbose_name_plural': 'Línies spec gradades',
                'unique_together': {('grading_version', 'pom', 'talla')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='fitting',
            unique_together={('size_fitting', 'numero')},
        ),
    ]
