# Generated by Django 6.0.5 on 2026-05-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizefitting',
            name='base_tancada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sizefitting',
            name='data_tancament_base',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
