# Generated by Django 6.0.5 on 2026-05-25 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0002_sprint1a_new_fields'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessioFitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sessio', models.DateField()),
                ('hora_inici', models.TimeField(blank=True, null=True)),
                ('hora_fi', models.TimeField(blank=True, null=True)),
                ('durada_hores', models.FloatField(blank=True, null=True)),
                ('lloc', models.CharField(blank=True, max_length=200, null=True)),
                ('tipus', models.CharField(choices=[('Proto', 'Proto'), ('Fit Sample', 'Fit Sample'), ('Size Set', 'Size Set'), ('PP Sample', 'PP Sample'), ('Mixt', 'Mixt')], max_length=20)),
                ('temporada', models.CharField(blank=True, max_length=10, null=True)),
                ('any', models.IntegerField(blank=True, null=True)),
                ('estat', models.CharField(choices=[('Planificada', 'Planificada'), ('Confirmada', 'Confirmada'), ('Realitzada', 'Realitzada'), ('Anul·lada', 'Anul·lada')], default='Planificada', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_fitting', to='tenants.client')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessió de fitting',
                'verbose_name_plural': 'Sessions de fitting',
                'ordering': ['-data_sessio'],
            },
        ),
    ]
