# Generated by Django 6.0.5 on 2026-05-25 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fitting', '0003_sprint1b_new_models'),
        ('pom', '0002_garmentgroup_pomcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingversion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gradingversion',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gradingversion',
            name='creat_per',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grading_versions_creades', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='gradingversion',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='SFFitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitting_num', models.PositiveIntegerField()),
                ('tipus', models.CharField(choices=[('Proto', 'Proto'), ('Sample', 'Sample'), ('PPS', 'PPS')], max_length=20)),
                ('estat', models.CharField(choices=[('Obert', 'Obert'), ('Tancat', 'Tancat'), ('Anullat', 'Anul·lat')], default='Obert', max_length=20)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('data_tancament', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sf_fittings_responsable', to='accounts.userprofile')),
                ('size_fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sf_fittings', to='fitting.sizefitting')),
            ],
            options={
                'verbose_name': 'SF Fitting (wizard)',
                'verbose_name_plural': 'SF Fittings (wizard)',
                'ordering': ['size_fitting', 'fitting_num'],
                'unique_together': {('size_fitting', 'fitting_num')},
            },
        ),
        migrations.CreateModel(
            name='SFFittingLinia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pom', models.CharField(max_length=200)),
                ('talla', models.CharField(max_length=20)),
                ('valor_vigent', models.FloatField()),
                ('valor_nou', models.FloatField(blank=True, null=True)),
                ('estat_cella', models.CharField(choices=[('Pendent', 'Pendent'), ('OK', 'OK'), ('Modificat', 'Modificat')], default='Pendent', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='fitting.sffitting')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sf_fitting_linies', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Línia SF Fitting',
                'verbose_name_plural': 'Línies SF Fitting',
                'ordering': ['fitting', 'pom', 'talla'],
            },
        ),
        migrations.CreateModel(
            name='GradedSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(max_length=20)),
                ('graded_value_cm', models.FloatField()),
                ('grading_type_applied', models.CharField(choices=[('LINEAR', 'Linear'), ('STEP', 'Step'), ('FIXED', 'Fixed'), ('ZERO', 'Zero'), ('EXCEPTION', 'Exception')], max_length=20)),
                ('increment_applied_cm', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('grading_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_specs', to='fitting.gradingversion')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graded_specs', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Spec generat',
                'verbose_name_plural': 'Specs generats',
                'ordering': ['grading_version', 'pom', 'size_label'],
                'unique_together': {('grading_version', 'pom', 'size_label')},
            },
        ),
    ]
