# Generated by Django 6.0.5 on 2026-05-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0004_sprint3_4_grading_models'),
        ('models_app', '0010_sprint7a_design_freeze'),
        ('pom', '0006_sprint_s4_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomalert',
            name='desviacio_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pomalert',
            name='missatge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pomalert',
            name='nota_resolucio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pomalert',
            name='origen',
            field=models.CharField(default='FITTING', max_length=20),
        ),
        migrations.AddField(
            model_name='pomalert',
            name='resolt_per_user_id',
            field=models.IntegerField(blank=True, help_text='ID usuari cross-schema (Sprint S11)', null=True),
        ),
        migrations.AddField(
            model_name='pomalert',
            name='tolerancia_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pomalert',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pom_alerts', to='models_app.model'),
        ),
        migrations.AlterField(
            model_name='pomalert',
            name='pom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='pom.pommaster'),
        ),
        migrations.AlterField(
            model_name='pomalert',
            name='tipus',
            field=models.CharField(blank=True, choices=[('desviacio', 'Desviació'), ('fora_rang', 'Fora de rang'), ('manca', 'Manca'), ('conflicte', 'Conflicte')], default='desviacio', max_length=20),
        ),
        migrations.AlterField(
            model_name='pomalert',
            name='valor_detectat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pomalert',
            name='valor_esperat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
