# Generated by Django 6.0.5 on 2026-05-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0005_sprint_s11_pomalert_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedspec',
            name='generated_from_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
