# Generated by Django 6.0.5 on 2026-05-30 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sprint_s1_foundations'),
        ('fitting', '0007_remove_fitcommentfitxer_fit_comment_and_more'),
        ('models_app', '0021_basemeasurement_tolerancia_minus_and_more'),
        ('pom', '0011_pommaster_tolerancia_default_minus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('Proto', 'Proto'), ('Fit', 'Fit'), ('SizeSet', 'SizeSet'), ('PP', 'PP'), ('TOP', 'TOP')], max_length=20)),
                ('data', models.DateField()),
                ('model_persona', models.CharField(blank=True, default='', max_length=200)),
                ('assistents', models.CharField(blank=True, default='', max_length=300)),
                ('lloc', models.CharField(blank=True, default='', max_length=200)),
                ('estat', models.CharField(choices=[('Oberta', 'Oberta'), ('Tancada', 'Tancada'), ('Anullada', 'Anul·lada')], default='Oberta', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitting_sessions_creades', to='accounts.userprofile')),
                ('garment_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitting_sessions', to='models_app.garmentset')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitting_sessions', to='models_app.model')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitting_sessions_responsable', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Sessió de fitting',
                'verbose_name_plural': 'Sessions de fitting',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PieceFitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(choices=[('Pendent', 'Pendent'), ('OK', 'OK'), ('NO_OK', 'No OK'), ('EXCEPCIO', 'Excepció')], default='Pendent', max_length=10)),
                ('gate_motiu', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piece_fittings_creats', to='accounts.userprofile')),
                ('grading_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piece_fittings', to='fitting.gradingversion')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piece_fittings', to='models_app.model')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece_fittings', to='fitting.fittingsession')),
            ],
            options={
                'verbose_name': 'Fitting de peça',
                'verbose_name_plural': 'Fittings de peça',
                'ordering': ['session', 'model'],
            },
        ),
        migrations.CreateModel(
            name='FittingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitxer', models.ImageField(upload_to='fitting_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fitting.fittingsession')),
                ('piece_fitting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='fitting.piecefitting')),
            ],
            options={
                'verbose_name': 'Foto de fitting',
                'verbose_name_plural': 'Fotos de fitting',
                'ordering': ['session', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PieceFittingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(max_length=20)),
                ('valor_teoric', models.FloatField()),
                ('valor_real', models.FloatField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, default='', max_length=200)),
                ('piece_fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linies', to='fitting.piecefitting')),
                ('pom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pom.pommaster')),
            ],
            options={
                'verbose_name': 'Línia de fitting de peça',
                'verbose_name_plural': 'Línies de fitting de peça',
                'ordering': ['piece_fitting', 'pom', 'size_label'],
            },
        ),
        migrations.AddConstraint(
            model_name='fittingsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('garment_set__isnull', False), ('model__isnull', True)), models.Q(('garment_set__isnull', True), ('model__isnull', False)), _connector='OR'), name='fittingsession_set_xor_model'),
        ),
        migrations.AlterUniqueTogether(
            name='piecefitting',
            unique_together={('session', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='piecefittingline',
            unique_together={('piece_fitting', 'pom', 'size_label')},
        ),
    ]
