# Generated by Django 6.0.5 on 2026-05-30 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sprint_s1_foundations'),
        ('fitting', '0008_fittingsession_piecefitting_fittingphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingversion',
            name='aprovada_per',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_versions_aprovades', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='gradingversion',
            name='data_aprovacio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piecefitting',
            name='gate_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piecefitting',
            name='gate_per',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piece_fittings_gated', to='accounts.userprofile'),
        ),
    ]
