# Generated by Django 6.0.5 on 2026-05-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0010_delete_sffitting'),
    ]

    operations = [
        migrations.AddField(
            model_name='fittingsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fittingsession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fittingsession',
            name='estat',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Oberta', 'Oberta'), ('Tancada', 'Tancada'), ('Anullada', 'Anul·lada')], default='Oberta', max_length=20),
        ),
    ]
