# Generated by Django 6.0.5 on 2026-06-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0011_fittingsession_end_time_fittingsession_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fittingsession',
            name='fase',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dev', 'Dev'), ('Proto', 'Proto'), ('SizeSet', 'SizeSet'), ('PP', 'PP'), ('TOP', 'TOP')], max_length=20),
        ),
    ]
