# Generated by Django 6.0.5 on 2026-06-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_jornada_override'),
        ('fitting', '0012_alter_fittingsession_fase'),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingDurationStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_mostres', models.PositiveIntegerField(default=0)),
                ('mitjana', models.FloatField(default=0.0)),
                ('m2_acum', models.FloatField(default=0.0)),
                ('desviacio', models.FloatField(default=0.0)),
                ('darrera_actualitzacio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estadística de durada de fitting',
                'verbose_name_plural': 'Estadístiques de durada de fitting',
            },
        ),
        migrations.AddField(
            model_name='fittingsession',
            name='attendees',
            field=models.ManyToManyField(blank=True, help_text='Assistents interns: ocupen franja a la seva cua de planificació.', related_name='fitting_sessions', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='fittingsession',
            name='duracio_minuts',
            field=models.PositiveIntegerField(blank=True, help_text='Durada de la franja. Default en programar: 10 min × models.', null=True),
        ),
    ]
