# Generated by Django 6.0.5 on 2026-06-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0013_fittingdurationstat_fittingsession_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fittingsession',
            name='convocatoria',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID compartit per sessions creades juntes (bulk). Null = individual.', null=True),
        ),
    ]
