# Generated by Django 6.0.5 on 2026-06-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0014_fittingsession_convocatoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fittingsession',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Marca real de tancament (→Tancada).', null=True),
        ),
        migrations.AddField(
            model_name='fittingsession',
            name='motiu_anullacio',
            field=models.TextField(blank=True, default='', help_text="Motiu d'anul·lació (estat Anullada)."),
        ),
        migrations.AddField(
            model_name='fittingsession',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text="Marca real d'obertura (Programada→Oberta).", null=True),
        ),
    ]
