# Generated by Django 6.0.5 on 2026-08-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0020_instancia_cins'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomalert',
            name='capa',
            field=models.CharField(db_index=True, default='exterior', help_text='Capa de la mesura alertada: slug de pom.MeasurementLayer (per SLUG, mai per PK).', max_length=20),
        ),
        migrations.AddField(
            model_name='pomalert',
            name='instancia',
            field=models.CharField(db_index=True, default='', help_text="Instància del POM dins la capa: slug compost canònic. '' és la instància única.", max_length=60),
        ),
    ]
