# Generated by Django 6.0.5 on 2026-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0023_c4_g2_retira_comportes'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecefittingline',
            name='decisio',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Acceptada — la mesura real es dona per bona'), ('ADJUSTED', "Ajustada — s'ha rectificat i el valor rectificat val"), ('REJECTED', 'Rebutjada — la presa no val; NO sembra res')], db_index=True, default='', help_text="Veredicte de la cel·la (D-31.21). '' = sense decidir, que NO és ACCEPTED. Una línia REJECTED es desa i es veu, però cap camí de sembra la llegeix.", max_length=10),
        ),
    ]
