# Generated by Django 6.0.5 on 2026-08-10 08:58

"""SET-2/T2 — les unicitats de `fitting` incorporen el GARMENT, i les comportes el tanquen.

Parella de `models_app/0081` dins de la mateixa onada; l'argument sencer viu allà.
  · `GradedSpec`       → ('grading_version','pom','size_label','capa','instancia','garment')
  · `PieceFittingLine` → ('piece_fitting','pom','size_label','capa','instancia','garment')

Mateixes columnes + una → estrictament més permissiva, amb `garment` constant ('') a les
420 + 280 files de `fhort` i cap NULL (auditat per SQL abans d'aplicar).

⚠️ **NI LA VERSIÓ NI LA SESSIÓ GUANYEN L'EIX** (D6). `GradingVersion` i `SizeFitting` es
queden com estaven, i també `FittingSession` i `PieceFitting`: mesurar una prenda és
mesurar el model sencer, i el segell és del model per DECISIÓ DE DOMINI, no per limitació
tècnica. L'eix és de la LÍNIA i de l'SPEC —que són la presa i el resultat—, mai del
recipient que els agrupa.

Les dues comportes `*_garment_gate_set2` es retiren amb les seves germanes de
`models_app`, i amb la mateixa condició: el test de R3 verd abans (v. `models_app/0081`).
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0025_set2_t2_garment_columna'),
        ('pom', '0075_pommaster_codi_client_unic_ci'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradedspec',
            unique_together={('grading_version', 'pom', 'size_label', 'capa', 'instancia', 'garment')},
        ),
        migrations.AlterUniqueTogether(
            name='piecefittingline',
            unique_together={('piece_fitting', 'pom', 'size_label', 'capa', 'instancia', 'garment')},
        ),
        migrations.AddConstraint(
            model_name='gradedspec',
            constraint=models.CheckConstraint(condition=models.Q(('garment', '')), name='fitting_gradedspec_garment_gate_set2'),
        ),
        migrations.AddConstraint(
            model_name='piecefittingline',
            constraint=models.CheckConstraint(condition=models.Q(('garment', '')), name='fitting_piecefittingline_garment_gate_set2'),
        ),
    ]
