# Generated by Django 6.0.5 on 2026-08-12 09:34

"""SET-2/#12 — les dues comportes de `fitting` cauen, i cauen PRIMER.

Retira `fitting_gradedspec_garment_gate_set2` i
`fitting_piecefittingline_garment_gate_set2`, les dues germanes de T2 (`0026`). El motiu, el
context i les condicions de la retirada viuen a `models_app/0084`, que és la peça mare
d'aquesta onada; aquí només queda escrit **per què aquesta va abans**.

**L'ORDRE NO ÉS INDIFERENT, i ja ens va costar un incident.** Escriure una mesura base
encadena cap al motor (`generate_graded_specs`), que escriu els specs DINS de la mateixa
crida. Si s'obrís primer la comporta de la mesura i aquesta encara visqués, una base amb
`garment='02'` arribaria a un `GradedSpec` que encara exigeix `garment = ''` i petaria amb
`CheckViolation` — exactament el que va passar a C4 amb capa/instància i que es va haver de
corregir al commit `959147a5`.

Amb aquest ordre, la finestra intermèdia és inofensiva: el consumidor de sota queda obert
mentre l'escriptor de sobre encara està tancat, o sigui que durant els mil·lisegons entre
les dues migracions **cap escriptura nova no és possible** i cap no pot quedar a mitges.
Per això `models_app/0084` declara una dependència explícita d'aquesta: no és decoració,
és qui fixa l'ordre.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0026_set2_t2_garment_unicitats_comportes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gradedspec',
            name='fitting_gradedspec_garment_gate_set2',
        ),
        migrations.RemoveConstraint(
            model_name='piecefittingline',
            name='fitting_piecefittingline_garment_gate_set2',
        ),
    ]
