# Generated by Django 6.0.5 on 2026-09-23 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0028_e2_b1_presa_at'),
        ('models_app', '0087_m3_cicle_vida_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingSisterDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_actual_abans', models.FloatField()),
                ('valor_proposat', models.FloatField()),
                ('regla_text', models.CharField(blank=True, default='', max_length=255)),
                ('valor_final', models.FloatField()),
                ('decisio', models.CharField(choices=[('MANTINGUT', 'Mantingut — es conserva el valor que ja tenia'), ('PROPOSTA', "Proposta usada — s'aplica el valor calculat per la derivació"), ('MANUAL', 'Valor manual — el tècnic ha introduït un valor propi')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sister_decisions', to='models_app.basemeasurement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitting_sister_decisions', to=settings.AUTH_USER_MODEL)),
                ('piece_fitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sister_decisions', to='fitting.piecefitting')),
            ],
            options={
                'verbose_name': 'Decisió de germana (consentiment de fitting)',
                'verbose_name_plural': 'Decisions de germana (consentiment de fitting)',
                'ordering': ['piece_fitting', 'base_measurement'],
                'constraints': [models.UniqueConstraint(fields=('piece_fitting', 'base_measurement'), name='fittingsisterdecision_unica_per_pf_i_germana')],
            },
        ),
    ]
