# Generated by Django 6.0.5 on 2026-06-05 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackofficeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('COMERCIAL', 'Comercial'), ('FACTURACIO', 'Facturació'), ('SUPORT', 'Suport')], max_length=20)),
                ('actiu', models.BooleanField(default=True)),
                ('data_alta', models.DateField(auto_now_add=True)),
                ('ultim_acces', models.DateTimeField(blank=True, null=True)),
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='backoffice_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BackofficeActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accio', models.CharField(max_length=100)),
                ('objecte_tipus', models.CharField(blank=True, max_length=100)),
                ('objecte_id', models.CharField(blank=True, max_length=100)),
                ('detall', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuari', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accions', to='backoffice.backofficeuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
