# Generated by Django 6.0.5 on 2026-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_backoffice_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConsumptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi_client', models.CharField(max_length=3)),
                ('period', models.CharField(max_length=7)),
                ('opaque_ref', models.UUIDField(unique=True)),
                ('merited_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-merited_at'],
            },
        ),
    ]
