# Generated by Django 6.0.5 on 2026-06-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_model_consumption_event'),
        ('tenants', '0003_client_adreca_vat_contactes_comercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('descripcio', models.TextField(blank=True, default='')),
                ('tipus', models.CharField(choices=[('tier_fee', 'Quota base tier'), ('model_count', 'Per model iniciat'), ('manual', 'Manual (setup/formació)')], max_length=20)),
                ('actiu', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tipus', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TenantContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField(blank=True, null=True)),
                ('actiu', models.BooleanField(default=True)),
                ('nota', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='tenants.client')),
            ],
            options={
                'ordering': ['-data_inici'],
            },
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preu', models.DecimalField(decimal_places=4, max_digits=10)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('inclosos', models.IntegerField(default=0)),
                ('actiu', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='backoffice.servicecatalog')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backoffice.tenantcontract')),
            ],
            options={
                'ordering': ['service__tipus', 'service__code'],
                'unique_together': {('contract', 'service')},
            },
        ),
    ]
