# Generated by Django 6.0.5 on 2026-06-07 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_service_catalog_and_contracts'),
        ('tenants', '0003_client_adreca_vat_contactes_comercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('tipus', models.CharField(choices=[('auto', 'Automàtica'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('estat', models.CharField(choices=[('esborrany', 'Esborrany'), ('emesa', 'Emesa'), ('pagada', 'Pagada'), ('cancel·lada', 'Cancel·lada')], default='esborrany', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emesa_at', models.DateTimeField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenants.client')),
            ],
            options={
                'ordering': ['-period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.CharField(max_length=200)),
                ('quantitat', models.DecimalField(decimal_places=4, max_digits=10)),
                ('preu_unit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='backoffice.invoice')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='backoffice.servicecatalog')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('tipus', 'auto')), fields=('client', 'period', 'tipus'), name='unique_auto_invoice_per_client_period'),
        ),
    ]
