# Generated by Django 6.0.5 on 2026-07-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_invoice_and_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('descripcio', models.TextField(blank=True, default='')),
                ('seleccio', models.JSONField(blank=True, default=dict)),
                ('is_default_free', models.BooleanField(default=False)),
                ('actiu', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_free', True)), fields=('is_default_free',), name='unique_default_free_seed_profile')],
            },
        ),
    ]
