# Generated by Django 6.0.5 on 2026-07-14 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_seedprofile'),
        ('tenants', '0005_alter_plan_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('TERMES', 'Termes i condicions'), ('PRIVACITAT', 'Política de privacitat'), ('DPA', 'Acord de tractament de dades (DPA)'), ('SLA', 'Acord de nivell de servei (SLA)')], max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('actiu', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tipus', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_versio', models.PositiveIntegerField()),
                ('contingut', models.TextField(blank=True, default='')),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('estat', models.CharField(choices=[('DRAFT', 'Esborrany'), ('PUBLICADA', 'Publicada')], default='DRAFT', max_length=10)),
                ('data_publicacio', models.DateTimeField(blank=True, null=True)),
                ('requereix_reacceptacio', models.BooleanField(default=False, help_text='Si True, els clients que havien acceptat versions anteriors han de reacceptar (apareix a pending/ i al gate del /me del tenant).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='backoffice.legaldocument')),
            ],
            options={
                'ordering': ['document', '-numero_versio'],
            },
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_by', models.CharField(help_text='Email/identificador de qui va clicar.', max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metode', models.CharField(choices=[('CHECKBOX', 'Checkbox UI'), ('API', 'API')], default='CHECKBOX', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_acceptances', to='tenants.client')),
                ('versio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='backoffice.legaldocumentversion')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='legaldocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'numero_versio'), name='unique_versio_per_document'),
        ),
        migrations.AddConstraint(
            model_name='legalacceptance',
            constraint=models.UniqueConstraint(fields=('client', 'versio'), name='unique_acceptance_per_client_versio'),
        ),
    ]
