# Generated by Django 6.0.5 on 2026-07-17 12:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_legaldocument_legaldocumentversion_legalacceptance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('format', models.CharField(default='{codi}-{any}-{num:04d}', help_text='Plantilla del número. Claus: {codi} {any} {any2} {num}.', max_length=60)),
                ('reinici_anual', models.BooleanField(default=True)),
                ('any_actual', models.IntegerField(blank=True, null=True)),
                ('comptador', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sèrie de factures',
                'verbose_name_plural': 'Sèries de factures',
                'ordering': ['codi'],
            },
        ),
        migrations.CreateModel(
            name='VATRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('percentatge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="0 per als règims exempts o d'inversió del subjecte passiu.", max_digits=5)),
                ('regim_default', models.CharField(blank=True, default='', max_length=30)),
                ('mencio_legal', models.TextField(blank=True, default='', help_text='Text obligatori al PDF (p.ex. inversió del subjecte passiu, exempció).')),
                ('actiu', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Tipus d'IVA",
                'verbose_name_plural': "Tipus d'IVA",
                'ordering': ['-percentatge', 'codi'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('regim_default', ''), _negated=True), fields=('regim_default',), name='uniq_vat_default_per_regim')],
            },
        ),
    ]
