# Generated by Django 6.0.5 on 2026-07-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_invoiceserie_vatrate'),
        ('tenants', '0005_alter_plan_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='base_imposable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='num_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quota_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rectifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rectificatives', to='backoffice.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='backoffice.invoiceserie'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='pct_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='quota_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='backoffice.vatrate'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tipus',
            field=models.CharField(choices=[('auto', 'Automàtica'), ('manual', 'Manual'), ('rectificativa', 'Rectificativa')], default='auto', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('numero', ''), _negated=True), fields=('serie', 'numero'), name='uniq_numero_per_serie'),
        ),
    ]
