# Generated by Django 6.0.5 on 2026-07-17 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_invoice_base_imposable_invoice_num_seq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconsumptionevent',
            name='exclos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelconsumptionevent',
            name='exclos_motiu',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='modelconsumptionevent',
            name='invoice_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_events', to='backoffice.invoiceline'),
        ),
        migrations.AddField(
            model_name='tenantcontract',
            name='periodicitat',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensual', max_length=12),
        ),
    ]
