# Generated by Django 6.0.5 on 2026-07-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_modelconsumptionevent_exclos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconsumptionevent',
            name='actor_schema',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
    ]
