# Generated by Django 6.0.5 on 2026-07-23 06:52

from django.db import migrations


def backfill_actor_fhort(apps, schema_editor):
    """Veritat històrica: TOTS els 31 events existents es van meritar des del tenant `fhort`
    (los és buit, BRW és un customer no un tenant). Se'ls fixa actor_schema='fhort'. Additiu i
    idempotent: només toca els que encara no en tenen (actor_schema='')."""
    Event = apps.get_model('backoffice', 'ModelConsumptionEvent')
    Event.objects.filter(actor_schema='').update(actor_schema='fhort')


def unbackfill(apps, schema_editor):
    Event = apps.get_model('backoffice', 'ModelConsumptionEvent')
    Event.objects.filter(actor_schema='fhort').update(actor_schema='')


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_modelconsumptionevent_actor_schema'),
    ]

    operations = [
        migrations.RunPython(backfill_actor_fhort, unbackfill),
    ]
