# Generated by Django 6.0.5 on 2026-09-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_backfill_actor_schema_fhort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('empresa', models.CharField(blank=True, default='', max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('missatge', models.TextField()),
                ('idioma', models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('ca', 'Català')], max_length=2)),
                ('pagina_origen', models.CharField(blank=True, default='', max_length=300)),
                ('consentiment', models.BooleanField(default=False)),
                ('privacy_version', models.CharField(max_length=40)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('estat', models.CharField(choices=[('nou', 'Nou'), ('contactat', 'Contactat'), ('tancat', 'Tancat')], default='nou', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('notificat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
