# Generated by Django 6.0.5 on 2026-09-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0012_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interes',
            field=models.CharField(blank=True, choices=[('saas', 'SaaS'), ('studio', 'Studio'), ('early', 'Early'), ('other', 'Other')], default='', max_length=20),
        ),
    ]
